### ISSUE TITLE
4.15 Compile Errors

### ISSUE THREAD

**Issue by TomOnGithub** [ufna/VaRest#100]
Had to add #include "EdGraphUtilities.h" in Varest_BreakJson.cpp to make it compile with 4.15 version. Otherwise received the error  C2653: 'FEdGraphUtilities': is not a class or namespace name

**Comment by Dr-Jerm** [comment]
I just upgraded to 4.15 and ran into the same issue. Have you had any luck getting it running @TomOnGithub?

**Comment by TomOnGithub** [comment]
Yes, just added the include. It compiled and runs like before.

**Comment by ufna** [comment]
I think it was old version in marketplace for some time, because it's already fixed in develop :) Thanks for pointing that, I'll make sure that marketplace version is up-to-date
