### ISSUE TITLE
Build/Packaging fails for shipping build from the Project Launcher

### ISSUE THREAD

**Issue by MADSOFTWARE** [ufna/VaRest#105]
The release don't seem to work. Firstly before launching it warns that it is not compatible with 4.16, launching anyways in editor (with a clean 4.16 project with source files) tho it seems to work fine, you can add nodes and they work, but it will completely fail when building a shipping build from the project launcher.

It seems that the project finds no files for the plugin when it tries to package it and all functions using the plugin throws 'missing function' errors.

"Cook: LogUObjectGlobals:Warning: Failed to load '/Script/VaRestPlugin': Can't find file '/Script/VaRestPlugin'
Cook: LogLinker:Warning: Can't find file '/Script/VaRestPlugin' etc etc
"

Details on how to setup Project Launcher for shipping release build:
https://docs.unrealengine.com/latest/INT/Engine/Deployment/Releasing/

**Comment by MADSOFTWARE** [comment]
This problem is solved by opening VaRestPlugin.uplugin and changing engine version from 4.11.0 to 4.16.0 and this allows the shipping release build to complete without errors.

**Comment by ufna** [comment]
Hm, thanks, I've fixed it now :)
