### ISSUE TITLE
Add GraphQL API support

### ISSUE THREAD

**Issue by ufna** [ufna/VaRest#106]
http://graphql.org/

**Comment by ufna** [comment]
https://habrahabr.ru/post/332850/

**Comment by jans32** [comment]
There is c++ graphql parser available here https://github.com/graphql/libgraphqlparser. Maybe it could be used with graphql schema language in Unreal. But I' don't have time nor enough tool creation experience to tackle this kind of task.

**Comment by ufna** [comment]
Not for now.

**Comment by brybalicious** [comment]
Hi @ufna still not on your radar? Many interesting APIs are unfortunately not using REST but GraphQL.
