### ISSUE TITLE
HI~ Development Server Build Error Help me plz

### ISSUE THREAD

**Issue by NakGun** [ufna/VaRest#107]
Im mmo starter kit tutorial following
https://www.youtube.com/watch?v=oRETzmGEqNo&list=PL_fgmB1BERFW_wI3D4QVAr-PUpXmzqezw&index=7

but Development Server Build error (Development Edit is Okey)
i search google..not find answer please help me
sorry my english is bad..^^;;

my unreal 4.16
varest : maketplace version and installed engine(4.16)

1>Performing 16 actions (4 in parallel)
1>SharedPCH.Engine.cpp
1>Module.VaRestPlugin.cpp
1>VaRestPlugin.generated.cpp
1>E:\Paragon\UE_4.16\Engine\Source\Runtime\Engine\Classes\Engine/NetSerialization.h(18): fatal error C1083: 포함 파일을 열 수 없습니다. 'NetSerialization.generated.h': No such file or directory
1>E:\Paragon\UE_4.16\Engine\Source\Runtime\Engine\Classes\Engine/NetSerialization.h(18): fatal error C1083: 포함 파일을 열 수 없습니다. 'NetSerialization.generated.h': No such file or directory
1>E:\Paragon\UE_4.16\Engine\Source\Runtime\InputCore\Classes\InputCoreTypes.h(10): fatal error C1083: 포함 파일을 열 수 없습니다. 'InputCoreTypes.generated.h': No such file or directory
1>ERROR : UBT error : Failed to produce item: E:\ProjectUnreal\Fighters\Plugins\VaRest\Binaries\Win64\UE4Server-VaRestPlugin.lib
1>Total build time: 3.99 seconds (Local executor: 0.00 seconds)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(44,5): error MSB3075: "E:\Paragon\UE_4.16\Engine\Build\BatchFiles\Build.bat FightersServer Win64 Development "E:\ProjectUnreal\Fighters\Fighters.uproject" -waitmutex" 명령이 종료되었습니다(코드: 5). 이 명령을 실행할 권한이 있는지 확인하세요.

**Comment by ufna** [comment]
@NakGun for dedicated server build please use github version of the plugin (and install it to the project instead of engine) and all will be ok ;)
