### ISSUE TITLE
VaRest plugins doesnt load in UE4.16 source version

### ISSUE THREAD

**Issue by Masterchief89** [ufna/VaRest#108]
Dowloaded latest VaRest plugin for here and placed it into the Plugins folder of the Empty test project made with **UE 4.16.2** **Source version**. Opened the project went to the **Plugins** and selected VaRest plugin to be enabled, restared and got message that i Need to rebuild, rebuild Failed. Triyed Rebuild in VS 2017 - gives me error messages:

Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS0618	'UnrealBuildTool.ModuleRules.ModuleRules()' is obsolete: 'Please change your module constructor to take a ReadOnlyTargetRules parameter, and pass it to the base class constructor (eg. "MyModuleRules(ReadOnlyTargetRules Target) : base(Target)").'	SourceTest	c:\Users\MasterChief\Documents\Unreal Projects\SourceTest\Plugins\VaRestPlugin\Source\VaRestEditorPlugin\VaRestEditorPlugin.Build.cs	7	

Screenshot:
![image](https://user-images.githubusercontent.com/11280250/28274544-dbbdae86-6b19-11e7-9170-bbe79373d4f6.png)

Hopefully its me that made a mistake somewhere. Assistance would be great!

**Comment by ufna** [comment]
Please update plugin to the latest version
