### ISSUE TITLE
Update to Unreal Engine v 4.17

### ISSUE THREAD

**Issue by nocivus** [ufna/VaRest#109]
Unreal version 4.17 is out :)

**Comment by nocivus** [comment]
Created a pull request, here: https://github.com/ufna/VaRest/pull/110

**Comment by ufna** [comment]
Hi guys,

I'll make an update tomorrow, sorry for delay

**Comment by nocivus** [comment]
No problem. Open source means we can change it ourselves ;). Btw, do you
have any examples of using the plugin via C++?

**Comment by ufna** [comment]
Done)

I have plan to add some exaple to docs, but I don't know when yet :(
