### ISSUE TITLE
6.4.0 does not work with 6.4.1

### ISSUE THREAD

**Issue by MJBrune** [ufna/VaRest#11]
Steps:
Download 1.1-RC7
Add it to a 6.4.1 UE4 project.
Note it doesn't work and complains about compatibility of the plugin.

Fix: Looks like a recompile for binaries is needed again for ease of use.

**Comment by ufna** [comment]
This version is compatible with UE 4.7.x . Please use https://github.com/ufna/VaRest/releases/tag/1.1-rc6 this release instead.

**Comment by MJBrune** [comment]
That version doesn't work with 4.6.1 either. Are you basically saying you only support 4.4 or an unstable preview of 4.7.0?

**Comment by ufna** [comment]
What's the error you got on project compilation?

Last plugin version supports only 4.7 and upper.

**Comment by MJBrune** [comment]
VaRestPlugin.dll (API version 2357962), but it was incompatible with the current engine API version (2369412). This is likely a stale module that must be recompiled.
LogInit:Warning: Incompatible or missing module: UE4Editor-VaRestPlugin.dll

**Comment by ufna** [comment]
You need to recompile your project then (it's required for UE4 plugins to have C++ project)

**Comment by MJBrune** [comment]
Hmm I had this project with VaRest without C++ code at 4.4 is this a new requirement?

**Comment by ufna** [comment]
It's very old requirement (from the beginning of the engine) :) Without C++ project you can't even package the game.

When binaries are pre-build with EXACT version you're using, you won't met the problem that you described. But it's better to move your project to simple C++ one.

**Comment by BZInhance** [comment]
Yeah you pretty much have too now. Whenever there's a new version of UE, I create a blank C++ project. I drop all the custom plugins I use inside and I compile the solution. It generates the dll for the plugins for this version.

**Comment by MJBrune** [comment]
Alright, thanks. Will do.
