### ISSUE TITLE
Request callbacks going STALE

### ISSUE THREAD

**Issue by lekjart** [ufna/VaRest#111]
I have been battling an issue when using this plugin under certain circumstances where the request callbacks go STALE within the span of calling the URL and receiving response, such that the callback specified is never called.

I stepped through the engine source using vanilla Unreal 4.16.3 to find out where things go wrong. I have narrowed it down to an issue when invoking the `CallURL ` node from within the Init event of a custom game instance blueprint. When I do this, the call is performed correctly within the HTTP subsystem and the response comes back into `FCurlHttpRequest::FinishedRequest()` with all correct data, but when it reaches the line where it would normally call the specified callback delegate it fails because the underlying delegate is STALE. Basically the following fails silently in CurlHttp.cpp:

```
// Mark last request attempt as completed successfully
CompletionStatus = EHttpRequestStatus::Succeeded;
// Call delegate with valid request/response objects
OnProcessRequestComplete().ExecuteIfBound(SharedThis(this),Response,true);
```
In my case this only fails in builds or when running standalone, but works fine when playing from editor. When I move CallURL to some other later entry point, e.g. in the BeginPlay of my start level, everything works fine under all circumstances.

I wonder if the callback delegate is only kept with a weak reference and somehow goes out of scope during the init phase of the game instance, but I am not even sure this is specifically related to game instance.

I am fine with moving my entry point from the game instance, but I suspect there is still some underlying problem with how references to the callback delegate are kept which might result in random failures under certain circumstances and I am not familiar enough with this code to try to find out exactly where the delegate gets unbound.

**Comment by lekjart** [comment]
And just as an experiment, I tried to explictly build the VARest request object from scratch and save it as a variable in my game instance, just to make sure I would have at least one reference count to it, and that seemed to fix it, but I doubt this is the intended usage pattern.

**Comment by ufna** [comment]
Currently `CallURL` has really bad implementation, I'll fix it soon.

**Comment by Skylonxe** [comment]
We have run into same issue in our project. Requests sometimes did not have callback called. For now we solved it with caching all request into array. Anyways, it's nasty bug.

**Comment by zn960829** [comment]
> We run into same issue in our project. Requests sometimes did not have callback called. For now we solved it with caching all request into array. Anyways, it's nasty bug.

Where do you cache all request in?  I  meet same issue. I try to cache them in mygameinstance,but it doesn't work.

**Comment by zn960829** [comment]
> Currently `CallURL` has really bad implementation, I'll fix it soon.

About two years passed,did you fix it?

**Comment by Skylonxe** [comment]
> > We run into same issue in our project. Requests sometimes did not have callback called. For now we solved it with caching all request into array. Anyways, it's nasty bug.
> 
> Where do you cache all request in? I meet same issue. I try to cache them in mygameinstance,but it doesn't work.

Any UObject is fine but do not forget to tag your TArray with UPROPERTY() macro.

**Comment by zn960829** [comment]
> > > We run into same issue in our project. Requests sometimes did not have callback called. For now we solved it with caching all request into array. Anyways, it's nasty bug.
> > 
> > 
> > Where do you cache all request in? I meet same issue. I try to cache them in mygameinstance,but it doesn't work.
> 
> Any UObject is fine but do not forget to tag your TArray with UPROPERTY() macro. There are also build in functions for this in GameInstance: RegisterReferencedObject(), UnregisterReferencedObject()

Thank you very much.I have solved it .

**Comment by klinikk** [comment]
The problem is that RequestMap in UVaRestLibrary that holds all requests is not marked as UPROPERTY and it couldn't be because is static.  GC detects all request as unreferenced objects.

My work around is call Request->AddToRoot() in UVaRestLibrary::CallUR(...) and call Request->RemoveFromRoot() in UVaRestLibrary::OnCallComplete(...)
