### ISSUE TITLE
Update for Epic Market

### ISSUE THREAD

**Issue by NatsuZirok** [ufna/VaRest#112]
Владимир, пожалуйста, обновите плагин в маркете. А то некоторые люди не могут понять, откуда качать и что делать(я не в их числе).

**Comment by ufna** [comment]
К сожалению причина задержки в Эпиках - заявку на апдейт плагина я отправил уже очень давно :( Остаётся только ждать и отсылать всех на гитхаб.

Спасибо за пинг, я чекну что пишут на маркетплейсе!
