### ISSUE TITLE
Double quoting json string value

### ISSUE THREAD

**Issue by Rko619** [ufna/VaRest#114]
i am sending a path "D:\19_08_2017" for constructing json string value ,after constructing into json array,while encoding it the string in the file is like "D:\\19_08_2017" it is adding "\" extra,is it a known bug?

**Comment by ufna** [comment]
Hi @Rko619 ,

I didn't understand what are you doing exactly :) There shouldn't be any additional quotes in encoding/decoding mechanism. Please provide more details
