### ISSUE TITLE
Android, Packeged fine but app won't start

### ISSUE THREAD

**Issue by xcibe95x** [ufna/VaRest#119]
So i just tried to build an app to comunicate with my database
tried everything even a blank project with just the plugin and not
when the plugin in is on the app just won't run
Used api level 22 and 23 nothing.
What i am doing wrong?

**Comment by xcibe95x** [comment]
Ps. Engine version 4.16 the plugin is installed manually

**Comment by dylangartland1** [comment]
Does the plugin work correctly on Desktop? If so, have you tried enabling internet permissions on your app?

You can do this by opening `Project Settings -> Platforms -> Android`. Then scroll down to Advanced `APKPackaging `and under `Extra Permissions` add '`android.permission.INTERNET`'

**Comment by xcibe95x** [comment]
Yes the plugin work on Desktop, it's just on android that the app crash on start
i tried to add android.permission.internet same thing.

**Comment by ufna** [comment]
Hi @xcibe95x 

Please provide log from the device.

**Comment by xcibe95x** [comment]
It crash before it can save a log, i've read about an adb command that
gives a log ill try tomorrow

Il 4 ott 2017 14:46, "Vladimir Alyamkin" <notifications@github.com> ha
scritto:

**Comment by xcibe95x** [comment]
i used the adb command and is a general device log, it saves the app log in /data/ folder wich is accessible only with root, so maybe i will root the phone and check inside there, anyway i found this, but i'm not sure it's the main problem.
10-05 20:20:10.622  4534  4534 W linker  : /data/app/com.constraints.test-1/lib/arm/libOVRPlugin.so: is missing DT_SONAME will use basename as a replacement: "libOVRPlugin.so"

**Comment by ufna** [comment]
@xcibe95x 

I've just checked the last version on my device, please update plugin and try again. If it doesn't work, please try it with empty UE4 project

**Comment by ufna** [comment]
Hah, I've got it by myself first time)

**Comment by xcibe95x** [comment]
> 
> 
> Hah, I've got it by myself first time)

Did you figure out how to fix in the end? i've come to a point where i need this to publish a game on the playstore and after using latest engine version and sdk it's still crashing
