### ISSUE TITLE
Can't do post and x-www-form-urlencoded

### ISSUE THREAD

**Issue by BZInhance** [ufna/VaRest#12]
Hello,

I'm trying to do POST requests with x-www-form-urlencoded content type and I'm having a hard time to add the data to my request. I don't see how you go from a json structure to a mykey1=myval1&mykey2=mayval2&mykey3=.. single line string.

Best,

Ben

**Comment by ufna** [comment]
1. Construct Json request as described here - https://github.com/ufna/VaRest/wiki/Plugin-Usage (Simple GET request)
2. Construct Json object and set string parameters you want, f.e. set mykey1=myval1, etc.
3. Then evaluate the request - it will be automatically processed from json object to single line string in URL.

**Comment by BZInhance** [comment]
But can you do also POST that way ? The API I'm using only accepts POST...

**Comment by BZInhance** [comment]
OK from what I see in the source code, the x-www-form-urlencoded goes directly in the URL so it's not going to work for POST.

**Comment by BZInhance** [comment]
I fixed it. I'll email you the code.

**Comment by BZInhance** [comment]
I don't have permission to upload from git so I put the file here :
https://www.wetransfer.com/downloads/8e7e898b6ec4ac3219562c6276afb07b20150106011144/2d56d9593a2552c7dff94e5983eee94620150106011144/999c5e

I've just modified the case ERequestContentType::x_www_form_urlencoded: in the ProcessRequest method.

case ERequestContentType::x_www_form_urlencoded:
	{
		HttpRequest->SetHeader("Content-Type", "application/x-www-form-urlencoded");

		FString UrlParams = "";
		uint16 ParamIdx = 0;

		// Loop through all the values and prepare additional url part
		for (auto RequestIt = RequestJsonObj->GetRootObject()->Values.CreateIterator(); RequestIt; ++RequestIt)
		{
			FString Key = RequestIt.Key();
			FString Value = RequestIt.Value().Get()->AsString();

			if (!Key.IsEmpty() && !Value.IsEmpty())
			{
				UrlParams += ParamIdx == 0 ? "" : "&";
				UrlParams += Key + "=" + Value;
			}

			ParamIdx++;
		}

		switch (RequestVerb)
		{
		case ERequestVerb::GET:
			// Apply params to the url
			HttpRequest->SetURL(HttpRequest->GetURL() + "?" + UVaRestRequestJSON::PercentEncode(UrlParams));
			break;
		case ERequestVerb::POST:
			// Set Json content
			HttpRequest->SetContentAsString(UrlParams);
			break;
		default:
			break;
		}

		break;
	}
