### ISSUE TITLE
Request Response Content string empty

### ISSUE THREAD

**Issue by brunogbrito** [ufna/VaRest#127]
Hello there,

I've just noticed that in 4.18 the Response Content string variable from the request node is coming empty when making an GET request.  I can see the feedback in the log, but the response content variable itself prints nothing in the Print String.

**Comment by brunogbrito** [comment]
I just saw that it's not a bug :) 
It was modified to remove the print from that variable if it the request succeeds. Would be good if we cold still have that print ;) 

tks for your time!

**Comment by ufna** [comment]
Hi @brunogbrito ,

I've added special getter for it now ;)
