### ISSUE TITLE
[UE 4.15] Compile error when packaging game using VaRest

### ISSUE THREAD

**Issue by paulevans** [ufna/VaRest#128]
Hello - I've been trying to get this plugin to package from source for a few days now.  

I got the source working through Visual Studio, but as soon as I go to package I just keep hitting one error after another.

Would you mind taking a look? I'll update a branch with a pull request if I manage to figure it out myself, but this is my first go at debugging an Unreal plugin and I'm feeling that.

Cheers, Paul

Repro:
Have a game project that uses VaRest
Go to File -> Package Project -> Windows -> Windows (64 bit)

Expect:
No errors

Actual:
Many compile errors.

Cards on the table, I've not used a stock version of unreal yet - so will try that another time.

**Comment by jans32** [comment]
Hi,
Go to your project root folder and delete ".vs, Binaries, Intermediate, .sln". Right click on blue project file, press "Generate project files". Recompile in VS. And it should build in the editor. Make sure that you have not modified plugin files.

**Comment by paulevans** [comment]
Thanks for the reply. I'm stuck on 4.15 so had to mess around in my own branch. I've been selectively taking fixes going forwards but even on an untouched revision I've not managed to get package build working yet.

Do you have a revision for 4.15 that you know for certain works with the package build?

I deleted the intermediate files as you suggested - when developing a plug-in do you have to do that each iteration?

On my current *package* build after cleaning up the intermediate files I'm getting these errors. Visual Studio doesn't complain :/

`VaRest\Source\VaRestPlugin\Classes\VaRestJsonObject.h(23): error C2275: 'UStrProperty': illegal use of this type as an expression
ue4\engine\source\runtime\core\public\UObject/UObjectHierarchyFwd.h(31): note: see declaration of 'UStrProperty'
UE4\Engine\Plugins\CertainAffinity\VaRest\Source\VaRestPlugin\Classes\VaRestJsonObject.h(23): error C2065: 'Z_Param_FieldName': undeclared identifier
`

There are more errors but those are the first.  The others are probably knock-ons from the above.

**Comment by ufna** [comment]
Hi @paulevans ,

Are you using marketplace version or Github one? As I remember, the https://github.com/ufna/VaRest/releases/tag/v1.1-r15 release should work fine.

**Comment by paulevans** [comment]
I reset all my changes to the commit for the tag and it doesn't compile as-is in visual studio because of the header file order. 

![image](https://user-images.githubusercontent.com/719048/32507587-73a01c34-c3ad-11e7-8d8c-a729e2dd3c60.png)

I will keep plugging away at this here and there over the next few days.  If I do get something that works I will update my own branch and link back here.  If not then assume I didn't get it working on my own.

**Comment by ufna** [comment]
@paulevans please check https://docs.unrealengine.com/latest/INT/Programming/UnrealBuildSystem/IWYUReferenceGuide/ and disable IWYU for plugin. It wasn't IWYU-compatible for UE 4.15 version 

Just set PCHUsage = PCHUsageMode.UseSharedPCHs; as I did it here: https://github.com/ufna/VaRest/commit/1a46615a224c1ddf5822ca80cf48fb304cd7f89d#diff-41711fdde60258b73b4726fed50d3a31

**Comment by ufna** [comment]
Or you can cherry pick few latest commits from me into develop branch :)

**Comment by jans32** [comment]
I'm on 4.18 and VS 2017 with latest VaRest version. I had some errors building packaged build, VS would compile fine, but the editor refused to build. So I cleared those folders and it is building fine now. I don't really remember, but I think I had different errors. Might be some incomparability issues then.

**Comment by jans32** [comment]
I'm on 4.18 and VS 2017 with latest VaRest version. I had some errors building packaged build, VS would compile fine, but the editor refused to build. So I cleared those folders and it is building fine now. I don't really remember, but I think I had different errors. Might be some incomparability issues then.

**Comment by Swdanylenko** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error		All source files in module "VaRestPlugin" must include the same precompiled header first.  Currently "E:\Spatial\ACO\workers\unreal\Game\Plugins\VaRestPlugin\Source\VaRestPlugin\Classes\VaRestJsonObject.h" is included by most of the source files.  The following source files are not including "E:\Spatial\ACO\workers\unreal\Game\Plugins\VaRestPlugin\Source\VaRestPlugin\Classes\VaRestJsonObject.h" as their first include:	ACO	E:\Spatial\ACO\workers\unreal\Game\Intermediate\ProjectFiles\EXEC	1	
wtb 4.16 update

**Comment by Swdanylenko** [comment]
same problem EXEC : error : All source files in module "VaRestPlugin" must include the same precompiled header first.

**Comment by ufna** [comment]
@Swdanylenko Please provide additional details. Are you using the marketplace version for UE 4.16, or the Github one? If it's a Github version, which one exactly?

**Comment by Swdanylenko** [comment]
im using github release 4.16.3 builded from source + github master thread varest plugin
tried also old varests like r15 r16 that does not make difference.
however. ive added varest header to every source file and it works fine in editor, tho if i try to build - keep getting Can't find file '/Script/VaRestPlugin'. dont think these errors are connected

**Comment by rotacak** [comment]
Same for me. It will compile ok in editor, ok in visual studio, but it will fail in commandline packaging. I disabled IWYU but get:

UnrealBuildTool: ERROR: All source files in module "VaRestPlugin" must include the same precompiled header first.  Currently "g:\UE4.15\Engine\Plugins\VaRestPlugin\Source\VaRestPlugin\Classes\VaRestJsonObject.h" is included by most of the source files.  The following source files are not including "g:\UE4.15\Engine\Plugins\VaRestPlugin\Source\VaRestPlugin\Classes\VaRestJsonObject.h" as their first include:
UnrealBuildTool:
UnrealBuildTool: g:\UE4.15\Engine\Plugins\VaRestPlugin\Source\VaRestPlugin\Private\VaRestJsonValue.cpp (including g:\UE4.15\Engine\Plugins\VaRestPlugin\Source\VaRestPlugin\Classes\VaRestJsonValue.h)
UnrealBuildTool: g:\UE4.15\Engine\Plugins\VaRestPlugin\Source\VaRestPlugin\Private\VaRestLibrary.cpp (including g:\UE4.15\Engine\Plugins\VaRestPlugin\Source\VaRestPlugin\Classes\VaRestLibrary.h)
UnrealBuildTool: g:\UE4.15\Engine\Plugins\VaRestPlugin\Source\VaRestPlugin\Private\VaRestPlugin.cpp (including g:\UE4.15\Engine\Plugins\VaRestPlugin\Source\VaRestPlugin\Private\VaRestPluginPrivatePCH.h)
UnrealBuildTool: g:\UE4.15\Engine\Plugins\VaRestPlugin\Source\VaRestPlugin\Private\VaRestRequestJSON.cpp (including g:\UE4.15\Engine\Plugins\VaRestPlugin\Source\VaRestPlugin\Classes\VaRestRequestJSON.h)
UnrealBuildTool:
CommandUtils.Run: Run: Took 15,5433202s to run UnrealBuildTool.exe, ExitCode=5

Any help?

**Comment by ufna** [comment]
@rotacak This version is not compatible with UE 4.15. I thinks its better to use version from https://github.com/ufna/VaRest/commit/7f141b8af185fc8115e38d01d506f4c555dd5a4f

**Comment by ufna** [comment]
Check is monolithic build is enabled

**Comment by rotacak** [comment]
@ufna Where it can be enabled?

**Comment by ufna** [comment]
@rotacak What's your command line to build the project?

**Comment by rotacak** [comment]
@ufna "g:\UE4.15\Engine\Build\BatchFiles\RunUAT.bat" BuildCookRun -project="g:\BUILDPACK\packdata\Game.uproject" -noP4 -serverconfig=Shipping -cook -server -noeditor -noclient -serverplatform=Win64 -compile -stage -archive -Build -allMaps -pak -CookDir="g:\BUILDPACK\packdata\Content\General" -archivedirectory="g:\BUILDPACK\Build"

Trying to build shipping dedicated server.

**Comment by ufna** [comment]
Try to add  -DisableUnity

**Comment by rotacak** [comment]
Then it will end with:

UnrealBuildTool: g:\UE4.15\Engine\Plugins\VaRestPlugin\Source\VaRestPlugin\Classes/VaRestJsonObject.h(27): error C2065: 'FJsonObject': undeclared identifier
UnrealBuildTool: g:\UE4.15\Engine\Plugins\VaRestPlugin\Source\VaRestPlugin\Classes/VaRestJsonObject.h(27): error C2923: 'TSharedPtr': 'FJsonObject' is not a valid template type argument for parameter 'ObjectType'
UnrealBuildTool: g:\UE4.15\Engine\Plugins\VaRestPlugin\Source\VaRestPlugin\Classes/VaRestJsonObject.h(30): error C2065: 'FJsonObject': undeclared identifier
UnrealBuildTool: g:\UE4.15\Engine\Plugins\VaRestPlugin\Source\VaRestPlugin\Classes/VaRestJsonObject.h(30): error C2923: 'TSharedPtr': 'FJsonObject' is not a valid template type argument for parameter 'ObjectType'
UnrealBuildTool: g:\UE4.15\Engine\Plugins\VaRestPlugin\Source\VaRestPlugin\Classes/VaRestJsonObject.h(174): error C2065: 'FJsonObject': undeclared identifier
UnrealBuildTool: g:\UE4.15\Engine\Plugins\VaRestPlugin\Source\VaRestPlugin\Classes/VaRestJsonObject.h(174): error C2923: 'TSharedPtr': 'FJsonObject' is not a valid template type argument for parameter 'ObjectType'
UnrealBuildTool: g:\UE4.15\Engine\Plugins\VaRestPlugin\Source\VaRestPlugin\Classes/VaRestJsonObject.h(176): error C4624: 'UVaRestJsonObject': destructor was implicitly defined as deleted
UnrealBuildTool: g:\UE4.15\Engine\Plugins\VaRestPlugin\Source\VaRestPlugin\Classes/VaRestJsonObject.h(176): error C2282: 'UVaRestJsonObject::~UVaRestJsonObject' cannot override 'UObject::~UObject'
UnrealBuildTool: g:\UE4.15\Engine\Source\Runtime\CoreUObject\Public\UObject/Object.h(1257): note: 'UObject::~UObject' is not deleted
UnrealBuildTool: g:\UE4.15\Engine\Plugins\VaRestPlugin\Source\VaRestPlugin\Classes/VaRestJsonObject.h(16): error C2275: 'UStrProperty': illegal use of this type as an expression
UnrealBuildTool: g:\UE4.15\Engine\Source\Runtime\CoreUObject\Public\UObject/UnrealType.h(2423): note: see declaration of 'UStrProperty'
UnrealBuildTool: g:\UE4.15\Engine\Plugins\VaRestPlugin\Source\VaRestPlugin\Classes/VaRestJsonObject.h(16): error C2065: 'Z_Param_FieldName': undeclared identifier
UnrealBuildTool: g:\UE4.15\Engine\Plugins\VaRestPlugin\Source\VaRestPlugin\Classes/VaRestJsonObject.h(16): error C3861: 'P_GET_PROPERTY': identifier not found
UnrealBuildTool: g:\UE4.15\Engine\Plugins\VaRestPlugin\Source\VaRestPlugin\Classes/VaRestJsonObject.h(16): error C2059: syntax error: ','

And many other errors.

If I will add 
#include "JsonObject.h"
to VaRestJsonObject.h then it will end with unknown FPendingLatentAction

and if I will add
#include "LatentActions.h"
to VaRestRequestJSON.h then it will end with:

UnrealBuildTool: VaRestPlugin.generated.cpp
UnrealBuildTool: g:\UE4.15\Engine\Plugins\VaRestPlugin\Source\VaRestPlugin\Classes/VaRestJsonObject.h(17): error C2275: 'UStrProperty': illegal use of this type as an expression
UnrealBuildTool: g:\UE4.15\Engine\Source\Runtime\CoreUObject\Public\UObject/UnrealType.h(2423): note: see declaration of 'UStrProperty'
UnrealBuildTool: g:\UE4.15\Engine\Plugins\VaRestPlugin\Source\VaRestPlugin\Classes/VaRestJsonObject.h(17): error C2065: 'Z_Param_FieldName': undeclared identifier
UnrealBuildTool: g:\UE4.15\Engine\Plugins\VaRestPlugin\Source\VaRestPlugin\Classes/VaRestJsonObject.h(17): error C3861: 'P_GET_PROPERTY': identifier not found
UnrealBuildTool: g:\UE4.15\Engine\Plugins\VaRestPlugin\Source\VaRestPlugin\Classes/VaRestJsonObject.h(17): error C2059: syntax error: ','
UnrealBuildTool: g:\UE4.15\Engine\Plugins\VaRestPlugin\Source\VaRestPlugin\Classes/VaRestJsonObject.h(17): error C2065: 'P_FINISH': undeclared identifier
UnrealBuildTool: g:\UE4.15\Engine\Plugins\VaRestPlugin\Source\VaRestPlugin\Classes/VaRestJsonObject.h(17): error C2065: 'P_NATIVE_BEGIN': undeclared identifier
UnrealBuildTool: g:\UE4.15\Engine\Plugins\VaRestPlugin\Source\VaRestPlugin\Classes/VaRestJsonObject.h(17): error C2065: 'Z_Param_Out_ObjectArray': undeclared identifier
UnrealBuildTool: g:\UE4.15\Engine\Plugins\VaRestPlugin\Source\VaRestPlugin\Classes/VaRestJsonObject.h(17): error C2065: 'P_NATIVE_END': undeclared identifier
UnrealBuildTool: g:\UE4.15\Engine\Plugins\VaRestPlugin\Source\VaRestPlugin\Classes/VaRestJsonObject.h(17): error C2062: type 'bool' unexpected
UnrealBuildTool: g:\UE4.15\Engine\Plugins\VaRestPlugin\Source\VaRestPlugin\Classes/VaRestJsonObject.h(17): error C2065: 'Z_Param_Out_BoolArray': undeclared identifier
UnrealBuildTool: g:\UE4.15\Engine\Plugins\VaRestPlugin\Source\VaRestPlugin\Classes/VaRestJsonObject.h(17): error C2275: 'FString': illegal use of this type as an expression
UnrealBuildTool: g:\ue4.15\engine\source\runtime\core\public\Windows/WindowsCriticalSection.h(9): note: see declaration of 'FString'
UnrealBuildTool: g:\UE4.15\Engine\Plugins\VaRestPlugin\Source\VaRestPlugin\Classes/VaRestJsonObject.h(17): error C2065: 'Z_Param_Out_StringArray': undeclared identifier
UnrealBuildTool: g:\UE4.15\Engine\Plugins\VaRestPlugin\Source\VaRestPlugin\Classes/VaRestJsonObject.h(17): error C3861: 'P_GET_TARRAY_REF': identifier not found
UnrealBuildTool: g:\UE4.15\Engine\Plugins\VaRestPlugin\Source\VaRestPlugin\Classes/VaRestJsonObject.h(17): error C2062: type 'float' unexpected

and so on...

:(

**Comment by ufna** [comment]
Hm, I see that you've added plugin to the Engine. It's not a good idea, please move it to your project first.

**Comment by rotacak** [comment]
@ufna But then it will end with: 
UnrealBuildTool: LogPluginManager:Error: This project requires the 'VaRestPlugin' plugin. Install it and try again, or remove it from the project's required plugin list.
UnrealBuildTool: LogCompile:Error: Failed to initialize the engine (PreInit failed).

If I will remove it also from Game.uproject and leave it only in prebuild Game.uproject then it will package almost everything but it will fail with all blueprints where is plugin used. That is reason why I added it also to Engine, because I packaging it from engine.

**Comment by rotacak** [comment]
Update: It works. I added plugin into wrong project (not used for build by cmd). When I removed it from engine and added only to project, it works ok. Thanks for help.
