### ISSUE TITLE
PUT with post

### ISSUE THREAD

**Issue by BZInhance** [ufna/VaRest#13]
Hello,

To test what's coming out of a HTTP request I used this website
http://www.posttestserver.com/

When I do POST requests, they get through but it seems that the plugin also sends PUT data
http://www.posttestserver.com/data/2015/01/05/17.19.31634839677

I'm not sure it's a bug but it's worth mentionning it.

**Comment by ufna** [comment]
I've checked the code, it seemed to be a "feature", not a bug.
