### ISSUE TITLE
UnrealBuildTool constructor args

### ISSUE THREAD

**Issue by CortSmith** [ufna/VaRest#130]
Here is the problem, I downloaded the git version of the plugin and put the entire plugin in the plugins folder of my ue4 project (version 4.15) and it is giving me this error regarding the UnrealBuildTool.ModuleRules does not contain a constructor that takes 1 arguements

Here is the actual error:

Running C:/Program Files/Epic Games/UE_4.15/Engine/Binaries/DotNET/UnrealBuildTool.exe  -projectfiles -project="D:/.../.../.../BasicCombatBuild1/*.uproject" -game -rocket -progress
Discovering modules, targets and source code for project...
Messages while compiling D:\...\...\...\BasicCombatBuild1\Intermediate\Build\BuildRules\*ModuleRules.dll:
d:\...\...\...\BasicCombatBuild1\Plugins\VaRest-develop\Source\VaRestEditorPlugin\VaRestEditorPlugin.Build.cs(7,58) : error CS1729: 'UnrealBuildTool.ModuleRules' does not contain a constructor that takes 1 arguments
d:\...\...\...\BasicCombatBuild1\Plugins\VaRest-develop\Source\VaRestPlugin\VaRestPlugin.Build.cs(9,53) : error CS1729: 'UnrealBuildTool.ModuleRules' does not contain a constructor that takes 1 arguments
UnrealBuildTool Exception: ERROR: UnrealBuildTool encountered an error while compiling source files

I felt the need to hide the project name since the project is not mine. Any (*) is the placeholder for the project name any (...) is a folder placeholder up to the project.

**Comment by ufna** [comment]
Hi @CortSmith ,

You shouldn't use the last version for old engine versions - it's compatible with UE 4.18 only now. 

Just check https://github.com/ufna/VaRest/commit/531e8791279b2064b909bd9cda27695f996ff67a

**Comment by CortSmith** [comment]
Where can I download an older version, preferrably compatible with ue4.15.3

**Comment by ufna** [comment]
@CortSmith Checkout the commit I've mention above ;)
