### ISSUE TITLE
Linux binaries are missing

### ISSUE THREAD

**Issue by gjdwebserver** [ufna/VaRest#134]
The package does not contain the Linux binaries (4.18.1).

**Comment by ufna** [comment]
You mean marketplace version? It's better to use Github one for Linux builds.

**Comment by gjdwebserver** [comment]
I do mean marketplace version but i cannot find the build version for r-19 on github aswell.

**Comment by ufna** [comment]
For github version you should build binaries by yourself. Just add the plugin as project one (don't put it into the engine folder)
