### ISSUE TITLE
Request always fails in ios

### ISSUE THREAD

**Issue by rahulsode** [ufna/VaRest#135]
Varest request always fails when the application is packaged in development build for IOS,
Even after updating the plist to allow http request, still neither http nor https is working.

**Comment by ufna** [comment]
Hi @rahulsode 

I need an example project to reproduce it. I'm using VaRest prersonally with few iOS projects, and all is ok.

**Comment by rahulsode** [comment]
Here is the basic sample code on a blank project.
1 -> first one is a normal call on Http, which works fine.
2 -> the second one is normal call on Https, the response status is failed always
This is when testing on MAC, however both the code works fine when tested in Windows

Earlier I thought it fails only after packaging for IOS because they dont allow to connect to insecure server but now when I am just running the project on MAC, It fails
I also added the required data in the .plist to allow insecure connection still nothing changed

![sample code](https://user-images.githubusercontent.com/12656232/34201862-e9c17be6-e59b-11e7-933d-d1567fc6c815.png)

**Comment by rahulsode** [comment]
If it is running properly on your side then may be  I am doing something wrong, please let me know how you did it..

**Comment by ufna** [comment]
CallURL currently has its issues, I should rewrite it. Please use ApplyURL instead.

Also, you can turn the Http module log level to VeryVerbose and then check the state of Http request itself.
