### ISSUE TITLE
Decode Json Always Fails in UE 4.18

### ISSUE THREAD

**Issue by L34D3R** [ufna/VaRest#137]
Unable to decode json, it always fails. It was working perfectly in UE 4.14. 
![screenshot2-1](https://user-images.githubusercontent.com/13694300/34600769-340185c2-f21f-11e7-9bd1-e8dd321ec04f.jpg)

**Comment by L34D3R** [comment]
Used get response content as string node, working fine.

**Comment by ufna** [comment]
Hi @L34D3R ,

Yep, response content string was optimized in 4.18 edition :)

**Comment by manuganu9** [comment]
I have the same issue. It's not working on my machine 1. But it's working on my machine 2. Is there any dependency of the OS or Hardware?

I have Windows 7 Ultimate SP1 in both the machines.
