### ISSUE TITLE
Get PHP echo as printable string.

### ISSUE THREAD

**Issue by Shakary** [ufna/VaRest#138]
Hey guys, I'm really stuck at this and I could use some help. Please read my question here: 
https://answers.unrealengine.com/questions/747071/varest-register-system-print-php-result.html

I can't get the echo "Account Created" from the php to my register widget, in order to print "Account Created" or "Username taken".

You can check my current working blueprint: https://blueprintue.com/blueprint/fpm5yhh0/

Any ideas?

**Comment by ufna** [comment]
Hi @Shakary ,

You should bind OnRequestComplete event, and then read the responce content.

![](http://ufna.ru/github/varest/varest_example_simpleget.jpg)

**Comment by Shakary** [comment]
Ive added those blueprints after my process url, and it prints "Depretated-Use GetResponseContent as string instead", and when i do it, it prints the last thing that was on the print string box (Hello)

**Comment by ufna** [comment]
@Shakary What means "after"? You should use GetResponseContent exatly in binded event, not after ProcessURL

**Comment by Shakary** [comment]
I've tried that also... It didn't work.
Is it because the response is generated INSIDE the php as echo "Account created" ?

**Comment by ufna** [comment]
When you tried it, what was the ResponseContentString? 

echo "Account created" will be invalid json response. Try to make it something like ```echo "{\"response\": \"account created\"} ```

**Comment by Shakary** [comment]
I did that and the PHP page stopped working

**Comment by Shakary** [comment]
should the page now show {\"response\":\"account created\"}  ? that's what shows on the Register.php page, but it still doesn't get the response to the unreal engine

**Comment by ufna** [comment]
Please show your blueprint now

**Comment by Shakary** [comment]
blueprint: https://blueprintue.com/blueprint/kq5-ctpw/
php response: {"response": "account created"}

**Comment by ufna** [comment]
You're double-constructing your request. You should remove the second one construction

**Comment by Shakary** [comment]
Can I leave the first as a POST? Because it's supposed to add the info to the database

**Comment by ufna** [comment]
Sure

**Comment by Shakary** [comment]
Not working.. this is my php: http://www.arethonline.com/Register.php
This is my blueprint: https://blueprintue.com/blueprint/07mi5-2l/

I don't get the response, I get "DEPRECATED: Please use GetResponseContent as string instead. (And that won't work either)

**Comment by ufna** [comment]
What's the GetResponseContent() function result?

**Comment by Shakary** [comment]
I delete GetResponseContent string and put GetResponseContent() function and it prints "Hello" which is what was in the "print string" box before i connected them

**Comment by Shakary** [comment]
Is the php response right? is the page supposed to show that?

**Comment by ufna** [comment]
![](https://i.gyazo.com/6a2c519f16f9e536c3072efd6c5ab3b1.png)

**Comment by Shakary** [comment]
WORKED! Thank you so much! THANK YOU!

**Comment by ufna** [comment]
You're welcome!
