### ISSUE TITLE
UE4 error when I changed server URL

### ISSUE THREAD

**Issue by OAXP** [ufna/VaRest#140]
I always got this error and I don't know what is wrong and the server status in UE4 is offline but it's online.
Thanks for help.

Here is my LOG :

`LogTemp: Repeting last play command: Selected Viewport
LogBlueprintUserMessages: Early PlayInEditor Detection: Level '/Game/MainMenu.MainMenu:PersistentLevel' has LevelScriptBlueprint '/Game/MainMenu.MainMenu:PersistentLevel.MainMenu' with GeneratedClass '/Game/MainMenu.MainMenu_C' with ClassGeneratedBy '/Game/MainMenu.MainMenu:PersistentLevel.MainMenu'
LogPlayLevel: PlayLevel: No blueprints needed recompiling
PIE: New page: PIE session: MainMenu (Jan 19, 2018, 1:04:04 PM)
LogPlayLevel: Creating play world package: /Game/UEDPIE_0_MainMenu
LogPlayLevel: PIE: StaticDuplicateObject took: (0.001123s)
LogAIModule: Creating AISystem for world MainMenu
LogPlayLevel: PIE: World Init took: (0.000872s)
LogPlayLevel: PIE: Created PIE world by copying editor world from /Game/MainMenu.MainMenu to /Game/UEDPIE_0_MainMenu.MainMenu (0.002287s)
LogInit: XAudio2 using 'Haut-parleurs (Realtek High Definition Audio)' : 2 channels at 48 kHz using 32 bits per sample (channel mask 0x3)
LogInit: FAudioDevice initialized.
LogLoad: Game class is 'GameMode'
LogWorld: Bringing World /Game/UEDPIE_0_MainMenu.MainMenu up for play (max tick rate 0) at 2018.01.19-18.04.04
LogWorld: Bringing up level for play took: 0.000752
LogGameMode:Display: Match State Changed from EnteringMap to WaitingToStart
LogGameState: Match State Changed from EnteringMap to WaitingToStart
LogGameMode:Display: Match State Changed from WaitingToStart to InProgress
LogVaRest: Request (urlencoded): GET http://oaxp.ezyro.com/api/config.json 
LogGameState: Match State Changed from WaitingToStart to InProgress
PIE: Info Play in editor start time for /Game/UEDPIE_0_MainMenu -0.893
LogBlueprintUserMessages: Late PlayInEditor Detection: Level '/Game/MainMenu.MainMenu:PersistentLevel' has LevelScriptBlueprint '/Game/MainMenu.MainMenu:PersistentLevel.MainMenu' with GeneratedClass '/Game/MainMenu.MainMenu_C' with ClassGeneratedBy '/Game/MainMenu.MainMenu:PersistentLevel.MainMenu'
LogVaRest: Response (200): 
JSON(
<html><body><script type="text/javascript" src="/aes.js" ></script><script>function toNumbers(d){var e=[];d.replace(/(..)/g,function(d){e.push(parseInt(d,16))});return e}function toHex(){for(var d=[],d=1==arguments.length&&arguments[0].constructor==Array?arguments[0]:arguments,e="",f=0;f<d.length;f++)e+=(16>d[f]?"0":"")+d[f].toString(16);return e.toLowerCase
()}var a=toNumbers("f655ba9d09a112d4968c63579db590b4"),b=toNumbers("98344c2eee86c3994890592585b49f80"),c=toNumbers("cd42034f704a7ad74112af2e5a99305c");document.cookie="__test="+toHex(slowAES.decrypt(c,2,a,b))+"; expires=Thu, 31-Dec-37 23:55:55 GMT; path=/"; location.href="http://oaxp.ezyro.com/api/config.json?i=1";</script><noscript>This site requires Javasc
ript to work, please enable Javascript in your browser or use a browser with Javascript support</noscript></body></html>
)JSON
LogScript:Warning: Accessed None trying to read property CallFunc_GetField_ReturnValue4
    Login_C /Engine/Transient.UnrealEdEngine_0:Instance_C_7.Login_C_11
    Function /Game/LoginSystem/Widgets/Login.Login_C:ExecuteUbergraph_Login:01C7
PIE:Error: Error Blueprint Runtime Error: Accessed None trying to read property CallFunc_GetField_ReturnValue4 from function: 'ExecuteUbergraph_Login' from node: Branch in graph: EventGraph in object: Login with description: Accessed None trying to read property CallFunc_GetField_ReturnValue4
LogScript:Warning: Accessed None trying to read property CallFunc_GetField_ReturnValue4
    Login_C /Engine/Transient.UnrealEdEngine_0:Instance_C_7.Login_C_11
    Function /Game/LoginSystem/Widgets/Login.Login_C:ExecuteUbergraph_Login:0383
PIE:Error: Error Blueprint Runtime Error: Accessed None trying to read property CallFunc_GetField_ReturnValue4 from function: 'ExecuteUbergraph_Login' from node: Branch in graph: EventGraph in object: Login with description: Accessed None trying to read property CallFunc_GetField_ReturnValue4
LogBlueprintUserMessages: Early EndPlayMap Detection: Level '/Game/MainMenu.MainMenu:PersistentLevel' has LevelScriptBlueprint '/Game/MainMenu.MainMenu:PersistentLevel.MainMenu' with GeneratedClass '/Game/MainMenu.MainMenu_C' with ClassGeneratedBy '/Game/MainMenu.MainMenu:PersistentLevel.MainMenu'
LogOnline:Display: OSS: FOnlineSubsystemNull::Shutdown()
LogOnline:Display: OSS: FOnlineAsyncTaskManager::Stop() ActiveTask:0000000000000000 Tasks[0/0]
LogOnline:Display: OSS: FOnlineAsyncTaskManager::Exit() started
LogOnline:Display: OSS: FOnlineAsyncTaskManager::Exit() finished
LogPlayLevel:Display: Shutting down PIE online subsystems
LogBlueprintUserMessages: Late EndPlayMap Detection: Level '/Game/MainMenu.MainMenu:PersistentLevel' has LevelScriptBlueprint '/Game/MainMenu.MainMenu:PersistentLevel.MainMenu' with GeneratedClass '/Game/MainMenu.MainMenu_C' with ClassGeneratedBy '/Game/MainMenu.MainMenu:PersistentLevel.MainMenu'
LogPlayLevel:Display: Destroying online subsystem :Context_16
LogOnline:Display: OSS: FOnlineSubsystemNull::Shutdown()`

**Comment by ufna** [comment]
As I see in LogVaRest: Response (200) log, your server requires javascript enabled. It's not the way you can use REST.
