### ISSUE TITLE
Plugin does not work in packaged project when using it in GameInstance init method

### ISSUE THREAD

**Issue by timothyBrake** [ufna/VaRest#143]
Everything works fine in the Editor and I can create a blueprint class that gets JSON form a REST api. But when I package the project and play the game, nothing happens.

Am I missing some step in the process here?  I am using the Marketplace version and clicked on the "install to engine 4.18". The plugin is version 1.1-r19. It is a blueprint only project.

Any help is more than welcome as I want to release the game asap to be included in a contest.

I noticed that it does not get executed in the init method of a custom game instance class. I moved the call to the event to a regular blueprint and all worked fine.

**Comment by ufna** [comment]
Hi @timothyBrake ,

I know about this "feature" of the engine, nothing about plugin itself :( So, just use it outside the Init() function and all will be okay.
