### ISSUE TITLE
wiki example of POST Request please

### ISSUE THREAD

**Issue by DoctorMikeReddy** [ufna/VaRest#144]
It would be very helpful to have an example of how to construct a POST request, especially how to construct the request to send something like a username and password. In 'code' I could construct the required information to be passed using:
Request->SetHeader(TEXT("username"), "usernameString");
Request->SetHeader(TEXT("password"), "passwordString");
BUT I cannot work out how to do that in Blueprints using VaRest. 

Any help would be greatly appreciated

**Comment by DoctorMikeReddy** [comment]
With some help from reddit,I now know how to create a Request Bodystyle request. Will post an example here

**Comment by DoctorMikeReddy** [comment]
Here it is:

<img width="1644" alt="screen shot 2018-02-09 at 23 15 24" src="https://user-images.githubusercontent.com/1001087/36054604-44fb908e-0def-11e8-9aa8-34f4a76db6ce.png">

A login widget sets username and password, and here above is how to create a Request Body POST for interacting with a PHP/SQL server that does not parse JSON, and does not use GET for security reasons. I hope this is helpful, as it took me quite some time to work it out!

**Comment by chase03** [comment]
You need move bind event Complete after the set string, then Apply URL
