### ISSUE TITLE
Unreal 4.19 support

### ISSUE THREAD

**Issue by Anuj2907** [ufna/VaRest#145]
Need help integrating with 4.19 engine. Any pointers as to how to do this?

**Comment by woohoou** [comment]
Any news on this?

**Comment by ufna** [comment]
@woohoou unfortunately, not yet. I should check it next week.

**Comment by MADSOFTWARE** [comment]
Greetings! UE 4.19 is released now and I was wondering if there are any news for the 4.19 version of VaRest ^.^

**Comment by hiteshsathawane** [comment]
VaRest Plugin not working in 4.19.2

**Comment by ufna** [comment]
Hi @hiteshsathawane ,

What exactly means "not working"? Are you using repsonse content as string?

**Comment by hiteshsathawane** [comment]
![4 19 2](https://user-images.githubusercontent.com/8456138/40979901-c13ac236-68f4-11e8-807a-498df8801f3e.PNG)

**Comment by ufna** [comment]
@hiteshsathawane Please update plugin from Github or marketplace.

**Comment by awicks44** [comment]
I've using the VARest plugin as well...Whenever I do a packaged build, I receive "invalid response". It works when I'm testing on the PC, but never on my Iphone. Any assistance would be greatly appreciated.
