### ISSUE TITLE
Get Number Field and Get String Field not working as expected

### ISSUE THREAD

**Issue by DoctorMikeReddy** [ufna/VaRest#146]
Using the following JSON response from a server:
`{ "status": true, "session_id": "266a56808124ffe7d5bf9a0bb288f936", "player": { "player_id": "1", "logging": "1", "hair": "0", "hair_colour": "0", "skin": "0", "top": "0", "trousers": "0", "socks": "0" }, "scenario": [ { "number": "1", "unlocked": "1", "score": "10", "bar": "0", "bonus": "1" }, { "number": "2", "unlocked": "1", "score": "5", "bar": "0", "bonus": "0" } ] }`

I have had issues using Get String Field for "status", and have had to use Get Field -> As String  in order to get the value out correctly:

<img width="306" alt="screen shot 2018-02-09 at 22 46 21" src="https://user-images.githubusercontent.com/1001087/36054186-e6ca9f5c-0dec-11e8-8b85-f46a279558c6.png">

and have had to use Get Field -> As Number instead of Get Number Field when getting "player_id" from inside the "player" Object Field:
 
<img width="1342" alt="screen shot 2018-02-09 at 22 04 42" src="https://user-images.githubusercontent.com/1001087/36054336-b4a20dfc-0ded-11e8-92ab-a2e0cbb7ee69.png">

The above works, but the code below just return zero, whatever the correct value:

<img width="1419" alt="screen shot 2018-02-09 at 21 55 46" src="https://user-images.githubusercontent.com/1001087/36054364-dc184edc-0ded-11e8-899e-3d3c016f4e81.png">

Am I missing something? Shouldn't Get Number Field work the same as Get Field-> As Number and so on?

**Comment by ufna** [comment]
Hi @DoctorMikeReddy ,

The field "player_id" is not a Number field, because in JSON notation it's a string: `"player_id": "1"`

The **number** field will look as: `"player_id": 1` , no quotes!

**Comment by DoctorMikeReddy** [comment]
Thanks. I did notice this, and flagged to the server coder, who was creating the JSON, thinking this might be related. He was non-plussed that his code was adding quotes, as these items were numbers in SQL. Right now, we have everything working with items as strings. His perspective, if it ain’t broke…
:-(

**Comment by DoctorMikeReddy** [comment]
Presumably, status could be retrieved as a boolean and used directly.

**Comment by ufna** [comment]
You’re welcome ;)
