### ISSUE TITLE
The plugin has stopped working overnight

### ISSUE THREAD

**Issue by DO-Matt** [ufna/VaRest#148]
Something strange has happened.
Only yesterday everything worked well (and for many earlier days).
However, today all my projects using VaRest are full of errors and impossible to compile.
![varest](https://user-images.githubusercontent.com/36444739/36150748-f8aca2a8-10c4-11e8-8f59-3a9b50a19d5a.jpg)

There were no changes or updates in the projects or engine.
The only thing that has changed is the date.

If I delete all blueprint nodes. and I will remake them manually from scratch, the plugin works correctly in the editor, and during the compilation the same errors appear.

Interestingly. after closing the editor and restarting it. The new blueprint (working just second ago) shows these errors again.

I have absolutely no idea what to do about it.
EDIT- Im using Engine 4.18

**Comment by ufna** [comment]
Please try to launch the Validate operation on the engine. Also I recommend you to reinstall the plugin. It’s a really strange issue Oo

**Comment by DO-Matt** [comment]
I did it 15 times yesterday.
I even uninstalled the whole engine, I created a new project etc

The error keeps coming back

**Comment by DO-Matt** [comment]
And here a link to topic at UE forum which i create about that issue:
https://forums.unrealengine.com/development-discussion/blueprint-visual-scripting/1428350-i-found-
weird-bug-in-blueprints-call-unknown-function

**Comment by DO-Matt** [comment]
Update. its engine bug. all newly installed plugins have the same error :/
I totally dont know what to do..

**Comment by DO-Matt** [comment]
Update again. This problem does not apply to all plugins but only VaRest and that https://www.unrealengine.com/marketplace/low-entry-extended-standard-library

So something comment with LE plugin and VaRest may cause that error

**Comment by DO-Matt** [comment]
Update.

Asset action > reload called on broken blueprint, fix all errors in editor untill restart of the editor.

But the editor version of game works correctly till i try to packange it or i restart editor. Any idea what is happening? 

And this is a video how an error looks https://www.youtube.com/watch?v=GqcHF9hJw0k&feature=youtu.be

**Comment by ufna** [comment]
Hi @DO-Matt 

Are you solved the issue? It seemed to be very local one.
