### ISSUE TITLE
Https on Android instruction

### ISSUE THREAD

**Issue by ufna** [ufna/VaRest#15]
It should be set on Android to make https work:
```
FCurlHttpManager::CurlRequestOptions.bVerifyPeer = false;
```

**Comment by tuxbook** [comment]
This can be done in project settings: https://forums.unrealengine.com/showthread.php?56169-HTTPS-requests-not-working-on-Android

Worked for me :)

**Comment by ufna** [comment]
Thanks, @tuxbook , I'll check it and add to the documentation then :)
