### ISSUE TITLE
GET Call works on computer, doesn't work in iOS

### ISSUE THREAD

**Issue by azinonos** [ufna/VaRest#150]
Hello,

I am using the VaRest plugin in the way shown in the attached image. On my laptop in both Mac OS and Windows it works fine and I get the response, however when I launch the project on my iPhone it does not. I've trying to debug it using print statements and I can see that it stops working right after the 'Bind Event to OnRequestComplete' Node. Any help would be appreciated!
![screen shot 2018-02-16 at 12 04 34](https://user-images.githubusercontent.com/17152554/36306980-f053694e-1311-11e8-9d5d-25a8bc4dba78.png)

**Comment by ufna** [comment]
Hi @azinonos 

Please check https://github.com/ufna/VaRest/wiki#non-trusted-connections-http-on-ios first.

**Comment by azinonos** [comment]
Sorry for the late response but trying both pieces of code, the build fails with messages

`LogPlayLevel:   Code Signing Error: Bundle identifier is missing. [project_name] doesn't have a bundle identifier for the Development build configuration. Add a value for PRODUCT_BUNDLE_IDENTIFIER in the build settings editor.
LogPlayLevel:   Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'`

This doesn't happen without those lines of code. I am trying to use VaRest with ARKit by Apple so I also have this line in my additional plist data:
`<key>NSCameraUsageDescription</key> <string>This application will use the camera for AR</string>\n`

Any tips or help would be appreciated

**Comment by ufna** [comment]
@azinonos , are you sure that you're using valid mobile provision for this build?

**Comment by ufna** [comment]
Closing this one because of #153
