### ISSUE TITLE
does not work GET RESPONCE

### ISSUE THREAD

**Issue by DeadStunt2121** [ufna/VaRest#151]
Hello,
![1234](https://user-images.githubusercontent.com/22589851/36341919-bfc403ba-1406-11e8-98f6-f44f4a2047ff.jpg)

does not work GET RESPONCE.
Is there any other method that can be used?
version 4.18

**Comment by ufna** [comment]
Hi @DeadStunt2121 

Please use GetResponseContentAsString() instead.
