### ISSUE TITLE
Adding non trusted connection to iOS additional plist data breaks build

### ISSUE THREAD

**Issue by azinonos** [ufna/VaRest#153]
This is a continuation of my previous post which was closed before I had time to reply:
https://github.com/ufna/VaRest/issues/150

LogPlayLevel: Code Signing Error: Bundle identifier is missing. [project_name] doesn't have a bundle identifier for the Development build configuration. Add a value for PRODUCT_BUNDLE_IDENTIFIER in the build settings editor. LogPlayLevel: Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'

This doesn't happen without those lines of code. I am trying to use VaRest with ARKit by Apple so I also have this line in my additional plist data:
<key>NSCameraUsageDescription</key> <string>This application will use the camera for AR</string>\n

Any tips or help would be appreciated

**Comment by ufna** [comment]
@azinonos  , are you sure that you're using valid mobile provision for this build?

**Comment by azinonos** [comment]
Yes I am quite sure. Basically when I have this in the additional plist data, the build works fine:
`<key>NSCameraUsageDescription</key> <string>This application will use the camera for AR</string>\n`

However when I add the extra line below for the HTTP request, the build breaks:
`<key>NSCameraUsageDescription</key> <string>This application will use the camera for AR</string>\n<key>NSAppTransportSecurity</key><dict><key>NSExceptionDomains</key><dict><key>http://MY_TARGET_URL.com</key><dict><key>NSExceptionAllowsInsecureHTTPLoads</key><true/><key>NSIncludesSubdomains</key><true/></dict></dict></dict>\n`

And the error I receive is the following (the part with the error):
_LogPlayLevel:   Check dependencies
LogPlayLevel:   Code Signing Error: Bundle identifier is missing. [PROJECT] doesn't have a bundle identifier for the Development build configuration. Add a value for PRODUCT_BUNDLE_IDENTIFIER in the build settings editor.
LogPlayLevel:   Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'
LogPlayLevel:   ** BUILD FAILED **
LogPlayLevel:   The following build commands failed:
LogPlayLevel:     Check dependencies
LogPlayLevel:   (1 failure)
LogPlayLevel: Took 23.574548s to run env, ExitCode=65
LogPlayLevel: ERROR: CodeSign Failed
LogPlayLevel:        (see /Users/[user]/Library/Logs/Unreal Engine/LocalBuildLogs/UAT_Log.txt for full exception trace)
LogPlayLevel: AutomationTool exiting with ExitCode=32 (Error_FailedToCodeSign)
LogPlayLevel: Completed Launch On Stage: Deploy Task, Time: 76.636909
LogPlayLevel: RunUAT ERROR: AutomationTool was unable to run successfully.
PackagingResults: Error: Launch failed! Failed to Code Sign_

I have tried changing the bundle identifier to another value but it didn't work, I don't know if I have to use something specific from the certificates? Thanks.

**Comment by ufna** [comment]
Are you using Remote build?

**Comment by azinonos** [comment]
I am building locally from a MacBook pro. I've tried removing the \n and now the AdditionalPlistData is as follows:
`<key>NSCameraUsageDescription</key> <string>This application will use the camera for AR</string><key>NSAppTransportSecurity</key><dict><key>NSExceptionDomains</key><dict><key>http://MY_TARGET_URL.com</key><dict><key>NSExceptionAllowsInsecureHTTPLoads</key><true/><key>NSIncludesSubdomains</key><true/></dict></dict></dict>`

The build works with no errors now but the request still silently fails and I get nothing. I a not sure if the second line is not recognized without the \n, is there a different way to add multiple values?

**Comment by azinonos** [comment]
I see, thanks for that piece of information. Could you explain how I would set the HttpModule log to verbose? Also keep the application is running on an iPhone so the actions on the phone do not appear in the output log on the computer.

**Comment by ufna** [comment]
It's great to have a look on https://wiki.unrealengine.com/Logs,_Printing_Messages_To_Yourself_During_Runtime

JFYI:
[Core.Log]
LogHttp=VeryVerbose

You can grab runtime log from device with XCode device manager.

**Comment by azinonos** [comment]
Thanks, I'll try it out tonight and get back to you!

**Comment by ufna** [comment]
It's definitely a plist misconfiguration problem. Http is not allowed by it.

**Comment by azinonos** [comment]
Isn't that line of code you linked me to supposed to fix the problem though? Is there some alternative I can try?

**Comment by ufna** [comment]
It's all about NSAppTransportSecurity in plist. Or you can use https instead :)

**Comment by azinonos** [comment]
Sorry but I'm a bit confused. I am adding the NSAppTransportSecurity in plist, so that should have eliminated the issue right? Could there be a reason it doesn't work right now? Regarding HTTPS unfortunately right now I'm building my application with a dummy endpoint so I am not in control of the website, and it would make things more complicated. Please let me know if there is a better way to give you better information. Thanks for the help so far!

**Comment by ufna** [comment]
Could you show your DefaultEngine.ini please?

**Comment by azinonos** [comment]
Posting it here. As before I've changed the project name to [PROJECT_NAME] for privacy reasons.

DefaultEngine.ini
```
[URL]
GameName=[PROJECT_NAME]

[URL]
[/Script/Slate.SlateSettings]
bVirtualKeyboardSendsTextChanged=False
bVirtualKeyboardDisplayOnFocus=True
bExplicitCanvasChildZOrder=True

[/Script/IOSRuntimeSettings.IOSRuntimeSettings]
MinimumiOSVersion=IOS_11
MaxShaderLanguageVersion=2
bSupportsMetal=True
bSupportsMetalMRT=False
bCookASTCTextures=False
bCookPVRTCTextures=True
bShipForArmV7=False
bGeneratedSYMBundle=True
AdditionalPlistData="<key>NSCameraUsageDescription</key> <string>This application will use the camera for AR</string><key>NSAppTransportSecurity</key><dict><key>NSExceptionDomains</key><dict><key>[TARGET_URL]</key><dict><key>NSExceptionAllowsInsecureHTTPLoads</key><true/><key>NSIncludesSubdomains</key><true/></dict></dict></dict>"
bSupportsOpenGLES2=False
bSupportsLandscapeLeftOrientation=False
FrameRateLock=PUFRL_60
MobileProvision=[PROJECT_NAME]_Profile.mobileprovision
SigningCertificate=iPhone Developer: Andreas Zinonos (PUC783HR3N)
BundleDisplayName=[PROJECT_NAME]
BundleName=[PROJECT_NAME]
BundleIdentifier=com.YourCompany.[PROJECT_NAME]

[/Script/UnrealEd.CookerSettings]
DefaultASTCQualityBySize=2

[/Script/Engine.RendererSettings]
r.MobileHDR=True
r.Mobile.DisableVertexFog=False
r.Shadow.CSM.MaxMobileCascades=2
r.MobileMSAA=1
r.DiscardUnusedQuality=False
r.AllowOcclusionQueries=True
r.MinScreenRadiusForLights=0.030000
r.MinScreenRadiusForDepthPrepass=0.030000
r.MinScreenRadiusForCSMDepth=0.010000
r.PrecomputedVisibilityWarning=False
r.TextureStreaming=True
Compat.UseDXT5NormalMaps=False
r.ClearCoatNormal=False
r.ReflectionCaptureResolution=128
r.ReflectionEnvironmentLightmapMixBasedOnRoughness=True
r.ForwardShading=True
r.VertexFoggingForOpaque=True
r.AllowStaticLighting=True
r.NormalMapsForStaticLighting=False
r.GenerateMeshDistanceFields=False
r.DistanceFieldBuild.EightBit=False
r.GenerateLandscapeGIData=True
r.DistanceFieldBuild.Compress=False
r.TessellationAdaptivePixelsPerTriangle=48.000000
r.SeparateTranslucency=False
r.TranslucentSortPolicy=0
TranslucentSortAxis=(X=0.000000,Y=-1.000000,Z=0.000000)
r.CustomDepth=1
r.CustomDepthTemporalAAJitter=True
r.DefaultFeature.Bloom=True
r.DefaultFeature.AmbientOcclusion=False
r.DefaultFeature.AmbientOcclusionStaticFraction=True
r.DefaultFeature.AutoExposure=False
r.DefaultFeature.AutoExposure.Method=0
r.DefaultFeature.MotionBlur=False
r.DefaultFeature.LensFlare=False
r.DefaultFeature.AntiAliasing=1
r.StencilForLODDither=False
r.EarlyZPass=3
r.EarlyZPassMovable=True
r.EarlyZPassOnlyMaterialMasking=False
r.DBuffer=False
r.ClearSceneMethod=1
r.BasePassOutputsVelocity=False
r.SelectiveBasePassOutputs=False
bDefaultParticleCutouts=False
r.AllowGlobalClipPlane=False
r.GBufferFormat=1
r.MorphTarget.Mode=False
vr.InstancedStereo=False
vr.MultiView=False
vr.MobileMultiView=False
vr.MobileMultiView.Direct=False
vr.MonoscopicFarField=False
r.WireframeCullThreshold=5.000000
r.SupportStationarySkylight=True
r.SupportLowQualityLightmaps=True
r.SupportPointLightWholeSceneShadows=True
r.SupportAtmosphericFog=True
r.SkinCache.CompileShaders=False
r.Mobile.EnableStaticAndCSMShadowReceivers=True
r.Mobile.AllowDistanceFieldShadows=True
r.Mobile.AllowMovableDirectionalLights=True
r.MobileNumDynamicPointLights=4
r.MobileDynamicPointLightsUseStaticBranch=True
r.SkinCache.SceneMemoryLimitInMB=128.000000

[/Script/HardwareTargeting.HardwareTargetingSettings]
TargetedHardwareClass=Mobile
AppliedTargetedHardwareClass=Mobile
DefaultGraphicsPerformance=Maximum
AppliedDefaultGraphicsPerformance=Maximum

[/Script/Engine.Engine]
NearClipPlane=20.000000

[/Script/EngineSettings.GameMapsSettings]
EditorStartupMap=/Game/Maps/ARSample.ARSample
LocalMapOptions=
TransitionMap=None
bUseSplitscreen=False
TwoPlayerSplitscreenLayout=Horizontal
ThreePlayerSplitscreenLayout=FavorTop
bOffsetPlayerGamepadIds=False
GameInstanceClass=/Script/Engine.GameInstance
GameDefaultMap=/Game/Maps/ARSample.ARSample
ServerDefaultMap=/Engine/Maps/Entry.Entry
GlobalDefaultGameMode=/Game/Blueprints/[PROJECT]GameMode.[PROJECT]GameMode_C
GlobalDefaultServerGameMode=None

[/Script/AndroidRuntimeSettings.AndroidRuntimeSettings]
bEnableGradle=False
bPackageDataInsideApk=True

[Core.Log]
LogHttp=VeryVerbose

[/Script/Engine.PhysicsSettings]
DefaultGravityZ=-980.000000
DefaultTerminalVelocity=4000.000000
DefaultFluidFriction=0.300000
SimulateScratchMemorySize=262144
RagdollAggregateThreshold=4
TriangleMeshTriangleMinAreaThreshold=5.000000
bEnableAsyncScene=False
bEnableShapeSharing=False
bEnablePCM=True
bEnableStabilization=False
bWarnMissingLocks=True
bEnable2DPhysics=False
LockedAxis=Invalid
DefaultDegreesOfFreedom=Full3D
BounceThresholdVelocity=200.000000
FrictionCombineMode=Average
RestitutionCombineMode=Average
MaxAngularVelocity=3600.000000
MaxDepenetrationVelocity=0.000000
ContactOffsetMultiplier=0.010000
MinContactOffset=0.000100
MaxContactOffset=1.000000
bSimulateSkeletalMeshOnDedicatedServer=True
DefaultShapeComplexity=CTF_UseSimpleAndComplex
bDefaultHasComplexCollision=True
bSuppressFaceRemapTable=False
bSupportUVFromHitResults=False
bDisableActiveActors=False
bDisableCCD=False
bEnableEnhancedDeterminism=False
MaxPhysicsDeltaTime=0.033333
bSubstepping=False
bSubsteppingAsync=False
MaxSubstepDeltaTime=0.016667
MaxSubsteps=6
SyncSceneSmoothingFactor=0.000000
AsyncSceneSmoothingFactor=0.990000
InitialAverageFrameRate=0.016667
PhysXTreeRebuildRate=10
```

**Comment by ufna** [comment]
Please remove " from AdditionalPlistData

**Comment by azinonos** [comment]
I've removed it making the line:
`AdditionalPlistData=<key>NSCameraUsageDescription</key> <string>This application will use the camera for AR</string><key>NSAppTransportSecurity</key><dict><key>NSExceptionDomains</key><dict><key>[TARGET_URL]</key><dict><key>NSExceptionAllowsInsecureHTTPLoads</key><true/><key>NSIncludesSubdomains</key><true/></dict></dict></dict>`

Unfortunately I still get the same error.

**Comment by ufna** [comment]
You have app com.YourCompany.smth in mobile provision? Not com.myrealcompany.smth?

[TARGET_URL] is a domain?

Personally I'm using:
AdditionalPlistData=<key>NSAppTransportSecurity</key><dict><key>NSAllowsArbitraryLoads</key><true/><key>NSExceptionDomains</key><dict><key>localhost</key><dict><key>NSIncludesSubdomains</key><true/></dict></dict></dict>

And it works okay with http

**Comment by azinonos** [comment]
Ok so your code did the trick, thanks! Not sure why the 'official' one doesn't work, but I'm guessing it has to do with the NSAllowsArbitraryLoads key. Maybe tell them to update the code to what you are using. Thanks again!

Also when removing the quotes from plist the code was trimmed in Unreal Editor and only half of it was left there, so I had to put them back. It works with the quotes fine.

**Comment by davidtreeUH** [comment]
just found that in version 4.19 you no longer need the plist amendment as they have added a checkbox in the iOS platform pain "Allow web connections to non-HTTPS websites"

**Comment by azinonos** [comment]
Thanks for the info @davidtreeUH. I'll need to stick wth 4.18 for now since there are no samples or documentation for ARKit in the new version as far as I know.
