### ISSUE TITLE
[noob_question] Which bp node sets body of request?

### ISSUE THREAD

**Issue by Sardorian** [ufna/VaRest#156]
![image](https://user-images.githubusercontent.com/9645781/37538014-7037e7d4-2960-11e8-9dcd-23eb16f1f22e.png)
i need to do this request in bp nodes, can someone point me out please? How should i add this body parameter to request variable?

**Comment by ufna** [comment]
Hi @Sardorian 

Just use Set Field function for Request json object with grant_type field name and with "password" value, etc.

**Comment by Sardorian** [comment]
Which content type should i use? urlencoded(request body) or urlencoded(url)?

**Comment by ufna** [comment]
Try body first

**Comment by Sardorian** [comment]
Also another question, can it be that server is not accepting POST, i am not getting any respond, GET works fine?

**Comment by Sardorian** [comment]
I checked just now, server sends codes and works as intended when i do requests from https://resttesttest.com/ . 
And also POST works too in UE4, i could change variable in the server, also get status prints succeded, BUT i am not getting response code =( is there any way to force debug or smth?
![default](https://user-images.githubusercontent.com/9645781/37543383-705962f8-2972-11e8-964f-e52b358bc4a9.PNG)
![image](https://user-images.githubusercontent.com/9645781/37543386-715d4fd4-2972-11e8-988b-f12fb4b70abf.png)

**Comment by ufna** [comment]
You re using GetStatus(), it’s the reason. Status is obviously not a response code.
