### ISSUE TITLE
[HTML5] Doesn't work after packaging or if "launch"

### ISSUE THREAD

**Issue by cfilo88** [ufna/VaRest#158]
Hi, I'm having a problem with VaRest in a HTML5 project.
If i click "play" from ue4 editor, VaRest works fine, but if I click "launch" from the editor or if I start the game after packaging (local and webhost) VaRest doesn't works. I'm using Unreal 4.18.3 with VaRest 1.1-r20. Thanks.

**Comment by thewenneur** [comment]
Hello, I have the same issue with all existing versions of unreal engine. I think it's a bug, because of the compilation erro sayin that "simbol multiply defined " if my memory is ok.... 
PS: Sorry for the bad English, I'm French :)

**Comment by SquarerFive** [comment]
Yeah, my one seems to fail when it tries to produce the javascript item on packaging and launch.

**Comment by Niuva** [comment]
I am experiencing this as well.

**Comment by michaelWuensch** [comment]
I was not able to package the game using HTML5 and VaRest. But I finally got it working.
For some reason it works only if you build the engine from source. If you try to package it using the binary version of UE it always throws an error.
