### ISSUE TITLE
Build Failed On 4.19 - Cannot open include file: 'ISettingsModule.h'

### ISSUE THREAD

**Issue by metahusk** [ufna/VaRest#159]
Building on UE4.19 (Epic Games Launcher Version) fails with the following error:
"fatal error C1083: Cannot open include file: 'ISettingsModule.h': No such file or directory"

I fixed the problem using a full directory path. 

On line 13 of VaRest\Source\VaRestPlugin\Private\VaRestPlugin.cpp
I  changed
#include "ISettingsModule.h"
To
#include "Developer/Settings/Public/ISettingsModule.h"

I haven't tried the source version of the engine yet. (Edit: To clarify, I used the source of the plugin from github. I'm not sure if there are other versions you've released?)

I'm not sure why I'm having issues. I'm still on VS2015, maybe that's part of the reason. Thanks for your awesome work on this plugin!

**Comment by jade-playerium** [comment]
I use VS2017 and have the same issue. 

Thanks for the way to fix.

**Comment by ufna** [comment]
Thanks, I'll take a look next week.

**Comment by ufna** [comment]
Fixed by https://github.com/ufna/VaRest/commit/081afbd7660ab94251f8b859313cedb6cc2d2fe2
