### ISSUE TITLE
Javascript not enabled

### ISSUE THREAD

**Issue by GewoonJaap** [ufna/VaRest#162]
When trying to do a json request, i get the error that JavaScript is not enabled in my browser (UE4)

**Comment by ufna** [comment]
Hi @GewoonJaap ,

Yes, and that's completely right. JS is a client tech, which is not supposed to work with http requests. Restful server shouldn't require it.

**Comment by GewoonJaap** [comment]
Hello,

Now i cant do a request... (php)
Is there a way to fix?
