### ISSUE TITLE
Chinese character issue

### ISSUE THREAD

**Issue by KaivnD** [ufna/VaRest#163]
My project mean to use Chinese character as username, but somehow VaRest dosen't work fine.So I came here to get some help, please help me!

**Comment by ufna** [comment]
Hi @Calvin-Dun ,

Could you provide an example please?

**Comment by Calvin-Dun** [comment]
Hi ufna! It's very nice of you to solve my problem , here is the thing , I'm Chinese guy , my client use Chinese character as their username. So, in part of my project I have to verify their account by Chinese character.

1. First image is a part of my GameInstance ,I use Apply url to request a JSON data and store them.

<img width="837" alt="wx20180509-000809 2x" src="https://user-images.githubusercontent.com/37983330/39768958-5332a232-531d-11e8-98bf-eae12b44ca43.png">

2.Second image is a part of my Login widget blueprint , this is going to get user input and verify account.
<img width="1419" alt="wx20180509-003852 2x" src="https://user-images.githubusercontent.com/37983330/39770403-82c800f6-5321-11e8-95ef-e8f507ea1af0.png">

My problem : these blueprint program work fine with English character but Chinese character.
My thought : maybe string variable does not support Chinese character ,but apply url only surport string :) Thanks for help!
