### ISSUE TITLE
Missing Category

### ISSUE THREAD

**Issue by Doublezer0** [ufna/VaRest#165]
I get this error whilst trying to compile the current develop build for 4.19.1.
"/VaRest/Source/VaRestPlugin/Classes/VaRestSettings.h(15) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module."

The code is : 
![image](https://user-images.githubusercontent.com/7355892/39666180-6ae1de30-5097-11e8-9065-99b035e3ebf3.png)

**Comment by ufna** [comment]
Thanks @Doublezer0 , should be fixed now
