### ISSUE TITLE
Can't get response, when returned JSON is top-level array of objects

### ISSUE THREAD

**Issue by Wadimich** [ufna/VaRest#166]
Hello! As title says, i can't get response. I'm using UE 4.19.2 and latest Varest release. When i'm getting response it drops me error

> LogVaRest: Error: UVaRestJsonObject::SetRootObject(45): Trying to set invalid json object as root one. Reset now.

Any workarounds?

**Comment by saidmoya12** [comment]
Same issue #161, still without solution

**Comment by Wadimich** [comment]
I've modified source code and added wrapper. Now it looks like this:

```
{
  "data": <server response>
}
```

**Comment by saidmoya12** [comment]
Yes work but only if you can work with server.

Third party API have your own standard and working with web sites, mobile etc.

The fix before 4.19 upgrade was
1. Get json as string
1. append {"data:" + jsoncontentstring + "}"
2. Serialize and get data result

Now if jsoncontent isn't jsonobject this no work :(

**Comment by ufna** [comment]
After e24ca5865409806e8c50abd1687f6af805d1b80c you can use hack by @saidmoya12 with content wrapping. For today it fixes the issue. I'll update it on Marketplace too now.

**Comment by martoof** [comment]
Hello,
I have this error, is a patch will be make for this ? (UE4.20)
```
JSON(
[
    {
        "Name": "1",
        "itemName": "Cookie"
    },
    {
        "Name": "2",
        "itemName": "Expresso"
    }
]
)JSON
LogVaRest: Error: UVaRestJsonObject::SetRootObject(45): Trying to set invalid json object as root one. Reset now.
```

**Comment by ufna** [comment]
Hi @martoof ,

No, unfortunately top-level arrays are not supported. Please wrap it to var, f.e.

{ "myarray" = [...] }

**Comment by martoof** [comment]
Thanks for response @ufna  ,
Surprisingly, the request response work fine, I have juste an error message in my log but execution is good (i fill a data table with the response), so I wondered if it was serious?

**Comment by ufna** [comment]
@martoof No, it's really not a serious issues if you're processing it manually and it works :)

**Comment by DarkKelt** [comment]
How i can get data from responce if all time get "{}" string?
