### ISSUE TITLE
Varest working in 4.18, Not working at all in 4.19

### ISSUE THREAD

**Issue by SCFDMerch** [ufna/VaRest#167]
Updated my project to 4.19 since varest has been updated for it, varest does not work at all, completely dead, i tried a new project and a test database and still does not work at all completely dead in 4.19, double checked the database and everything in 4.18 works fine, but 4.19 completely dead have not had a single piece of it work so far and i have tried multiple projects and even had my mate test it all out on his computer same thing. I am using Echo commands inside my PHP to return data from my database and not a single echo command has gone through. And my current workflow worked perfectly fine before 4.19, so if im doing something wrong it would be good if atleast i can get a changelist of what was changed so i can adapt to the changes. but even still i have not had it work once so far in 4.19, please help!! thanks
![image](https://user-images.githubusercontent.com/26312629/40868761-910ab9ca-6653-11e8-9e87-e95f7fcd467e.png)
![image](https://user-images.githubusercontent.com/26312629/40868774-bef9cc36-6653-11e8-926b-b4cf0c45fe61.png)
This is what i had before 4.19 and it was working fine, and now the only thing that returns is that getting response content the way i am here has been deprecated so i tried using the new node for it and it doesn't work at all, i have also checked the database to atleast see if i could update the database and that maybe getting the response was the problem, but i could not update anything on the database and even on the test database.
![image](https://user-images.githubusercontent.com/26312629/40868822-86aa1f1a-6654-11e8-830c-f45565a85822.png)
Heres the PHP im using 
![image](https://user-images.githubusercontent.com/26312629/40868867-2aa55aee-6655-11e8-906b-a4c56b3c8a56.png)
![image](https://user-images.githubusercontent.com/26312629/40868873-3f7b1b8e-6655-11e8-940c-bb471e2b5ebf.png)
This is the dbconnect php 
![image](https://user-images.githubusercontent.com/26312629/40868892-7916d770-6655-11e8-980a-3367778c81b8.png)
I can also confirm the PHP works because i can use a browser and it works fine
This is what the users table looks like on the database
![image](https://user-images.githubusercontent.com/26312629/40868949-2ea65fa2-6656-11e8-8616-34dc6f0cfe99.png)

**Comment by ufna** [comment]
Hi @SCFDMerch ,

ProcessURL is not a latent function - you can't call GetResponseContent immediately after it. Please change it to ApplyURL first. Provide logs then, please.

**Comment by SCFDMerch** [comment]
Hi @ufna i have tried both, ive been using varest for awhile now with applyrURL, applyURL was right underneath processURL because i had already tried it, the reason why i had processURL there is because it wasnt working, i had tried using the old process url with a binded event, the event fires fine but gets no response content and server doesnt update, i have tried just about everything and nothing even gives the slightest reply, while in 4.18 it worked perfectly had no problems whatsoever, all i did was update the project and it refuses to work
![image](https://user-images.githubusercontent.com/26312629/40877145-40a8755a-66bf-11e8-9991-b83054e776d5.png)

**Comment by ufna** [comment]
Please provide logs. All requests are printed to logs.

What's the json you're receiving from server?

**Comment by SCFDMerch** [comment]
I wasnt planning to recieve data as a json format from the server, since previously thats how i was using it, i have however tried echoing it out as json format and that still did not work, And where would i find all the logs your talking about? all i know is the way i was using varest was fine until this update and there was no mention of these changes.

**Comment by KurtBurgess** [comment]
Hi I'm having the same issue
When requesting data from a server, va-rest will always return {} even when data available to be returned

**Comment by ufna** [comment]
@SCFDMerch ,

In log I see that you're receiving from server just "success" string. It's not a valid json, so request is failed.

**Comment by ufna** [comment]
@KurtBurgess ,

Please provide example of server response you;re receiving.

**Comment by KurtBurgess** [comment]
Apologies @ufna I have realised that the mistake was on my end, I was using the Get Content that was depreciated, thus I needed to modify my code to use Get Response Objects and change my web code to construct JSON objects packaged with the data I was passing to the plugin.

**Comment by SCFDMerch** [comment]
@ufna i would recommend mentioning in you changelist that you have changed these things to avoid this issue in the future, of all the tutorials i have seen using your plugin, most of them simply echo out a string like success, that is how i built my data around that idea, so in the future please mention when you change something major like this, this could have been avoided by simply mentioning that it was deprecated and showing a quick example of how to use the new system

**Comment by Antize** [comment]
Ok I fixed, you need to make a simple string request please.

![1](https://user-images.githubusercontent.com/10509024/41011519-8988c236-693d-11e8-9bf9-493a7f8b9e29.png)

![2](https://user-images.githubusercontent.com/10509024/41011533-94e513f0-693d-11e8-9ea5-d9df3f5e657b.png)

**Comment by Shakoorshs** [comment]
when I wanted to use "GetResponseContent"  It gives me This notification:

DEPRECATED: please use GetResponseContentAsString() instead

and when I use that it just shows this:
{}

so please help me I reeeaaaaallyyy need to use your plugin in Unreal Engine 4 

Just show me to the direction to learn 

Respects

**Comment by KurtBurgess** [comment]
You need to encode your data as JSON on the web side and then from within Unreal you need to Get Field, I use get field by field name, where the field name is the same as the JSON name

**Comment by Shakoorshs** [comment]
Dear Kurt Burgess
Thank you very very much for your response i really hope you can help me out

on the web side I do encode my Data and it returns some thing like this:
{"status": "online","username": "shakoor","email": "shakoor@sh.com","banned": "no","kills": "0","wins": "0"}
so i will use "Get Field" as you said and it works fine but when I have some thing like this on the server:
{"status": "online","username": "shakoor","email": "shakoor@sh.com","banned": "no","kills": "0","wins": "0"}{"status": "online","username": "shakoor2","email": "shakoor@sh.com2","banned": "no","kills": "0","wins": "0"} 

So I have more than 1 json object and let's say I want to show the second result 
I just don't know how proceed 
you see the same code works fine for 1 json object but when it is more than 1 it doesn't work
so please please 
help me 
all I want to do is to have list of specific data on the server encoded as json and show them all
that is it  
"GetResponseContent" will print everything I guess, but it does not work anymore (Deprecated)

thank you again for your attention 

Respects

**Comment by ufna** [comment]
Hi @Shakoorshs ,

It's even not a valid json! You should wrap it into array:

{"myarray": [{"status":...}, {"status":...}, ...]}

**Comment by GuttaStudios** [comment]
Having same issue here and for the life of me I can;t figure it out. All of my data come thorough fine in the ue4 log "see img below"
![loginfo](https://user-images.githubusercontent.com/12000066/42000484-cb04cfaa-7a2e-11e8-90f2-32dcff7fefde.png)

But unable to access of coarse because if the recent deprication.

@KurtBurgess 
I have tried to json_encode my varibles and retrive them with the get field but im really unsure how to achieve this. "see next imgs"
![phpjsonencode](https://user-images.githubusercontent.com/12000066/42000758-b7acf7c4-7a2f-11e8-9ed1-40d911752bcd.png)
![getguid](https://user-images.githubusercontent.com/12000066/42000927-52c44d98-7a30-11e8-8984-fa06d2e0bc69.png)

Would it be possible to give a example on how you have done this. It have been months I have been struggling to convert to varest new system any guidance would be appriciated.
