### ISSUE TITLE
Trying to set invalid json object as root one. Reset now

### ISSUE THREAD

**Issue by yummyV** [ufna/VaRest#174]
Am on UE 4.19.2 and get the error - 
"Trying to set invalid json object as root one. Reset now."

Just downloaded the plugin yesterday from the marketplace 1.1 -r22

Not sure what I can do, I saw a post where this was raised in May and UNFA said he updated the Marketplace, I guess it still has an issue.

**Comment by ufna** [comment]
Hi @yummyV ,

It could be valid behaviour if you're using manual processing for non-json data. Please provide example of data you're processing.
