### ISSUE TITLE
Missing plugin binaries

### ISSUE THREAD

**Issue by dnesov** [ufna/VaRest#175]
![image](https://user-images.githubusercontent.com/8338166/42813230-8d83034e-89c0-11e8-8cb3-540991f6dab4.png)
Any help?

**Comment by ufna** [comment]
Hi @dnesov ,

What version of engine do you use?

**Comment by dnesov** [comment]
Hello! I use 4.19.2 @ufna

**Comment by ufna** [comment]
Did you try to rebuild your project with MSVS? @dnesov

**Comment by dnesov** [comment]
nah
