### ISSUE TITLE
Accessing UVaRestLibrary from C++

### ISSUE THREAD

**Issue by vorixo** [ufna/VaRest#177]
Hello creators,

first of all, congratulations for your plugin, it is one of the most valuable pieces of engineering apported to the UE4 community, and as a developer I am, I'm so grateful with you all. 

I came across recently to a problem where I wasn't able to use the **UVaRestLibrary** from C++, and this is why it is missing _XXX_API macro_, so I am unable to call its methods from a different module in C++. 

I would like to request, if it is not that much of an issue, the addition of the macro in the class definition, so the BP library could be used on other modules.

PS: UE4 Version I am using is 4.19, I would like if posible to have this feature on that version aswell.

**Comment by ufna** [comment]
Hi @vorixo ,

Thanks for it :)
