### ISSUE TITLE
Problem building APK with Varest Plugin

### ISSUE THREAD

**Issue by Peddokh** [ufna/VaRest#178]
Hello, everybody.
I'm using the GitHub version, so 1.1-r22 with Unreal 4.20.1
The plugin is work well, but I have a problem has come up though which is causing the build to fail (APK), the message is saying that it is unable to load a file from the plugin from the intermediate folder: 'C:\Program Files\Epic Games\UE_4.20\Engine\Plugins\VaRest\Intermediate\Build\Android\UE4\Development\VaRestPlugin\VaRestPlugin.precompiled'.
Any Suggestions or help in this regard would be appreciated.

**Comment by ufna** [comment]
Hi @Peddokh ,

BTW you should use 1.1-r23 version for 4.20, but if you're upgraded plugin by yourself you shouldn't use version from Marketplace. It's a precompiled one and works a bit different. Just put the plugin into your project and build then :)

**Comment by Peddokh** [comment]
Thx so much, with version -23 finally I can make the APK.
But I still got another problem now, I made an easy function for check if is work with the server and is work on editor engine, but on Android device is doesn't work.
I need change something about the network on Project Settings? or the problem is other else?
Thx again.

**Comment by ufna** [comment]
In the Project Settings dialog, look in the Engine - Network section for Libcurl Verify Peer checkbox. Try turning it off and see if it works.

**Comment by Peddokh** [comment]
No, unfortunately still doesn't work.

**Comment by ufna** [comment]
What's in log for it?

**Comment by Peddokh** [comment]
What do you mean? Sorry, but I still learning xD

**Comment by ufna** [comment]
Check https://wiki.unrealengine.com/Logs,_Printing_Messages_To_Yourself_During_Runtime and then enable VeryVerbose category logs for:
LogHttp
LogVaRest

Then use ADB to get logs from device.

**Comment by Peddokh** [comment]
I hope is this: 

W_BaseStation_C /Engine/Transient.GameEngine_0:TSS_GameInstance_C_0.W_BaseStation_C_0
	Function /Game/UI/Widget/Station/W_BaseStation.W_BaseStation_C:ExecuteUbergraph_W_BaseStation:01BF
[2018.08.03-18.39.57:695][130]LogScript: Warning: Script call stack:
	Function /Game/UI/Widget/Station/W_BaseStation.W_BaseStation_C:BndEvt__Button_246_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
	Function /Game/UI/Widget/Station/W_BaseStation.W_BaseStation_C:ExecuteUbergraph_W_BaseStation

[2018.08.03-18.39.58:941][205]LogScript: Warning: Accessed None
	W_BaseStation_C /Engine/Transient.GameEngine_0:TSS_GameInstance_C_0.W_BaseStation_C_0
	Function /Game/UI/Widget/Station/W_BaseStation.W_BaseStation_C:ExecuteUbergraph_W_BaseStation:00EE
[2018.08.03-18.39.58:941][205]LogScript: Warning: Script call stack:
	Function /Game/UI/Widget/Station/W_BaseStation.W_BaseStation_C:BndEvt__Button_246_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
	Function /Game/UI/Widget/Station/W_BaseStation.W_BaseStation_C:ExecuteUbergraph_W_BaseStation

[2018.08.03-18.39.58:942][205]LogScript: Warning: Accessed None
	W_BaseStation_C /Engine/Transient.GameEngine_0:TSS_GameInstance_C_0.W_BaseStation_C_0
	Function /Game/UI/Widget/Station/W_BaseStation.W_BaseStation_C:ExecuteUbergraph_W_BaseStation:0130
[2018.08.03-18.39.58:942][205]LogScript: Warning: Script call stack:
	Function /Game/UI/Widget/Station/W_BaseStation.W_BaseStation_C:BndEvt__Button_246_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
	Function /Game/UI/Widget/Station/W_BaseStation.W_BaseStation_C:ExecuteUbergraph_W_BaseStation

[2018.08.03-18.39.58:942][205]LogScript: Warning: Accessed None trying to read property JSONVAR
	W_BaseStation_C /Engine/Transient.GameEngine_0:TSS_GameInstance_C_0.W_BaseStation_C_0
	Function /Game/UI/Widget/Station/W_BaseStation.W_BaseStation_C:ExecuteUbergraph_W_BaseStation:0164
[2018.08.03-18.39.58:943][205]LogScript: Warning: Script call stack:
	Function /Game/UI/Widget/Station/W_BaseStation.W_BaseStation_C:BndEvt__Button_246_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
	Function /Game/UI/Widget/Station/W_BaseStation.W_BaseStation_C:ExecuteUbergraph_W_BaseStation

[2018.08.03-18.39.58:943][205]LogScript: Warning: Accessed None trying to read property Request
	W_BaseStation_C /Engine/Transient.GameEngine_0:TSS_GameInstance_C_0.W_BaseStation_C_0
	Function /Game/UI/Widget/Station/W_BaseStation.W_BaseStation_C:ExecuteUbergraph_W_BaseStation:0196
[2018.08.03-18.39.58:944][205]LogScript: Warning: Script call stack:
	Function /Game/UI/Widget/Station/W_BaseStation.W_BaseStation_C:BndEvt__Button_246_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
	Function /Game/UI/Widget/Station/W_BaseStation.W_BaseStation_C:ExecuteUbergraph_W_BaseStation

[2018.08.03-18.39.58:944][205]LogScript: Warning: Accessed None trying to read property Request
	W_BaseStation_C /Engine/Transient.GameEngine_0:TSS_GameInstance_C_0.W_BaseStation_C_0

**Comment by Peddokh** [comment]
![screenshot_1](https://user-images.githubusercontent.com/30414970/43660167-1838d098-9756-11e8-8149-7a808c0c5d67.png)
![screenshot_2](https://user-images.githubusercontent.com/30414970/43660175-1b875ec2-9756-11e8-9ed6-a74c12faf082.png)

**Comment by Peddokh** [comment]
I don't know where I make mistake...

**Comment by ufna** [comment]
Please try to use ProcessUrl instead. I'm not sure that ApplyUrl will work in this case (it really must be refactored, I should do it soon :) )

**Comment by Peddokh** [comment]
If I use Process URL where can I get the "Result" ?
![screenshot_3](https://user-images.githubusercontent.com/30414970/43661555-a0a09bf6-975a-11e8-9067-9fa35a52b710.png)

**Comment by ufna** [comment]
You should use bind few events: https://camo.githubusercontent.com/f05dd0c57d39ff3c225ae9008d1a075574f70f6d/687474703a2f2f75666e612e72752f6769746875622f7661726573742f7661726573745f6578616d706c655f73696d706c656765742e6a7067

**Comment by Peddokh** [comment]
Still work on editor but not on Android.
![screenshot_4](https://user-images.githubusercontent.com/30414970/43662598-6377f86a-975e-11e8-9cce-c2b060dd042a.png)
Plus, I can't use "Get Field" after custom event.

**Comment by ufna** [comment]
Heh, I see that your project is BP-only. Unfortunately, plugins like meine are not fully supported for BP-only projects, it's the known feature of engine itself. Just convert your project to C++ one and all will be fine.

**Comment by Peddokh** [comment]
Ah...because I saw this "No C++ coding required, everything can be managed via blueprints" so, I was thinking is perfect for BP-only.
Anyway, thx for the help, I'll try it and let you know.

**Comment by ufna** [comment]
Yep, no coding required, but C++ project :( I hope Epics will fix this later.

**Comment by Peddokh** [comment]
Finally is work!!!
Thanks so much mate <3

**Comment by ufna** [comment]
You're welcome! ;)
