### ISSUE TITLE
UTF8 Letters don't work

### ISSUE THREAD

**Issue by mbpictures** [ufna/VaRest#180]
Hello!
I'm from Germany and I'm trying to use "umlauts" (ö, ä, ü) within you plugin. But it always give me an "?" instead of the umlaut. Do you have any idea how to fix it?

Best regards!

**Comment by G1K777** [comment]
You need to convert them to Binary. Or use HTML coding like &auml;

**Comment by mbpictures** [comment]
I'll give it a try, thank you very much!
