### ISSUE TITLE
Not able to get API response on android shipping apk

### ISSUE THREAD

**Issue by tagorenavabothu** [ufna/VaRest#184]
Everything worked when I ran the build from the editor, On the shipping build API hit is not happening. 

I installed the Plugin from the marketplace. 

[](https://imgur.com/a/SR9MAMt)

check the above URL for integration.

**Comment by tagorenavabothu** [comment]
Got it, Permissions are removing at runtime in my project. I corrected them and working.

**Comment by ben657** [comment]
Hey there, i'm having a similar problem at the moment. Could you describe how you managed to fix the permissions problem?
