### ISSUE TITLE
How can I use ConstructWhereQuery?

### ISSUE THREAD

**Issue by torus** [ufna/VaRest#19]
I have read the plugin's source and the ConstructWhereQuery method looks so useful.
But I couldn't find out how to use it.

What should I connect a ConstructWhereQuery node to?

**Comment by ufna** [comment]
Hi!

It should be used instead "regular" query constructor when you're using Parse Object quering with "where" condition. That's all the difference from regular one :)

**Comment by torus** [comment]
Thanks! I'll try it.
