### ISSUE TITLE
Requesting https interface failed

### ISSUE THREAD

**Issue by Aqiang223** [ufna/VaRest#193]
Windows platform,What do I need to set up?

LogHttp: Warning: 000001D5770F4900: request failed, libcurl error: 51 (SSL peer certificate or SSH remote key was not OK)
LogHttp: Warning: 000001D5770F4900: libcurl info message cache 0 (Hostname rest.ms-zm.com was found in DNS cache)
LogHttp: Warning: 000001D5770F4900: libcurl info message cache 1 (  Trying 116.62.131.198...)
LogHttp: Warning: 000001D5770F4900: libcurl info message cache 2 (TCP_NODELAY set)
LogHttp: Warning: 000001D5770F4900: libcurl info message cache 3 (Connected to rest.ms-zm.com (116.62.131.198) port 443 (#1))
LogHttp: Warning: 000001D5770F4900: libcurl info message cache 4 (ALPN, offering http/1.1)
LogHttp: Warning: 000001D5770F4900: libcurl info message cache 5 (Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH)
LogHttp: Warning: 000001D5770F4900: libcurl info message cache 6 (SSL re-using session ID)
LogHttp: Warning: 000001D5770F4900: libcurl info message cache 7 (TLSv1.2 (OUT), TLS handshake, Client hello (1):)
LogHttp: Warning: 000001D5770F4900: libcurl info message cache 8 (TLSv1.2 (IN), TLS handshake, Server hello (2):)
LogHttp: Warning: 000001D5770F4900: libcurl info message cache 9 (TLSv1.2 (IN), TLS handshake, Certificate (11):)
LogHttp: Warning: 000001D5770F4900: libcurl info message cache 10 (TLSv1.2 (IN), TLS handshake, Server key exchange (12):)
LogHttp: Warning: 000001D5770F4900: libcurl info message cache 11 (TLSv1.2 (IN), TLS handshake, Server finished (14):)
LogHttp: Warning: 000001D5770F4900: libcurl info message cache 12 (TLSv1.2 (OUT), TLS handshake, Client key exchange (16):)
LogHttp: Warning: 000001D5770F4900: libcurl info message cache 13 (TLSv1.2 (OUT), TLS change cipher, Client hello (1):)
LogHttp: Warning: 000001D5770F4900: libcurl info message cache 14 (TLSv1.2 (OUT), TLS handshake, Finished (20):)
LogHttp: Warning: 000001D5770F4900: libcurl info message cache 15 (TLSv1.2 (IN), TLS change cipher, Client hello (1):)
LogHttp: Warning: 000001D5770F4900: libcurl info message cache 16 (TLSv1.2 (IN), TLS handshake, Finished (20):)
LogHttp: Warning: 000001D5770F4900: libcurl info message cache 17 (SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384)
LogHttp: Warning: 000001D5770F4900: libcurl info message cache 18 (ALPN, server accepted to use http/1.1)
LogHttp: Warning: 000001D5770F4900: libcurl info message cache 19 (old SSL session ID is stale, removing)
LogHttp: Warning: 000001D5770F4900: libcurl info message cache 20 (Server certificate:)
LogHttp: Warning: 000001D5770F4900: libcurl info message cache 21 ( subject: CN=*.maijju.com)
LogHttp: Warning: 000001D5770F4900: libcurl info message cache 22 ( start date: Sep 28 02:06:10 2018 GMT)
LogHttp: Warning: 000001D5770F4900: libcurl info message cache 23 ( expire date: Dec 27 02:06:10 2018 GMT)
LogHttp: Warning: 000001D5770F4900: libcurl info message cache 24 ( subjectAltName does not match rest.ms-zm.com)
LogHttp: Warning: 000001D5770F4900: libcurl info message cache 25 (SSL: no alternative certificate subject name matches target host name 'rest.ms-zm.com')
LogHttp: Warning: 000001D5770F4900: libcurl info message cache 26 (Closing connection 1)
LogHttp: Warning: 000001D5770F4900: libcurl info message cache 27 (TLSv1.2 (OUT), TLS alert, Client hello (1):)

**Comment by Aqiang223** [comment]
@ufna

**Comment by ufna** [comment]
Hi @Aqiang223 ,

You should disable Libcurl Verify Peer in project settings, or use trusted sertificate :)
