### ISSUE TITLE
Unicode character becomes u-code representation in string

### ISSUE THREAD

**Issue by DevChagrins** [ufna/VaRest#199]
I'm receiving some data back from a Request and once GetResponseContentAsString is called, the character é is replaced with u00e9.

Upon further inspection the é shows up in the Destination Buffer in UVaRestJsonObject::DeserializeFromUTF8Bytes but after encoding the data, this is changed to the string u00e9.

**Comment by ufna** [comment]
@nnprudnikov , please check it.
