### ISSUE TITLE
Request always fails in HTML Shipping

### ISSUE THREAD

**Issue by L34D3R** [ufna/VaRest#200]
Request always fails in HTML Shipping. My logic is shown in the attached image. Can you please help here.

I tried with UE 4.19, UE 4.20, UE 4.21
![HTML Request fail](https://user-images.githubusercontent.com/13694300/54974094-c0e01b00-4fb8-11e9-825b-a0ead6f3b5a3.JPG)

**Comment by ufna** [comment]
HTML5 won't be supported anymore, as it's a deprecated stuff with lots of limits

**Comment by HusainBlu** [comment]
is there any workaround or alternate way?
