### ISSUE TITLE
[Info] Why the request is not processed

### ISSUE THREAD

**Issue by MrChebik** [ufna/VaRest#207]
Hi, I'm new.
On Wiki page, we can see [simple GET request](https://github.com/ufna/VaRest/wiki/Plugin-Usage#simple-get-request).
So, I make own request, but he does not tell me, if request was completed or failed.
![Screenshot_2019-04-12_07-58-49](https://user-images.githubusercontent.com/11232501/56013473-8df88f80-5cf9-11e9-9ed1-0b6d8395014f.png)
But, I found function 'Call URL'. And with it, everything works for me.
![Screenshot_2019-04-12_07-59-47](https://user-images.githubusercontent.com/11232501/56013502-ab2d5e00-5cf9-11e9-82d2-c79b463efbdf.png)

Response from my request is very simple: only code (200 / 406).

**Comment by ufna** [comment]
Hi @MrChebik ,

Construct Json Request node is pure (not exec one), and each usage has its own function result. Three requests in your case. Just save the result to variable once and use it then.
