### ISSUE TITLE
How can I post user data from unreal to webserver?

### ISSUE THREAD

**Issue by Keate** [ufna/VaRest#210]
Now I can login after registering my account from website,and when I create register widget,I want to send user registration data to resgiter.php for activating account.
Is there a solution to do this?

**Comment by ufna** [comment]
Hi @Keate ,

You should construct POST request and send data you want. So, `register.php` should process this data.

**Comment by Keate** [comment]
I have no idea of what's wrong with this,Can you help me？My JSON file is empty as the UE log shows.
-----------------------------------------------------------------------
LogVaRest: UVaRestRequestJSON::ProcessRequest(353): Request (urlencoded): POST http://smarthomevr.dx.am/register.php?name=lim&email=keate1029%40gmail.com&password=asdasd&confirm_password=asdasd (check bExtendedLog for additional data)
LogBlueprintUserMessages: [RegisterWidget_C_0] An email for activating your accont has sent to you
LogVaRest: Response (200): 
JSON(
)JSON
LogVaRest: Error: UVaRestJsonObject::SetRootObject(45): Trying to set invalid json object as root one. Reset now.
-----------------------------------------------------------------------
And my php code is here.
`<?php
session_start();

include('includes/config.php');
include('includes/db.php');
include('includes/functions.php');



$data = file_get_contents("php://input"); 
$content = utf8_encode($data); 
$userdata = json_decode($content,true); 


$name = mysqli_real_escape_string($db , $userdata->name);
$email = mysqli_real_escape_string($db , $userdata->email);
$password = mysqli_real_escape_string($db , $userdata->password);
$token = bin2hex(openssl_random_pseudo_bytes(32));
        
$query = "insert into users (name,email,password,token) values('$name','$email','$password','$token')";
        
$db->query($query);
$message = "Hi $name! Account created here is the activation link http://smarthomevr.dx.am/activate.php?token=$token";
        
mail($email , 'Activate Account' , $message , 'From: keate@smarthomevr.dx.am');

exit();
    
?> 
`
I'm lack of  the ability of php coding. I just tried to register at my website and log in in Unreal before, and actually, I engage myself in registering account in Unreal.

**Comment by Keate** [comment]
[https://blueprintue.com/blueprint/lotdtyjr/](url)
What I have done in blueprint

**Comment by Keate** [comment]
[https://blueprintue.com/blueprint/lotdtyjr/](url)
What I have done in blueprint

**Comment by Keate** [comment]
> Hi @Keate ,
> 
> You should construct POST request and send data you want. So, `register.php` should process this data.

Now, I have changed content type into JSON, instead of URL. It logs Json successfully, but my php still cannot write these data into DB. How can I fix it?

**Comment by ufna** [comment]
@Keate , 

`LogVaRest: Error: UVaRestJsonObject::SetRootObject(45): ` - is not a problem at all, but you have an empty response from server. Just print `{}` and all will be fine with it.

But to process vars on your server-side, you should look for PHP guys. I'm not familiar with modern php and unfortunately I can't help with it.

**Comment by Keate** [comment]
I've fixed it. It works well now. Thank you @ufna for your plugin, and I can continue my work now.

**Comment by ufna** [comment]
You're welcome! :)

**Comment by andreasnts** [comment]
How did you solve it? I have the same problem :(

**Comment by Keate** [comment]
> How did you solve it? I have the same problem :(

Hi, you mean which problem?
