### ISSUE TITLE
How to send Bytes array?

### ISSUE THREAD

**Issue by oppne** [ufna/VaRest#212]
So currently i have to do this

"The payload must use the content type “multipart/form-data” where the image content is a byte array. Along with the image data, the following request headers must also set:"

So currently i have made an object that sets the headers, and i need a way to send the image as a byte array. How do i set this up in blueprint? I currently have the image pixel data, but i dont know where to set it. I get the respons 591, and the server gets the byte array as "NULL"
Adding an image to my current setup

https://user-images.githubusercontent.com/22558756/57628010-636c5180-7599-11e9-94d1-db26befa5f76.png

All the headers work, its only that im trying to send the image content as a number array field, and its not working!

Image below is the respons content

https://user-images.githubusercontent.com/22558756/57628188-be9e4400-7599-11e9-90ab-767b2f50066d.png

**Comment by ufna** [comment]
Hi @oppne ,

You should try `UVaRestRequestJSON::SetBinaryRequestContent` function

**Comment by ufna** [comment]
Hm, and also `multipart/form-data` is not supported. If you want to upload image with plugin you should modify VaRest and add one more `ERequestContentType` with logic you need.

**Comment by ufna** [comment]
Check https://github.com/ufna/VaRest/blob/develop/Source/VaRestPlugin/Private/VaRestRequestJSON.cpp#L310

**Comment by oppne** [comment]
Is there anyway to remove the json wrapping around the object which is sent? Because it seems like the multipart/form-data it does not consider.

**Comment by ufna** [comment]
@oppne `multipart/form-data` is not supported by plugin. To make it right you should modify the code I've mentioned above.

**Comment by oppne** [comment]
So i need to copy something like this

https://stackoverflow.com/questions/48609620/send-post-multipart-form-data-request-using-restbed-c
