### ISSUE TITLE
Does not convert json_encode message from PHP

### ISSUE THREAD

**Issue by aesipenko** [ufna/VaRest#213]
Hi!
I am passing a json message from PHP. The message contains Cyrillic. The word is displayed in the browser as \u0420\u043e\u043c\u0430\u043d and then decoded correctly. But in UE, u0420u043eu043cu0430u043d is output. If I send a string without json_encode
`echo "{\"method\": \"Кириллица\", \"params\": []}";`
, then all characters will be valid.

I tried Response Content and GetResponseContentAsString.
UE4 4.22.1
VaRest-1.1-r25.2

Why the word is not decoded?

**Comment by aesipenko** [comment]
I added a parameter JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE in json_encode and now everything is working correctly.
Thanks for the great plugin.

**Comment by ufna** [comment]
@aesipenko great you solved it! :)
