### ISSUE TITLE
Create own multipart form data

### ISSUE THREAD

**Issue by oppne** [ufna/VaRest#216]
I have created an own function under "VaRestRequestJSON.CPP"

Under (RequestContentType)
![image](https://user-images.githubusercontent.com/22558756/58585146-2cb05f80-8258-11e9-96c5-cccd81ab5daf.png)

And use it this way
![image](https://user-images.githubusercontent.com/22558756/58585273-8d3f9c80-8258-11e9-922a-357380b3034a.png)

But i only get this error message

}
LogHttp: Warning: 000001D6B5EA7880: request has been successfully processed. URL: SecretURL!!!, HTTP code: 500, content length: 0, actual payload size: 0
LogHttp: Warning: 000001D6B5EA7880 Response Header Server: nginx/1.15.10
LogHttp: Warning: 000001D6B5EA7880 Response Header Date: Wed, 29 May 2019 18:49:48 GMT
LogHttp: Warning: 000001D6B5EA7880 Response Header Content-Length: 0
LogHttp: Warning: 000001D6B5EA7880 Response Header Connection: keep-alive
LogHttp: Warning: 000001D6B5EA7880 Response Header Strict-Transport-Security: max-age=15724800; includeSubDomains

As i see it, the content is 0, but i set the headers corretcly and use the function

**Comment by ufna** [comment]
Hi, 

It'll be added in https://github.com/ufna/VaRest/issues/74
