### ISSUE TITLE
GET requests very slow

### ISSUE THREAD

**Issue by garnold54** [ufna/VaRest#217]
I am using VaRest for a research project which is doing a lot of GET requests against a REST API. It works great and has been very helpful in my project. However, I noticed that GET requests were taking a very long time to return. Something like dozens of seconds up to a minute or more. Doing the same GET requests from a terminal on the same machine returned right away.  After some digging around, I ran into this issue:

https://answers.unrealengine.com/questions/471251/http-requests-are-very-slow.html

which suggests that the `HttpRequest->SetContentAsString(OutputString);` should not be set on GET requests. I patched my local version of VaRest by changing this line:

https://github.com/ufna/VaRest/blob/3154d9fa4243d72ef0c6d47708dde6395b8a4049/Source/VaRestPlugin/Private/VaRestRequestJSON.cpp#L411

To look like:
```
if(RequestVerb != ERequestVerb::GET) {
    HttpRequest->SetContentAsString(OutputString);
}
```

This fixed the slowness issue for me and the GET requests started returning right away. I am not 100% sure this is the right fix, but it does seem like the `SetContentAsString` should not be set if we are doing a GET that expects JSON to be returned.

This was all on Windows.

**Comment by ufna** [comment]
Hi @garnold54 ,

The right solution is not using GET verb, especially for 'application/json' request types. I'll add warning about it, but it's all on developer.

**Comment by ufna** [comment]
`we are doing a GET that expects JSON to be returned.`

You shouldn't use `application/json` for it. Content type is for request data, not for response!

**Comment by garnold54** [comment]
Ah, ok. So then how should I properly do a GET request that expects a JSON response using VARest?

Should I be using the "Construct Json Request (Empty)" node in the blueprint and then use the "Set Verb" to make it a "GET" instead of using the "Construct Json Request" node?

**Comment by ufna** [comment]
> So then how should I properly do a GET request that expects a JSON response using VARest?

Just use default, which is `ERequestContentType::x_www_form_urlencoded_url`. 

> Should I be using the "Construct Json Request (Empty)" node in the blueprint and then use the "Set Verb" to make it a "GET" instead of using the "Construct Json Request" node?

Both variants are equal :)
