### ISSUE TITLE
Android packaging always show errors

### ISSUE THREAD

**Issue by MriV13** [ufna/VaRest#218]
Hi
i cant find solution for this error in Output log when i packaging my game.

Packaging(Androdi)
> LogVaRest: Error: UVaRestJsonObject::SetRootObject(40): Trying to set invalid json object as root one. Reset now.
> LogVaRest: Warning: JSON could not be decoded!
> LogBlueprintUserMessages: [req_C_0] blad
> LogVaRest: UVaRestRequestJSON::ProcessRequest(350): Request (urlencoded): POST randomwebsite.dx.am/TrashStatus/CheckNetwork.php (check bExtendedLog for additional data)
> LogVaRest: Response (200): 
> JSON(
> ok
> )JSON

In the editor everything works fine.
I am using ue4.22 but its the same problems on diffrents engine also.
I installed plugin from marketplace.
I am using plugin from 2 years and everything was fine but when i tryed install manually then plugin stop works, i was trying reinstall plugin and created new project but always the same errors, 
Please help me.

**Comment by ufna** [comment]
Hi @MriV13 ,

It assumed that you have a valid json in response. For example, `{"result" : "ok"}', instead of "ok" in your case.

**Comment by MriV13** [comment]
@ufna i am not sure what do you mean but when i make like this 
shows string "ok" in game. 
![image](https://user-images.githubusercontent.com/28051592/58958538-6bd43880-87a3-11e9-99e3-f6c9a144ec53.png)

**Comment by MriV13** [comment]
IsValidJsonResponse always false, but why? how can i fix it?

**Comment by ufna** [comment]
Because json response is not valid. Response content should be presented in json format.

**Comment by MriV13** [comment]
so my php file is incorrect?
My file:

> <?php
		die ("ok"); 
?>

so i should do like this:

> <?php
		die (`{"result" : "ok"}');
?>

when i tryed this second option in my response content string shows =DEPRECATED: Please use getResponseContentAsString() instead
but is valid now

**Comment by ufna** [comment]
Yes, exactly! And use GetResponseContentAsString() instead :)

**Comment by MriV13** [comment]
Thank you very much
I found solution. In php file i changed to JSON format e.g
` die (`{"result" : "ok"}');`
and in the ue4 i am using something like this:
![image](https://user-images.githubusercontent.com/28051592/58970831-764dfc80-87ba-11e9-9b5c-e08d9f583ea4.png)
but i am a little bit confused why plugin varest stopped work after 'nothing'. I was using over 2 years this plugin and i never used it that way
I think i had some errors with decode or encode JSON, but why? who knows :)

**Comment by ufna** [comment]
@MriV13 , It's not "nothing", plugin was updated :)
