### ISSUE TITLE
{} UE4 4.19

### ISSUE THREAD

**Issue by anhuntz** [ufna/VaRest#219]
Just trying a simple "GET" from my HTTP PHP file. Worked fine in 4.16, 4.17, 4.18, etc. 

In 4.19 though it just get's the string: "{}"

![image](https://user-images.githubusercontent.com/49049502/59310714-4482dd00-8c75-11e9-8143-f27587a0a855.png)

I don't really know what else to say. It prints "{}" when it should print the PHP text. The PHP file itself is literally just echos for testing but it won't even get them.

Any fix?

**Comment by ufna** [comment]
Hi @anhuntz ,

It's the same as disscussed at https://github.com/ufna/VaRest/issues/218 . Just make sure you have json output format from server. 

Plugin was updated and format policy is more strict now.

**Comment by ufna** [comment]
@anhuntz are you using github version or marketplace one?

**Comment by anhuntz** [comment]
> @anhuntz are you using github version or marketplace one?

Marketplace

**Comment by ufna** [comment]
@anhuntz , I'll check it tomorrow. It's outdated version with bugs maybe, in latest one you can use your approach (with warnings, but working).

**Comment by anhuntz** [comment]
> @anhuntz , I'll check it tomorrow. It's outdated version with bugs maybe, in latest one you can use your approach (with warnings, but working).

Sure let me know if you figure something out. I'd really like if the plugin worked like it used to

**Comment by ufna** [comment]
Hi @anhuntz ,

Unfortunately I found that I can't update marketplace version for UE4.19 due to Marketplace rules. So, you can add the plugin into your project from github UE4.19 branch https://github.com/ufna/VaRest/tree/4.19 , or update the engine to UE 4.20 and up.
