### ISSUE TITLE
Response Tutorial needed

### ISSUE THREAD

**Issue by Gr3enP0ison** [ufna/VaRest#22]
We I followed your tutorial and got a problem. I followed your instructions for the system and got a problem which I cannot solve.
How I can get a response after I posted data to an url. 
+ How can I send for example a "username" and a "password" to an url with a response. 
I checked out your wiki but I think it is a bit incomplete or I din't check it :( .
It would be nice if anybody could help me...

**Comment by shiftone242** [comment]
![network-login](https://cloud.githubusercontent.com/assets/10530415/6311292/877a349a-b958-11e4-932e-1acd7cf73a61.jpg)

Here is a basic set-up I used previously, its not the best example but maybe it can be of some help.

**Comment by Gr3enP0ison** [comment]
Wow , thank you really much

**Comment by Gr3enP0ison** [comment]
Yeah right, but is there an example for Post without JSON ?

**Comment by ufna** [comment]
@Gr3enP0ison currently it's not possible, you have to use json to prepare set of key=param values. Then you can POST it with x_www_form_urlencoded form, so params from json will be serialized into string as part of url.
