### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by RyuMaster** [ufna/VaRest#220]
TCHAR* DestinationBuffer = new TCHAR[DestinationLength];

nevers gets deleted;

Also, in many
UE_LOG functions,

*balabla->SomeString()
produces memory leaks, has to be

FString asas= balabla->SomeString();
UE_LOG(*asas)

**Comment by ufna** [comment]
Hi @RyuMaster ,

Thanks for pointing this buffer, fixed now.

Regarding UE_LOG, please provide an example. `UE_LOG(LogVaRest, Log, TEXT("%s: Request (urlencoded): %s %s (check bExtendedLog for additional data)"), *VA_FUNC_LINE, *HttpRequest->GetVerb(), *HttpRequest->GetURL());` is completely valid, I don't see any leaks here. (also, it widely used in the engine code itself)

**Comment by RyuMaster** [comment]
Hi! In regards to UE_LOG, I am no sure, it just reliably produces me memory leak when I am using

#define MALLOC_LEAKDETECTION 1
MallocLeak Start

to test.

but maybe false alarms then?

**Comment by ufna** [comment]
Hm, I'll test it today with the same define.

**Comment by RyuMaster** [comment]
Righty! I was just following this tutorial for my project:

https://dzone.com/articles/dealing-with-memory-leaks-in-unreal-engine-4

And stumbled upon it

**Comment by ufna** [comment]
@RyuMaster , I've checked it and and seemed okay :)
