### ISSUE TITLE
[Android arm64] Plugin 'VaRestPlugin" failed to load

### ISSUE THREAD

**Issue by martoof** [ufna/VaRest#221]
I want to export my Android build for the Play Store.
It want a 64 bits release (because that's what GooglePlayConsole wants now)
I check "Support arm64" in project settings.
Build success but after installing :

> Plugin 'VaRestPlugin" failed to load because module 'VaRestPlugin' could not be found.

with armv7, it's perfectly work.
Any idea ?
Is it the good solution to make android 64 bits build ?
This project is BP only.
Thanks

**Comment by ufna** [comment]
Hi @martoof ,

Unfortunately, pre-compiled version of VaRest on the Marketplace is completely managed by Epics, I can't do nothing with it.

But plugin itself supports arm64 as it should, so you can use the Github version instead of marketplace one to package your project. Negative side effect - you should switch your project to the C++ one in this case.

I hope Epics will add arm64 support for marketplace plugins.

**Comment by martoof** [comment]
Thank you @ufna for your answer, you are always so fast and efficient!
I will try to compile arm64 via github and I hope that epic will add support 64bits on the marketplace in the coming months to meet the obligations of stores.
I will make a return on this thread to say if it worked!

**Comment by ufna** [comment]
You're welcome! Please keep informed :)

**Comment by martoof** [comment]
Ok, here is my feedback.
I compile the 64bits version of VaRestPlugin with a clean new project.
Then, I follow this instructions : https://github.com/ufna/VaRest/wiki/Plugin-Installation---compile-from-source
So i put my files to C:\Program Files\Epic Games\UE_4.18\Engine\Plugins\Marketplace\VaRestPlugin

When i compile a project which use VaRestPlugin arm64, i have this error :
```
ERROR: Missing precompiled manifest for 'VaRestPlugin'. This module was most likely not flagged for being included in a precompiled build - set 'PrecompileForTargets = PrecompileTargetsType.Any;' in VaRestPlugin.build.cs to override.
PackagingResults: Error: Missing precompiled manifest for 'VaRestPlugin'. This module was most likely not flagged for being included in a precompiled build - set 'PrecompileForTargets = PrecompileTargetsType.Any;' in VaRestPlugin.build.cs to override.
```

So i have put the plugin directly in my project in a Plugins folder, and it's work perfectly !!

So i don't know why this don't work with plugin in engine folder whereas work in project folder.
And for my personal culture, i would like to have an explain ;)
