### ISSUE TITLE
Setting a Timeout

### ISSUE THREAD

**Issue by justadaniel** [ufna/VaRest#222]
Hey, I was wondering if there was an ability to set a request timeout? I think it's needed in case a server is down.

**Comment by ufna** [comment]
Hi @justadaniel ,

All http request inside are managed with HTTP module. You can configure its timeout like this in DefaultEngine.ini

```
[HTTP]
HttpTimeout=15
```

**Comment by justadaniel** [comment]
Thanks for the quick response! Works like a charm! :)

**Comment by ufna** [comment]
You're welcome! :)

**Comment by solanki-parin** [comment]
i changed in BaseEngine but it worked like a charm a spend entire day for this this saved my day
