### ISSUE TITLE
Remote compiling requires a server name when Packaging IOS

### ISSUE THREAD

**Issue by yuchengzhong** [ufna/VaRest#223]
When Im trying to build a IOS version from my windows PC,
this **"Remote compiling requires a server name"** showed up.
**(Fully Blueprint Porject)** 
And it never happened before.How to solve this problem?Do I need a MAC to build this project? Thanks.
Also when I use a pure blueprint project,and tried to Package the project.Both IOS and Windows platform got error. 
**Windows:** 
PackagingResults: Error: Visual Studio 2017 must be installed in order to build this target. PackagingResults: Error: Unknown Error 
**IOS:** 
PackagingResults: Error: Remote compiling requires a server name. Please specify one in the Remote Server Name settings field.

Could anyone tell me how to build my pure blueprint project into IOS or Windows **without a Mac and VS 2017**?
Thanks.

**Comment by ufna** [comment]
Hi @yuchengzhong ,

It's required for projects with C++ plugins enabled. Btw, what engine version you're using?
