### ISSUE TITLE
Request not working when build or run standalone

### ISSUE THREAD

**Issue by stealthgun** [ufna/VaRest#224]
Hey,

I have an issue where I can run VaREST fine within the Editor but once I build a game or run it standalone the request fails.

In the Editor:
`LogVaRest: UVaRestRequestJSON::ProcessRequest(388): Request (url body): GET https://api.gjdwebserver.nl/ords/darkharvest/information/news (check bExtendedLog for additional data)
LogVaRest: Response (200): 
`

but when ran standalone:

`[2019.10.02-15.46.41:173][  0]LogVaRest: UVaRestRequestJSON::ProcessRequest(384): Request (url body): GET https://api.gjdwebserver.nl/ords/darkharvest/information/news `

That's the only logging I can see (with extended log on) 
I am running 4.23 with the marketplace plugin

**Comment by stealthgun** [comment]
I ve done abit of debugging and reduced it to the callback.

![callback](https://user-images.githubusercontent.com/129263/66066114-2f45fd00-e549-11e9-96de-d242f3b6d3d3.png)

what I see now is:
[2019.10.02-17.13.54:748][  0]LogVaRest: Request (binary): GET https://api.gjdwebserver.nl/ords/darkharvest/information/news
[2019.10.02-17.13.54:748][  0]LogBlueprintUserMessages: [DarkHarvestGameInstance_C_0] Started Varest URL Call

but I don't see the "Varest Response" debug line.

**Comment by ufna** [comment]
Hi @stealthgun ,

It seemed to be a bug of Call URL node, I'm completely rewriting it right now. For this time I recommend to use `Process URL` instead

**Comment by stealthgun** [comment]
@ufna Thank you Process URL did the trick.

**Comment by ufna** [comment]
Glad it helped. I'll close the issue for now, because it's a part of current refactoring
