### ISSUE TITLE
Set Array Field sending empty array to server.

### ISSUE THREAD

**Issue by TheBossBaby** [ufna/VaRest#228]
Set Array Field node is sending empty array to the server and when used with other fields like string field only strings are sent to the server no array is sent to the sever.

**Comment by ufna** [comment]
Hi @TheBossBaby , 

Please provide an example

**Comment by TheBossBaby** [comment]
![image](https://user-images.githubusercontent.com/30798744/67142727-a2f24480-f281-11e9-9136-3edb01f52811.png)
![image](https://user-images.githubusercontent.com/30798744/67142731-bb625f00-f281-11e9-98b2-b72177d1786a.png)

**Comment by ufna** [comment]
![c0963f6eceb798db45012bef5ddb9da6](https://user-images.githubusercontent.com/271578/67143186-569f0880-f271-11e9-9ccc-9521a148631f.png)

And the postman answer:

```json
{
   "args":{

   },
   "data":{
      "string array":[
         "123",
         "456",
         "",
         "321"
      ],
      "number array":[
         0,
         1,
         4,
         2
      ],
      "id":"test id !!!"
   },
   "files":{

   },
   "form":{

   },
   "headers":{
      "x-forwarded-proto":"https",
      "host":"postman-echo.com",
      "content-length":"121",
      "accept":"*/*",
      "accept-encoding":"deflate, gzip",
      "content-type":"application/json",
      "user-agent":"VaRestDemo/++UE4+Release-4.23-CL-8386587 Windows/10.0.18362.1.256.64bit",
      "x-forwarded-port":"443"
   },
   "json":{
      "string array":[
         "123",
         "456",
         "",
         "321"
      ],
      "number array":[
         0,
         1,
         4,
         2
      ],
      "id":"test id !!!"
   },
   "url":"https://postman-echo.com/post"
}
```

So, please check you're filling it right and processing on your server too.

**Comment by TheBossBaby** [comment]
Ok, Thanks for your quick response let me try it thanks.

**Comment by TheBossBaby** [comment]
@ufna it's still sending blank array.

**Comment by ufna** [comment]
![6514b7b74eee1cae14fef99477efdb45](https://user-images.githubusercontent.com/271578/67148517-f7f58100-f2a8-11e9-8062-4e10679b1589.png)

Are you sure with this?

**Comment by TheBossBaby** [comment]
@ufna I want to send POST request content type: x-www-form-urlencoded(Request Body) with few strings and some arrays, your response is for JSON content.

I am sending screenshot again in a cleaner way:

![image](https://user-images.githubusercontent.com/30798744/67150762-7cf88e80-f2d9-11e9-9fa1-646429895d8a.png)

![image](https://user-images.githubusercontent.com/30798744/67150771-926db880-f2d9-11e9-8cb0-195dc1a420e5.png)

**Comment by ufna** [comment]
@TheBossBaby , arrays are not supported with `x-www-form-urlencoded`. There is no clear way to implement them, so use `json` instead.

**Comment by TheBossBaby** [comment]
@ufna thanks for your quick response, I followed your code for sending request data as JSON, but its blank at server side.

When I am testing the by postman server is showing the data.

Unreal Code
![image](https://user-images.githubusercontent.com/30798744/67157985-2ed2a200-f350-11e9-8549-89d883c62062.png)

Server side
![image](https://user-images.githubusercontent.com/30798744/67158064-1d3dca00-f351-11e9-9f8e-8be5574b24f9.png)

Postman Request:
![image](https://user-images.githubusercontent.com/30798744/67158093-4eb69580-f351-11e9-8f44-4ccf76e2045d.png)

Server Side:
![image](https://user-images.githubusercontent.com/30798744/67158098-5f670b80-f351-11e9-83f0-31818ac1e4b9.png)

Thanks in advance.

**Comment by ufna** [comment]
@TheBossBaby , don't use Pure blueprint nodes as it's on screen. Provide result of 'Construct Json Request' as variable and use it instead.

This is forced not to be pure bp in lates github release.

**Comment by TheBossBaby** [comment]
Thanks, it fixed.
