### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by davesenter** [ufna/VaRest#24]
I'm having trouble installing this plugin. Following the installation instructions, it seems I need VaQuoleUI? Which requires Qt to be installed? 

Where is the binaries archive? Is this created by the user? Basically, I'm all mixed up and need more detailed installation instructions.

**Comment by ufna** [comment]
Oh, I need to update docs now.. Thanks for mentioned it.

**Comment by davesenter** [comment]
Any update on this? Or can anyone breakdown how to install JUST the VaRest plugin?

**Comment by davesenter** [comment]
This seems to be working. I was at least able to get the Editor open after dropping the plugin into the plugins folder. Still trying to get this working in Blueprint.

**Comment by ufna** [comment]
I've updated installation instructions for VaRest only: https://github.com/ufna/VaRest/wiki/Plugin-Installation
