### ISSUE TITLE
Is it possible to make an example GET request on the wiki?

### ISSUE THREAD

**Issue by ZeProf2Code** [ufna/VaRest#242]
Hello, I'm trying to do a request with this plugin on my webserver but I don't know what to add : https://blueprintue.com/blueprint/629isrm_/

**Comment by ZeProf2Code** [comment]
(it's in a UMG widget)

**Comment by ZeProf2Code** [comment]
okay so I got it working but now I have a problem : 
the response is `[{"id":"1","username":"ZeProf2Coding","health":"100","stamina":"100","money":"500","inventory":"[]"}]`
but with that code I cannot retrive the money field :
https://blueprintue.com/blueprint/pk52o_6i/

**Comment by ufna** [comment]
first, remove top-level array fron json, it should be:

```
{
   "id":"1",
   "username":"ZeProf2Coding",
   "health":100,
   "stamina":100,
   "money":500,
   "inventory":[  ]
}
```

second, you functions GetStringField / GetNumberField instead, and all will be okay!
