### ISSUE TITLE
Compile on 4.24 Preview 1

### ISSUE THREAD

**Issue by grigorovich** [ufna/VaRest#246]
To compile plugin on 4.24 Ive just trim namespace 'UE4StringConv_Private' in file **Source/VaRestPlugin/Private/VaRestJsonParser.cpp** (line 86):

`if (UE4StringConv_Private::IsHighSurrogate(Codepoint) || UE4StringConv_Private::IsLowSurrogate(Codepoint))
`
to dat
`if (StringConv::IsHighSurrogate(Codepoint) || StringConv::IsLowSurrogate(Codepoint))`.

**UE4StringConv_Private** to  **StringConv**

Compiled and works fine with UE 4.24 Preview 1 on macos 10.15.1 and xcode 11.2

**Comment by ufna** [comment]
Thanks, @grigorovich , I've moved UE 4.24 support to separate branch until its release.
