### ISSUE TITLE
Renaming the plugin from VaRestPlugin to VaRest caused all BP nodes to become invalid

### ISSUE THREAD

**Issue by CodeSpartan** [ufna/VaRest#249]
Renaming the plugin from VaRestPlugin to VaRest caused all BP nodes to become invalid in projects that already relied on VaRest before migrating to 4.24.

In just one project, I now have 171 errors:
![a022a95cfaf43831fcee2207037efaee](https://user-images.githubusercontent.com/10173914/70740174-a0641680-1d29-11ea-82b9-431a4ee58d7a.png)

Would you happen to know if it's possible to create a redirector? If not, maybe it'd make more sense to roll back the name change?

**Comment by ufna** [comment]
Hi @CodeSpartan ,

Yep, I'll think how to make it right asap.

**Comment by ufna** [comment]
@CodeSpartan , I've pushed redirectors config, please check.
