### ISSUE TITLE
Folder and .uplugin name for iOS and Android

### ISSUE THREAD

**Issue by tuxbook** [ufna/VaRest#25]
I had to change the folder name from VaRest to VaRestPlugin to get it package to Android.

On iOS I also had to change the name of the .uplugin file from VaRest to VaRestPlugin for it to work.

Once I did that it worked like a charm! Love the library ufna, you're awesome! :D

Edit: This is with UE 4.7.5 (launcher build on PC for Android, source release branch build on Mac for iOS)

**Comment by ufna** [comment]
Thanks for the testing! I'll fix it and make a new release soon! :+1:

**Comment by ufna** [comment]
Done :)
