### ISSUE TITLE
How to process url in secure mode/https?

### ISSUE THREAD

**Issue by dEROZA** [ufna/VaRest#260]
Not understanding where I can try to ask my question, I trying it here.

I'm not a guru in web server development, but have understood most of kinds for this, unlike in secure protocol. So I wanna to know how I can request correctly my https resource in UE4 via VaREST?

**Comment by ufna** [comment]
Hi @dEROZA , just set url with https and it should be fine.

**Comment by dEROZA** [comment]
> 
> 
> Hi @dEROZA , just set url with https and it should be fine.

hmm, can you show me code line where this plugin starts processing https querry?

**Comment by ufna** [comment]
Nope, it's inside FPlatformHttpRequest.

**Comment by dEROZA** [comment]
> FPlatformHttpRequest

Why? What is it FPlatformHttpRequest?

**Comment by ufna** [comment]
You can check https://docs.unrealengine.com/en-US/API/Runtime/HTTP/Interfaces/IHttpRequest/index.html and https://docs.unrealengine.com/en-US/API/Runtime/HTTP/FHttpModule/index.html

**Comment by dEROZA** [comment]
Okay. Thanks, it's internal eg communication feature.
Can you provide to me an advice when I must use https, and when it must be non-secure requests?

**Comment by ufna** [comment]
I would recommend to use https always :)

**Comment by dEROZA** [comment]
Okay, thanks a lot! Good job in a REST side communication.. GLHF >_<

**Comment by ufna** [comment]
Thanks)

**Comment by dEROZA** [comment]
Did u sure that FPlatformHttpRequest works with h2c protocol?

**Comment by ufna** [comment]
@dEROZA , I'm sure it's not. Internally it works as http/1.1
