### ISSUE TITLE
UVaRestJsonObject::WriteToFile Produces Empty Entries

### ISSUE THREAD

**Issue by simongloor** [ufna/VaRest#261]
When using `UVaRestJsonObject::WriteToFile` on the Branch `4.24` the Results look something like this: 
 
`{"":"","":{"":{"":},"":{"":[{"":,"":,"":,"":,"":,"":,"":,"":},{"":,"":,"":,"":,"":,"":,"":,"":},{"":,"":,"":,"":,"":,"":,"":,"":},{"":,"":,"":,"":,"":,"":,"":,"":},{"":,"":,"":,"":,"":,"":,"":,"":}]}}}`

My current workaround is to use  `UVaRestJsonObject::EncodeJsonToSingleString()` in combination with `FFileHelper::SaveStringToFile`.

**Comment by ufna** [comment]
Hi @simongloor 
Please use develop branch instead for now. Version branches will be updated asap.
