### ISSUE TITLE
Broken after update.. new feature?

### ISSUE THREAD

**Issue by dEROZA** [ufna/VaRest#267]
![изображение](https://user-images.githubusercontent.com/8126176/74088912-5653a300-4ad6-11ea-99d7-901509aff79f.png)

**Comment by ufna** [comment]
Hi @dEROZA ,

Yes, plugin was moved to subsystems usage, it requires some manual fixes. I'll prepare a doc soon.

**Comment by dEROZA** [comment]
![изображение](https://user-images.githubusercontent.com/8126176/74146074-443f4500-4c3b-11ea-8075-985c9f8d789b.png)
Why you began subsystem using?

**Comment by ufna** [comment]
Subsystems are better way (and also native one for the egnine) to handle lifetime for things like that. It's the course declared by Epics, so I've switched to its usage.
