### ISSUE TITLE
After recent update POST is GET

### ISSUE THREAD

**Issue by Neubivljiv** [ufna/VaRest#270]
Hello,

I noticed after recent update that POST method is not working. I debugged on the web server and it was the  GET method. 

![123](https://user-images.githubusercontent.com/339178/74596149-991ff880-504b-11ea-92dd-61800ffeb73b.jpg)

![234](https://user-images.githubusercontent.com/339178/74596175-f025cd80-504b-11ea-9fc7-72ba51af2adb.jpg)

This returns GET and empty POST

**Comment by ufna** [comment]
Hi @Neubivljiv ,

I've just tested the latest development branch, and it works as it should. Please provide more detailes and check the request with LogHttp set to Verbose.

**Comment by Neubivljiv** [comment]
Hello @ufna, 

I tried to find this "check the request with LogHttp set to Verbose" but could not. 
Can you be more specific where to check this? 

I tested with custom verb but the same results. 
Also I have tested on the local webserver and remote webserver and got the same results. 
Here is what I did:
![111](https://user-images.githubusercontent.com/339178/74605476-b810a000-50c8-11ea-86cc-a99f00ce4e9b.jpg)

And on the webserver this is simple debug script:
![222](https://user-images.githubusercontent.com/339178/74605493-d24a7e00-50c8-11ea-9886-aa495f8f3ac8.jpg)

_debug.txt contains this:
![333](https://user-images.githubusercontent.com/339178/74605507-e55d4e00-50c8-11ea-88d9-172dbf15750b.jpg)

In previous version I got the POST method and it returned something like this:
`(POST) action = test13648 `

Now it returns only GET.

Unreal engine return this in the output log:
```
LogVaRest: UVaRestRequestJSON::ProcessRequest(347): Request (urlencoded): POST https://website.com/apitest/?action=test13648 (check bExtendedLog for additional data)
LogVaRest: Response (200): 
```

**Comment by Neubivljiv** [comment]
Ok here is additional debug. 

I put this:

`$request_method = $_SERVER['REQUEST_METHOD'];`

and it indeed returns POST method, but POST array is empty.

So I tried this:

`$rest_json = file_get_contents("php://input");
$_POST = json_decode( $_POST, true);`

but it also returns empty POST

**Comment by trdwll** [comment]
I can verify that it works with the latest commit (1a7815f0067f8c773540506f37dec76f52ffd25f) on develop. 
Here's the BP that I used. I also tested all of the content types and they work just fine.
![Capture](https://user-images.githubusercontent.com/11054333/74623311-2037a400-5112-11ea-99c7-900dadb41beb.PNG)

**Comment by ufna** [comment]
@Neubivljiv , 

`curl -H "Content-Type: application/x-www-form-urlencoded" -X POST https://website.com/api/ -d "\"action\"=\"Test Value\""` -- is not valid test for case you're showing, because you're set params into body, not the url. Try to construct request with `x-www-form-urlencoded (Request Body)`

**Comment by Neubivljiv** [comment]
@ufna I tested with parameters into body and it's working. Not sure why there are option to build url via string field as POST method (which will send URL with GET parameters). 

Thanks.

**Comment by ufna** [comment]
It's POST, but parameters are part of URL (so in PHP you're reading them from `$_GET`).

Glad it solved now :)
