### ISSUE TITLE
Make Json does not respect link to String Tables in Blueprints

### ISSUE THREAD

**Issue by erpy** [ufna/VaRest#278]
Make Json node does not re-link String Tables at load time, when engine starts.
I'm not sure whether this is an issue to this specific node or an engine bug, but I'm using String Tables elsewhere and happens only with Make Json.

See attached image for reference.

VaRest 1.1 r28, UE4.24.3

![varestStringTables](https://user-images.githubusercontent.com/734976/75635939-a2e45700-5c1a-11ea-9dcc-22fd9130e1f0.jpg)

**Comment by erpy** [comment]
The bug has worsened with latest update. 
Now I can't open the project (Editor crashes) even disabling the plugin from the .uproject file.
Restoring previous VaRest version loads the project fine (although with the string table bug).

**Comment by ufna** [comment]
Hi @erpy ,

PinNames shouldn't be localized at all, it changed to FName now (as it already works internally).

Regarding crash please provide crash log and open new issue (it shouldn't be connected with this one :) )

**Comment by erpy** [comment]
Assertion failed: Enum [File:D:/Build/++UE4/Sync/Engine/Source/Runtime/CoreUObject/Private/UObject/EnumProperty.cpp] [Line: 209]

UE4Editor_Core!AssertFailedImplV() [d:\build\++ue4\sync\engine\source\runtime\core\private\misc\assertionmacros.cpp:105]
UE4Editor_Core!FDebug::CheckVerifyFailedImpl() [d:\build\++ue4\sync\engine\source\runtime\core\private\misc\assertionmacros.cpp:455]
UE4Editor_CoreUObject!UEnumProperty::ExportTextItem() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\enumproperty.cpp:209]
UE4Editor_CoreUObject!UProperty::ExportText_Direct() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\property.cpp:732]
UE4Editor_UnrealEd!FBlueprintEditorUtils::PropertyValueToString_Direct() [d:\build\++ue4\sync\engine\source\editor\unrealed\private\kismet2\blueprinteditorutils.cpp:8607]
UE4Editor_BlueprintGraph!UK2Node_MakeStruct::FMakeStructPinManager::CustomizePinData() [d:\build\++ue4\sync\engine\source\editor\blueprintgraph\private\k2node_makestruct.cpp:72]
UE4Editor_BlueprintGraph!FOptionalPinManager::CreateVisiblePins() [d:\build\++ue4\sync\engine\source\editor\blueprintgraph\private\k2node.cpp:1588]
UE4Editor_BlueprintGraph!UK2Node_MakeStruct::AllocateDefaultPins() [d:\build\++ue4\sync\engine\source\editor\blueprintgraph\private\k2node_makestruct.cpp:133]
UE4Editor_BlueprintGraph!UK2Node::ReallocatePinsDuringReconstruction() [d:\build\++ue4\sync\engine\source\editor\blueprintgraph\private\k2node.cpp:574]
UE4Editor_BlueprintGraph!UK2Node::ReconstructNode() [d:\build\++ue4\sync\engine\source\editor\blueprintgraph\private\k2node.cpp:675]
UE4Editor_BlueprintGraph!UEdGraphSchema_K2::ReconstructNode() [d:\build\++ue4\sync\engine\source\editor\blueprintgraph\private\edgraphschema_k2.cpp:4595]
UE4Editor_UnrealEd!FBlueprintEditorUtils::ReconstructAllNodes() [d:\build\++ue4\sync\engine\source\editor\unrealed\private\kismet2\blueprinteditorutils.cpp:578]
UE4Editor_Kismet!FBlueprintCompilationManagerImpl::FlushCompilationQueueImpl() [d:\build\++ue4\sync\engine\source\editor\kismet\private\blueprintcompilationmanager.cpp:998]
UE4Editor_Kismet!FBlueprintCompilationManager::FlushCompilationQueue() [d:\build\++ue4\sync\engine\source\editor\kismet\private\blueprintcompilationmanager.cpp:2916]
UE4Editor_CoreUObject!FScopedClassDependencyGather::~FScopedClassDependencyGather() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\blueprint\blueprintsupport.cpp:439]
UE4Editor_CoreUObject!FLinkerLoad::CreateExport() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:4564]
UE4Editor_CoreUObject!FLinkerLoad::IndexToObject() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:4797]
UE4Editor_CoreUObject!FLinkerLoad::CreateExport() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:4171]
UE4Editor_CoreUObject!FLinkerLoad::CreateExportAndPreload() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:3216]
UE4Editor_CoreUObject!FLinkerLoad::LoadAllObjects() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:3380]
UE4Editor_CoreUObject!LoadPackageInternal() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\uobjectglobals.cpp:1311]
UE4Editor_CoreUObject!FLinkerLoad::VerifyImportInner() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:2849]
UE4Editor_CoreUObject!FLinkerLoad::VerifyImport() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:2581]
UE4Editor_CoreUObject!FLinkerLoad::VerifyImportInner() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:2915]
UE4Editor_CoreUObject!FLinkerLoad::VerifyImport() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:2581]
UE4Editor_CoreUObject!FLinkerLoad::Verify() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:2353]
UE4Editor_CoreUObject!FLinkerLoad::FinalizeCreation() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:2255]
UE4Editor_CoreUObject!FLinkerLoad::Tick() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:788]
UE4Editor_CoreUObject!FLinkerLoad::CreateLinker() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:457]
UE4Editor_CoreUObject!GetPackageLinker() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linker.cpp:736]
UE4Editor_CoreUObject!LoadPackageInternal() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\uobjectglobals.cpp:1207]
UE4Editor_CoreUObject!FLinkerLoad::VerifyImportInner() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:2849]
UE4Editor_CoreUObject!FLinkerLoad::VerifyImport() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:2581]
UE4Editor_CoreUObject!FLinkerLoad::VerifyImportInner() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:2915]
UE4Editor_CoreUObject!FLinkerLoad::VerifyImport() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:2581]
UE4Editor_CoreUObject!FLinkerLoad::VerifyImportInner() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:2915]
UE4Editor_CoreUObject!FLinkerLoad::VerifyImport() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:2581]
UE4Editor_CoreUObject!FLinkerLoad::Verify() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:2353]
UE4Editor_CoreUObject!FLinkerLoad::FinalizeCreation() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:2255]
UE4Editor_CoreUObject!FLinkerLoad::Tick() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:788]
UE4Editor_CoreUObject!FLinkerLoad::CreateLinker() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:457]
UE4Editor_CoreUObject!GetPackageLinker() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linker.cpp:736]
UE4Editor_CoreUObject!LoadPackageInternal() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\uobjectglobals.cpp:1207]
UE4Editor_CoreUObject!FLinkerLoad::VerifyImportInner() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:2849]
UE4Editor_CoreUObject!FLinkerLoad::VerifyImport() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:2581]
UE4Editor_CoreUObject!FLinkerLoad::VerifyImportInner() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:2915]
UE4Editor_CoreUObject!FLinkerLoad::VerifyImport() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:2581]
UE4Editor_CoreUObject!FLinkerLoad::Verify() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:2353]
UE4Editor_CoreUObject!FLinkerLoad::FinalizeCreation() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:2255]
UE4Editor_CoreUObject!FLinkerLoad::Tick() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:788]
UE4Editor_CoreUObject!FLinkerLoad::CreateLinker() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:457]
UE4Editor_CoreUObject!GetPackageLinker() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linker.cpp:736]
UE4Editor_CoreUObject!LoadPackageInternal() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\uobjectglobals.cpp:1207]
UE4Editor_CoreUObject!LoadPackage() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\uobjectglobals.cpp:1426]
UE4Editor_UnrealEd!UEditorEngine::Map_Load() [d:\build\++ue4\sync\engine\source\editor\unrealed\private\editorserver.cpp:2558]
UE4Editor_UnrealEd!UEditorEngine::HandleMapCommand() [d:\build\++ue4\sync\engine\source\editor\unrealed\private\editorserver.cpp:6106]
UE4Editor_UnrealEd!UEditorEngine::Exec() [d:\build\++ue4\sync\engine\source\editor\unrealed\private\editorserver.cpp:5586]
UE4Editor_UnrealEd!UUnrealEdEngine::Exec() [d:\build\++ue4\sync\engine\source\editor\unrealed\private\unrealedsrv.cpp:696]
UE4Editor_UnrealEd!FEditorFileUtils::LoadMap() [d:\build\++ue4\sync\engine\source\editor\unrealed\private\filehelpers.cpp:2466]
UE4Editor_UnrealEd!FEditorFileUtils::LoadDefaultMapAtStartup() [d:\build\++ue4\sync\engine\source\editor\unrealed\private\filehelpers.cpp:3842]
UE4Editor_UnrealEd!FUnrealEdMisc::OnInit() [d:\build\++ue4\sync\engine\source\editor\unrealed\private\unrealedmisc.cpp:353]
UE4Editor_UnrealEd!EditorInit() [d:\build\++ue4\sync\engine\source\editor\unrealed\private\unrealedglobals.cpp:114]
UE4Editor!GuardedMain() [d:\build\++ue4\sync\engine\source\runtime\launch\private\launch.cpp:154]
UE4Editor!GuardedMainWrapper() [d:\build\++ue4\sync\engine\source\runtime\launch\private\windows\launchwindows.cpp:134]
UE4Editor!WinMain() [d:\build\++ue4\sync\engine\source\runtime\launch\private\windows\launchwindows.cpp:263]
UE4Editor!__scrt_common_main_seh() [d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll

**Comment by ufna** [comment]
Please try to remove all files in \VaRest\Config\*.ini

**Comment by erpy** [comment]
> Please try to remove all files in \VaRest\Config*.ini

Unfortunately won't solve it. Same crash, same source lines as well.

**Comment by ufna** [comment]
Is it possible to provide a small project with issue reproduce?

**Comment by erpy** [comment]
> Is it possible to provide a small project with issue reproduce?

I will try to repro, but it does seem related to this thread subject matter. At startup the pins are mis-connected due to the bug. I suspect the engine can't cope with that all with the new version...

**Comment by ufna** [comment]
Please try, it will be superb if you get it. VaRest was refactored, breaking in some cases. It's hard to check all cases, which are not used in projects I'm working on :(

**Comment by erpy** [comment]
> Please try, it will be superb if you get it. VaRest was refactored, breaking in some cases. It's hard to check all cases, which are not used in projects I'm working on :(

Yup, no problem!
It is peculiar though that it crashes with the plugin **disabled** (!?)

**Comment by ufna** [comment]
thanks! 

> It is peculiar though that it crashes with the plugin disabled (!?)
Yep, node creating is complex process, so it could crash even when plugin is disable, cause it has some generated data inside already.

**Comment by erpy** [comment]
> thanks!
> 
> > It is peculiar though that it crashes with the plugin disabled (!?)
> 
> Yep, node creating is complex process, so it could crash even when plugin is disabled, cause it has some generated data inside already.

I tried fixing that node for good, saved the BP, re-opened with r29...but no go.

**Comment by ufna** [comment]
It continues to crash or smth else?

**Comment by erpy** [comment]
Crash continues. 
It seems impossible to move to any new version of VaRest from r28 with Blueprints using it in place.
I took off the folder using it, changed VaRest to latest and the Editor started. As soon as I copied the blueprints back and opened a class in Blueprint Editor, got another crash.

It does seem related to node pin construction compared to r28:


Assertion failed: Enum [File:D:/Build/++UE4/Sync/Engine/Source/Runtime/CoreUObject/Private/UObject/EnumProperty.cpp] [Line: 209]

UE4Editor_Core!AssertFailedImplV() [d:\build\++ue4\sync\engine\source\runtime\core\private\misc\assertionmacros.cpp:105]
UE4Editor_Core!FDebug::CheckVerifyFailedImpl() [d:\build\++ue4\sync\engine\source\runtime\core\private\misc\assertionmacros.cpp:455]
UE4Editor_CoreUObject!UEnumProperty::ExportTextItem() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\enumproperty.cpp:209]
UE4Editor_CoreUObject!UProperty::ExportText_Direct() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\property.cpp:732]
UE4Editor_UnrealEd!FBlueprintEditorUtils::PropertyValueToString_Direct() [d:\build\++ue4\sync\engine\source\editor\unrealed\private\kismet2\blueprinteditorutils.cpp:8607]
UE4Editor_BlueprintGraph!UK2Node_MakeStruct::FMakeStructPinManager::CustomizePinData() [d:\build\++ue4\sync\engine\source\editor\blueprintgraph\private\k2node_makestruct.cpp:72]
UE4Editor_BlueprintGraph!FOptionalPinManager::CreateVisiblePins() [d:\build\++ue4\sync\engine\source\editor\blueprintgraph\private\k2node.cpp:1588]
UE4Editor_BlueprintGraph!UK2Node_MakeStruct::AllocateDefaultPins() [d:\build\++ue4\sync\engine\source\editor\blueprintgraph\private\k2node_makestruct.cpp:133]
UE4Editor_BlueprintGraph!UK2Node::ReallocatePinsDuringReconstruction() [d:\build\++ue4\sync\engine\source\editor\blueprintgraph\private\k2node.cpp:574]
UE4Editor_BlueprintGraph!UK2Node::ReconstructNode() [d:\build\++ue4\sync\engine\source\editor\blueprintgraph\private\k2node.cpp:675]
UE4Editor_BlueprintGraph!UEdGraphSchema_K2::ReconstructNode() [d:\build\++ue4\sync\engine\source\editor\blueprintgraph\private\edgraphschema_k2.cpp:4595]
UE4Editor_UnrealEd!FBlueprintEditorUtils::ReconstructAllNodes() [d:\build\++ue4\sync\engine\source\editor\unrealed\private\kismet2\blueprinteditorutils.cpp:578]
UE4Editor_Kismet!FBlueprintCompilationManagerImpl::FlushCompilationQueueImpl() [d:\build\++ue4\sync\engine\source\editor\kismet\private\blueprintcompilationmanager.cpp:998]
UE4Editor_Kismet!FBlueprintCompilationManager::FlushCompilationQueue() [d:\build\++ue4\sync\engine\source\editor\kismet\private\blueprintcompilationmanager.cpp:2916]
UE4Editor_CoreUObject!FScopedClassDependencyGather::~FScopedClassDependencyGather() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\blueprint\blueprintsupport.cpp:439]
UE4Editor_CoreUObject!FLinkerLoad::CreateExport() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:4564]
UE4Editor_CoreUObject!FLinkerLoad::IndexToObject() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:4797]
UE4Editor_CoreUObject!FLinkerLoad::CreateExport() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:4171]
UE4Editor_CoreUObject!FLinkerLoad::CreateExportAndPreload() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:3216]
UE4Editor_CoreUObject!FLinkerLoad::LoadAllObjects() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:3380]
UE4Editor_CoreUObject!LoadPackageInternal() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\uobjectglobals.cpp:1311]
UE4Editor_CoreUObject!FLinkerLoad::VerifyImportInner() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:2849]
UE4Editor_CoreUObject!FLinkerLoad::VerifyImport() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:2581]
UE4Editor_CoreUObject!FLinkerLoad::VerifyImportInner() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:2915]
UE4Editor_CoreUObject!FLinkerLoad::VerifyImport() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:2581]
UE4Editor_CoreUObject!FLinkerLoad::VerifyImportInner() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:2915]
UE4Editor_CoreUObject!FLinkerLoad::VerifyImport() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:2581]
UE4Editor_CoreUObject!FLinkerLoad::Verify() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:2353]
UE4Editor_CoreUObject!FLinkerLoad::FinalizeCreation() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:2255]
UE4Editor_CoreUObject!FLinkerLoad::Tick() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:788]
UE4Editor_CoreUObject!FLinkerLoad::CreateLinker() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:457]
UE4Editor_CoreUObject!GetPackageLinker() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linker.cpp:736]
UE4Editor_CoreUObject!LoadPackageInternal() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\uobjectglobals.cpp:1207]
UE4Editor_CoreUObject!FLinkerLoad::VerifyImportInner() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:2849]
UE4Editor_CoreUObject!FLinkerLoad::VerifyImport() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:2581]
UE4Editor_CoreUObject!FLinkerLoad::VerifyImportInner() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:2915]
UE4Editor_CoreUObject!FLinkerLoad::VerifyImport() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:2581]
UE4Editor_CoreUObject!FLinkerLoad::Verify() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:2353]
UE4Editor_CoreUObject!FLinkerLoad::FinalizeCreation() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:2255]
UE4Editor_CoreUObject!FLinkerLoad::Tick() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:788]
UE4Editor_CoreUObject!FLinkerLoad::CreateLinker() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linkerload.cpp:457]
UE4Editor_CoreUObject!GetPackageLinker() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\linker.cpp:736]
UE4Editor_CoreUObject!LoadPackageInternal() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\uobjectglobals.cpp:1207]
UE4Editor_CoreUObject!LoadPackage() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\uobjectglobals.cpp:1426]
UE4Editor_CoreUObject!ResolveName() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\uobjectglobals.cpp:766]
UE4Editor_CoreUObject!StaticLoadObjectInternal() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\uobjectglobals.cpp:828]
UE4Editor_CoreUObject!StaticLoadObject() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\uobjectglobals.cpp:903]
UE4Editor_ContentBrowser!SContentBrowser::OnAssetsActivated() [d:\build\++ue4\sync\engine\source\editor\contentbrowser\private\scontentbrowser.cpp:2221]
UE4Editor_ContentBrowser!TBaseSPMethodDelegateInstance<0,SContentBrowser,0,void __cdecl(TArray<FAssetData,TSizedDefaultAllocator<32> > const &,enum EAssetTypeActivationMethod::Type)>::ExecuteIfSafe() [d:\build\++ue4\sync\engine\source\runtime\core\public\delegates\delegateinstancesimpl.h:369]
UE4Editor_ContentBrowser!SAssetView::OnListMouseButtonDoubleClick() [d:\build\++ue4\sync\engine\source\editor\contentbrowser\private\sassetview.cpp:4346]
UE4Editor_ContentBrowser!TBaseSPMethodDelegateInstance<0,SAssetView,0,void __cdecl(TSharedPtr<FAssetViewItem,0>)>::ExecuteIfSafe() [d:\build\++ue4\sync\engine\source\runtime\core\public\delegates\delegateinstancesimpl.h:369]
UE4Editor_ContentBrowser!TBaseDelegate<void,TSharedPtr<FAssetViewItem,0> >::ExecuteIfBound() [d:\build\++ue4\sync\engine\source\runtime\core\public\delegates\delegatesignatureimpl.inl:673]
UE4Editor_ContentBrowser!SListView<TSharedPtr<FAssetViewItem,0> >::Private_OnItemDoubleClicked() [d:\build\++ue4\sync\engine\source\runtime\slate\public\widgets\views\slistview.h:918]
UE4Editor_ContentBrowser!STableRow<TSharedPtr<FAssetViewItem,0> >::OnMouseButtonDoubleClick() [d:\build\++ue4\sync\engine\source\runtime\slate\public\widgets\views\stablerow.h:334]
UE4Editor_Slate!FEventRouter::Route<FReply,FEventRouter::FBubblePolicy,FPointerEvent,<lambda_cde3b80cdb8a457b0f09fee78051d179> >() [d:\build\++ue4\sync\engine\source\runtime\slate\private\framework\application\slateapplication.cpp:372]
UE4Editor_Slate!FSlateApplication::RoutePointerDoubleClickEvent() [d:\build\++ue4\sync\engine\source\runtime\slate\private\framework\application\slateapplication.cpp:5068]
UE4Editor_Slate!FSlateApplication::ProcessMouseButtonDoubleClickEvent() [d:\build\++ue4\sync\engine\source\runtime\slate\private\framework\application\slateapplication.cpp:5055]
UE4Editor_Slate!FSlateApplication::OnMouseDoubleClick() [d:\build\++ue4\sync\engine\source\runtime\slate\private\framework\application\slateapplication.cpp:5021]
UE4Editor_ApplicationCore!FWindowsApplication::ProcessDeferredMessage() [d:\build\++ue4\sync\engine\source\runtime\applicationcore\private\windows\windowsapplication.cpp:1962]
UE4Editor_ApplicationCore!FWindowsApplication::DeferMessage() [d:\build\++ue4\sync\engine\source\runtime\applicationcore\private\windows\windowsapplication.cpp:2410]
UE4Editor_ApplicationCore!FWindowsApplication::ProcessMessage() [d:\build\++ue4\sync\engine\source\runtime\applicationcore\private\windows\windowsapplication.cpp:1638]
UE4Editor_ApplicationCore!FWindowsApplication::AppWndProc() [d:\build\++ue4\sync\engine\source\runtime\applicationcore\private\windows\windowsapplication.cpp:789]
user32
user32
UE4Editor_ApplicationCore!FWindowsPlatformApplicationMisc::PumpMessages() [d:\build\++ue4\sync\engine\source\runtime\applicationcore\private\windows\windowsplatformapplicationmisc.cpp:130]
UE4Editor!FEngineLoop::Tick() [d:\build\++ue4\sync\engine\source\runtime\launch\private\launchengineloop.cpp:4397]
UE4Editor!GuardedMain() [d:\build\++ue4\sync\engine\source\runtime\launch\private\launch.cpp:173]
UE4Editor!GuardedMainWrapper() [d:\build\++ue4\sync\engine\source\runtime\launch\private\windows\launchwindows.cpp:134]
UE4Editor!WinMain() [d:\build\++ue4\sync\engine\source\runtime\launch\private\windows\launchwindows.cpp:263]
UE4Editor!__scrt_common_main_seh() [d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll

**Comment by ufna** [comment]
@erpy , is it possible to provide small demo project with the issue? I can't reproduce it on my side :(

**Comment by erpy** [comment]
Made yet another test, I tried disable compilation of key nodes on all the blueprints using VaRest... but got the same crash.
At least now it is pretty sure it's not a "content" crash (i.e. accessing any null pointer) ... but it's actually crashing constructing the nodes.

**Comment by erpy** [comment]
> @erpy , is it possible to provide small demo project with the issue? I can't reproduce it on my side :(

...will try... not sure I can either.... :(

**Comment by erpy** [comment]
I think I got it.
It must be VaRest enums, as in the pic:
![VaRestStruct](https://user-images.githubusercontent.com/734976/79351497-0b706480-7f39-11ea-89cb-f7afa4189246.jpg)

This is a link to the repro project:

https://drive.google.com/open?id=1KUgYRUegD4zLh9PSQ55t8lGx_tZctBlg

VaRest r28 is in the Plugins folder. If you edit/open the struct with r28, it's fine. If you open it with r29.2 it crashes the Editor.
Please let me know when you got the project.
Thanks!

**Comment by ufna** [comment]
@erpy , thanks for WTR! Please check latest version from develop, it should work now.

**Comment by ufna** [comment]
or 4.24 branch better, develop contains version for UE4.25 for now
