### ISSUE TITLE
Request Object reference validity test always fails in Blueprint

### ISSUE THREAD

**Issue by erpy** [ufna/VaRest#279]
As soon as a "VaRest Request JSON Object" is created, it always evaluates to "not valid" using the "isValid" engine node.

Steps:
1. Construct Json Request
2. Set Json Request Object
3. Set URL
4. Test Request JSON Object for validity

**Comment by ufna** [comment]
@erpy , please provide screenshot how you're doing it exactly. And what version do you use?

**Comment by erpy** [comment]
VaRest r.28, UE 4.24.3

![varest_requestObject](https://user-images.githubusercontent.com/734976/75704376-8fd49400-5cb9-11ea-9f4b-f60d904355fc.jpg)

**Comment by erpy** [comment]
Ok, digging a bit more. I'm in Game Instance... and the VaRest SubSystem is not valid as well - if it can be tested for validity. (?!)
Maybe that can be the issue ? If it is, should I not be able to use it at all ?

**Comment by ufna** [comment]
If you're doing it on GameInstance::Init, it's not the right place. Plase do it after the GI is started.

**Comment by erpy** [comment]
> If you're doing it on GameInstance::Init, it's not the right place. Plase do it after the GI is started.

Ok, got it, thanks!
Is there a way to issue an error trying to use Subsystem when it's not avail ?

**Comment by ufna** [comment]
> Is there a way to issue an error trying to use Subsystem when it's not avail ?
It's a bit complicated for case of GameInstance::Init(). Not sure I'll do it, but I'll definitely check it again. Thanks.
