### ISSUE TITLE
Request Object treated as JSON

### ISSUE THREAD

**Issue by erpy** [ufna/VaRest#280]
(Feature Request) 
Since it looks like the Request object produced is basically a JSON object, would it be possible to treat it as such ?

I'm referring to the ability to serialize, save, encode to string a VaRest Request.
At the moment I don't seem to be able to do that with the Request Object.
It would be very useful to save and re-load pending requests, for instance.

Thanks!

**Comment by ufna** [comment]
`RequestObject` **is** a json. You can serialize it to string or vice versa, etc. Please clarify what do you mean, or provide an example :)

**Comment by erpy** [comment]
Uhmm... am I doing it wrong ?

![varest_requestObjectJson](https://user-images.githubusercontent.com/734976/75708023-450a4a80-5cc0-11ea-9341-c25719e25ad0.jpg)

**Comment by ufna** [comment]
But.. your requests are even not VaRest one :)

**Comment by ufna** [comment]
I have no idea what is the class of `Req Obj` and why it's an "Object Object" :)

**Comment by erpy** [comment]
> I have no idea what is the class of `Req Obj` and why it's an "Object Object" :)

ReqObj is just a variable name for the function output. It's a VaRest Request Object variable.
The engine message says the two VaRest objects are not compatible. (?!)

**Comment by ufna** [comment]
I see it now. Your request object is request first of all. You should do `Req Obj -> Get Request Object() -> Encode Json to Single String`

**Comment by erpy** [comment]
> I see it now. Your request object is request first of all. You should do `Req Obj -> Get Request Object() -> Encode Json to Single String`

I see. I really got confused as the "Request Object" also have a "Set Request Object"... which I use as the Json data being sent with "content type -> json".
So that IS the same json object ? i.e. Request Object is the Json object being set in the Request Object reference !?

Sorry, I don't mean to get a free tutorial, but I'm puzzle now... :))

**Comment by ufna** [comment]
There are few entities here:
First is VaRest Request -- it's a **request** object itself, not the data. But, It contains `Request Object` and `Response Object` objects that are JSON one.

**Comment by erpy** [comment]
> There are few entities here:
> First is VaRest Request -- it's a **request** object itself, not the data. But, It contains `Request Object` and `Response Object` objects that are JSON one.

Ok, so my initial request was being able to save those Request properties in order to re-call them without having to re-build requests.
At the moment I have to save the Request properties in a wrapper structure, save it, and re-build the requests when the application restarts.

Thanks!

**Comment by ufna** [comment]
You're welcome.

You can save the `Request->GetRequestObject` json and then set it to the new request.

**Comment by erpy** [comment]
> You're welcome.
> 
> You can save the `Request->GetRequestObject` json and then set it to the new request.

Last time I checked though, the Request json doesn't bring the Verb, Content Type and URL properties that were set when the Request was initially created (?!)

**Comment by ufna** [comment]
Yes, it's by design. Requests are temporal object by its nature.
