### ISSUE TITLE
Module entry 'VaRestEditor' specified an unrecognized module type 'UncookedOnly'

### ISSUE THREAD

**Issue by stkopp** [ufna/VaRest#281]
Module entry 'VaRestEditor' specified an unrecognized module type 'UncookedOnly'
UE4 2.31
This happens when I put GitHub files in plugins (p.s. is this the right way to install GitHub plugin? since I have not found any specific tutorial)

I have read that [UE deprecated UncookedOnly](https://forums.unrealengine.com/development-discussion/engine-source-github/1696288-4-24-deprecation-of-developer-module-type-uncookedonly-not-working-on-nativized-bp-assets) some time ago maybe this is the case? I want to use this plugin for android development, but Google Play decided to stop support of 32 bit forever, this means that I can not use this plugin from UE4 Marketplace (btw [EasyAds](https://www.unrealengine.com/marketplace/en-US/product/easyads) supported us with additional files to marketplace plugin so that this plugin could run smoothly with 64-bit release)

**Comment by ufna** [comment]
@stkopp Latest release for UE 4.23 is https://github.com/ufna/VaRest/releases/tag/v1.1-r26_4.23 , please use it instead latest one from develop.
