### ISSUE TITLE
Can't upgrade project from 4.23 to 4.24

### ISSUE THREAD

**Issue by Istauri** [ufna/VaRest#282]
When updating my project from engine version 4.23 to 4.24 I first got missing plugin errors, as per your reply to a different user I tried changing VaRestPlugin to VaRest in my .uproject file which removes the message but it now causes the project to crash on startup with:

`Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x00000000`

 Exploring the logs shows:
`... failed to load '/Script/VaRestPlugin': Can't find file.`
for every time I've used the nodes in BPs along with:
`LoadErrors: Failed to load /Script/VaRestPlugin.OnRequestComplete__DelegateSignature Referenced by K2Node_CreateDelegate_OutputDelegate`

The plugin is installed to the engine from the marketplace however I've been trying to install it to the Oculus build of UE4 by copying the files across from the standard editor.
This seems to have worked for fresh projects but this project can't even open under either the vanilla 4.24 or the oculus 4.24, it will open under 4.23 however.

**Comment by ufna** [comment]
Hi @Istauri ,

Let's start from the beginning. First, check that UE 4.23 is working fine. Then, please re-gen project with UE 4.24 and check that you haven't `VaRestPlugin` in your *.Build.cs file (rename it to VaRest if you have it).

**Comment by Istauri** [comment]
I can confirm that 4.23 is working fine, attempting to open the project using 4.24 crashes the editor on startup.
Opening a fresh project on 4.24 works fine and enabling the plugin on a blank project on 4.24 also works.
Also VaRestPlugin is not in the *.Build.cs file

**Comment by ufna** [comment]
Could you launch the editor via MSVS debug? I need to know exact place of crash

**Comment by Istauri** [comment]
If I open the editor via visual studio it loads up fine but on opening the project it stops outputting with: `The program '[5136] UE4Editor.exe' has exited with code 0 (0x0).` Which is what you'd expect I think.

The project then crashes before startup and spits out a crash report:
[CCWP4MappingVR.log](https://github.com/ufna/VaRest/files/4313280/CCWP4MappingVR.log)

**Comment by Istauri** [comment]
Opening it in vanilla 4.24.3 results in a crash with a similar report

[CCWP4MappingVR.log](https://github.com/ufna/VaRest/files/4313304/CCWP4MappingVR.log)

**Comment by ufna** [comment]
Please launch the project from Visual Studio with F5 and show a breakpoint once crash happened.

**Comment by Istauri** [comment]
The project is a blueprint project with no Visual Studio solution/files, should I try and generate some?

**Comment by Istauri** [comment]
I opened the project in 4.23 and added a blank c++ actor to generate project files. I then set the project to reopen in 4.24 and edited the .uproject plugin name from VaRestPlugin to VaRest and ran the project from visual studio. This is the result:
![image](https://user-images.githubusercontent.com/57913181/76333650-d3e31c80-62e9-11ea-9a8d-3a99e291c7ce.png)

**Comment by ufna** [comment]
Could you send me this test project please? I'll check it in details.

**Comment by Istauri** [comment]
Unfortunately I'm unable to send you that project in particular as it contains research data, I tried creating a test project to reproduce the issue but found it difficult to reproduce.

In the end I removed all references to VaRestEditor from the gamestate and that allowed the project to finally open in 4.24

From what I can tell, nodes that use VaRest Request JSON data types that were created in 4.23 seemed to crash the project as well as ConstructJsonRequest

I have to rebuild the gamestate blueprint but the project is now thankfully running in 4.24

**Comment by ufna** [comment]
Yep, it was hard update to subsystems approach, and it's still in progress (some cases are still WIP). But it's part of big refactoring, so in result VaRest should became much more clear and shiny :)

Glad you solved the issue, and thanks for feedback!
