### ISSUE TITLE
Example get request for 4.24.?

### ISSUE THREAD

**Issue by damianward1972** [ufna/VaRest#283]
I can’t seem to get any of the YouTube examples working in 4.24 does anyone have a working blueprint image / screenshot they can share.?

Thanks

**Comment by trdwll** [comment]
Something like this should work just fine. 
![image](https://user-images.githubusercontent.com/11054333/76039778-70d53c80-5f1b-11ea-86e6-410012568caa.png)

**Comment by tetuje** [comment]
![Screenshot 2020-03-06 at 13 28 20](https://user-images.githubusercontent.com/1509070/76083653-64e68a80-5fae-11ea-8e8d-26986c93b21f.png)

It doesn't work from an Object BP?

**Comment by trdwll** [comment]
@tetuje What class are you trying to call this from?

**Comment by tetuje** [comment]
Object class

**Comment by trdwll** [comment]
So a quick fix, for now, could be passing VaRestSubsystem as an argument like so. 

![image](https://user-images.githubusercontent.com/11054333/76118806-193add80-5fbc-11ea-8fb9-c946c52a8eb8.png)

As for a permanent fix, I'm not entirely sure. Maybe @ufna has an idea.

**Comment by ufna** [comment]
@tetuje it's an issue of subsystems design for now. I'm not sure why `WorldContext` is hidden by Epics for this case, but current solution is nice as provided by @trdwll . 

I don't want to make temp solution with static getter in VaRest itself for now, it will be very dangerous for memory corruption in some cases.

**Comment by damianward1972** [comment]
> Something like this should work just fine.
> ![image](https://user-images.githubusercontent.com/11054333/76040041-38822e00-5f1c-11ea-87de-51fa591eea9e.png)
> 
> Update: Posted the wrong screenshot. lol

That's awesome.. many thanks it really helped me out cheers :)

**Comment by tetuje** [comment]
> So a quick fix, for now, could be passing VaRestSubsystem as an argument like so.
> 
> ![image](https://user-images.githubusercontent.com/11054333/76118806-193add80-5fbc-11ea-8fb9-c946c52a8eb8.png)
> 
> As for a permanent fix, I'm not entirely sure. Maybe @ufna has an idea.

I was trying this approach however UE4 can't find Va Rest Subsystem Object Reference as possible inputs for a Custom Event. Did I miss anything?

Thanks.

![Screenshot 2020-03-17 at 00 20 07](https://user-images.githubusercontent.com/1509070/76807612-3bff9a00-67e5-11ea-9c20-ac8f4d026522.png)

**Comment by trdwll** [comment]
@tetuje I believe it was Object. You can just drag from Target and into the new event and it'll add it automatically for you. 😄
