### ISSUE TITLE
Unable to generate/Build

### ISSUE THREAD

**Issue by pascalf1309** [ufna/VaRest#284]
I seem to get this whenever I try to build my CPP Unreal project

ERROR: Unable to instantiate module 'UnrealEd': Unable to instantiate UnrealEd module for non-editor targets. (referenced via Target -> VaRestEditorPlugin.Build.cs -> AssetTools.Build.cs)

**Comment by ufna** [comment]
@pascalf1309 , please check that you haven't `VaRestEditor` mentioned in your *.Target.cs file.

**Comment by pascalf1309** [comment]
that doesn't appear to be the issue. I tried switching to UE4.23 in case that might help... and it got me this error here instead(might provide some more insight on whats going on since its a different error.

**Comment by ufna** [comment]
@pascalf1309 please try updated version. If no, feel free to reopen the issue
