### ISSUE TITLE
Problem building APK with Varest Plugin in Unreal 4.23

### ISSUE THREAD

**Issue by swaraadam** [ufna/VaRest#285]
Hi every one, 
I'm using unreal engine 4.23.1, and VaREST-1.1-r26_4.23
![image](https://user-images.githubusercontent.com/15243729/76292272-de9db180-62e9-11ea-9855-b1acf4b7833a.png)

always got that error when building to the APK
if using marketplace version, I can build it but when opening it on android device this problem happens

![photo6287362037629692422](https://user-images.githubusercontent.com/15243729/76292392-19074e80-62ea-11ea-947f-23c8c44f0545.jpg)

I've read issue #178 . try to covert the graph from File>>developer>>generate native code. but the error still comes T_T

thanks, anyone for help. I appreciate it

**Comment by swaraadam** [comment]
I've tried to build with this way too, [https://allarsblog.com/2015/11/05/converting-bp-project-to-cpp/](url) . but I still got the same error

**Comment by ufna** [comment]
Hi @swaraadam ,

Please cherry pick the https://github.com/ufna/VaRest/commit/fd6feb5bec56a7677df7c236853702a4265734ee , it will fix your issue. It happens because Playfab plugin has some parts of VaRest inside, so some stuff is duplicated and conflicts in Android build.

**Comment by swaraadam** [comment]
thank for the response @ufna , but I dunno what to do with it

![image](https://user-images.githubusercontent.com/15243729/76400186-d95c6780-63ba-11ea-8ed9-2aef6e6a6e2a.png)
does it mean I must be download from that version and put it to the plugin folder?
but I got that warning when I did and the editor cant read the plugin.

do I have to do something first to make it look like a release version?

**Comment by swaraadam** [comment]
yay finally got it, VaRest has the same function name too in VaRestJsonValue file. so I need to change its name too. thanks a lot, @ufna . have a nice day

**Comment by ufna** [comment]
Hi @swaraadam , 

Glad you solved it! :)
