### ISSUE TITLE
using VaRest-1.1-r26_4.23.zip in UE4.23.1 Crash

### ISSUE THREAD

**Issue by Jackyuan999** [ufna/VaRest#288]
My UE Version: 4.23.1-9631420+++UE4+Release-4.23, when I use  VaRest-1.1-r26_4.23.zip in my project and call "CallUrl" function , the APP crashed in my iPhone after packaging, but it didnot crash in UE editor when I tested it on PC. I found this: "EngineVersion" : "4.23.0"  in the .uplugin file. Does this mean that I must use UE version 4.23.0 exactly? thanks a lot.

**Comment by ufna** [comment]
Hi @Jackyuan999 ,

Is it a crash on launch, or something like "after 30 secs"? What's in a crash logs?
