### ISSUE TITLE
Package Plugin Error

### ISSUE THREAD

**Issue by Jackyuan999** [ufna/VaRest#289]
when I package this plugin using Package tool in plugin menu in UE4.23.1 , there are many compiling errors in the log file, please help analyze these errors ,thanks a lot! . My plugin version:  VaRest-1.1-r26_4.23. 
![tool](https://user-images.githubusercontent.com/7939663/77636318-e1a5cc80-6f8e-11ea-9626-8aa49a8118ce.png)

[errorlog.txt](https://github.com/ufna/VaRest/files/4386515/errorlog.txt)

**Comment by ufna** [comment]
Hi @Jackyuan999 ,

Please use version from 4.23 branch: https://github.com/ufna/VaRest/tree/4.23 . I've just checked it and it works as it should.
