### ISSUE TITLE
UE4 will crash when create more than one HTTP Request?

### ISSUE THREAD

**Issue by alonezhby** [ufna/VaRest#291]
Hi, I created three BPs(BP_A, BP_B, BP_C), each one BP has a Va Rest Quest JSON Object to request different data from two URL. When I start to Play, after few seconds UE4 Crashed.

PS: BP_C has 10 more instanced actors in the level, each actor will use a base url with different parameters. BP_A and BP_B only has one instance in the level,

And get some error logs:
LogVaRest: UVaRestRequestJSON::ProcessRequest(346): Request (urlencoded): GET http://localhost:9080/Dec/Getdatas_A.php (check bExtendedLog for additional data)
LogHttp: Warning: Failed to add easy handle 000002505D56A0C0 to multi handle with code 7
LogHttp: Warning: 0000025060055440: request failed, libcurl multi error: 7 (The easy handle is already added to a multi handle)

When I let only one BP to run the Quest, UE4 work well, and not crash.

What I need to do to let two BP(Request) work same time?

Thanks!

**Comment by ufna** [comment]
Hi @alonezhby ,

There is no such limitations in VaRest. Please show how exactly you have request call implemented.

**Comment by alonezhby** [comment]
Hi, @ufna , thanks for your replay.
Here is call detail, three BPs are the same, the difference is BP_C has been  instanced 10 more times in the level, each instance will use a base url with different parameters.
![Request_Detail](https://user-images.githubusercontent.com/4462109/77822864-819b5b80-7131-11ea-8068-a9a88fb8cedb.png)

**Comment by ufna** [comment]
As I can see, you're calling `Execute Process Request` multiple times, and also it happens countless times after first one finished. It's the issue.

**Comment by alonezhby** [comment]
Oh... Really sorry, after `Execute Process Request`, it should be `Request processed`, I'll try again.
Thanks!

**Comment by alonezhby** [comment]
Just checked, I made a mistake in this BP, other two BP is right. And it's all ok now.
Really thanks!

**Comment by alonezhby** [comment]
Btw, I found another issue: 
if the 10 instanced actor's request all have connection failed(Connection timed out), it will  affect connection success actor's response time(about 10s later get the response data, e.g: I change connection success actor's data  in database, ue4 will get the result after about 10s later ).

If all request's connection success,  I do same thing: change data in databse, UE4 will get the result immediately. 

How to keep the request success actor's respone time not after by request failed actor?
Thanks.!

**Comment by ufna** [comment]
You should check the logic you're using, because all requests are independent. They are not connected internally and doesn't affect each other directly.

**Comment by ufna** [comment]
Closing the topic as issue resolved
