### ISSUE TITLE
Crash in iPhone6plus iOS 12.4.5

### ISSUE THREAD

**Issue by Jackyuan999** [ufna/VaRest#292]
when using Project Launcher to install app to my iPhone6plus, build OK,  but when running on my mobile, after display the app logo , it crashed. I use VaRest plugin when level is initiated. thanks a lot. And if I remove CallUrl function, it won't crash.
![tool2](https://user-images.githubusercontent.com/7939663/77876086-950b0b80-7284-11ea-8b7f-74111f08a617.png)
![useway](https://user-images.githubusercontent.com/7939663/77876174-d0a5d580-7284-11ea-8af8-af08f1fbb8f6.png)
[errolog0330.txt](https://github.com/ufna/VaRest/files/4400871/errolog0330.txt)

**Comment by ufna** [comment]
Hi, crashlogs are necessary, can't say nothing without it. But also you can try to use full-specified https url, it could help, e.g. https://google.com
