### ISSUE TITLE
"Make Json" node can't be nativized

### ISSUE THREAD

**Issue by louga31** [ufna/VaRest#293]
When the engine tries to nativize the "Make JSON" node, it creates this kind of C++ code
`b0l__VaRest_MakeJson_Target__pf = UVaRestSubsystem::ConstructVaRestJsonObject();`
This code doesn't compile because it calls a non-static function.

This issue prevent nativization of any blueprint that use the "Make JSON" node

I'm using the 4.25 branch

**Comment by ufna** [comment]
```
void ANewBlueprint_C__pf1010915279::bpf__ExecuteUbergraph_NewBlueprint__pf_1(int32 bpp__EntryPoint__pf)
{
	UVaRestSubsystem* bpfv__CallFunc_GetEngineSubsystem_ReturnValue__pf{};
	check(bpp__EntryPoint__pf == 8);
	// optimized KCST_UnconditionalGoto
	b0l__VaRest_MakeJson_Target__pf = UVaRestSubsystem::ConstructVaRestJsonObject();
	if(::IsValid(b0l__VaRest_MakeJson_Target__pf))
	{
		b0l__VaRest_MakeJson_Target__pf->UVaRestJsonObject::SetStringField(FString(TEXT("111")), FString(TEXT("243")));
	}
```

**Comment by ufna** [comment]
@louga31 ,

fixed now, I'll update it on the Marketplace too soon.

**Comment by louga31** [comment]
Thanks
