### ISSUE TITLE
Failed to load plugin when using projectLauncher

### ISSUE THREAD

**Issue by Jackyuan999** [ufna/VaRest#294]
"Cannot find module "VaRestPlugin" so the plugin "VaRestPlugin" failed to load. Please make sure the plugin is installed correctly, otherwise please consider disabling this plugin in the project." I use Project Launcher to install my app to iPhone6P, but got this error. Please help me , thanks a lot.

**Comment by ufna** [comment]
What plugin version u're using?

**Comment by Jackyuan999** [comment]
VaRest v1.1-r26 [UE 4.23]

**Comment by ufna** [comment]
Got it. Please find any `VaRestPlugin` usages in your config and *.build.cs files and change it not VaRest.

**Comment by Jackyuan999** [comment]
I didn't get it, could you give some detailed information? 
you mean change these 2 files? they are located in my project plugin dir /VaRestPlugin, how to change it?
/Config/FilterPlugin.ini:
[FilterPlugin]
; This section lists additional files which will be packaged along with your plugin. Paths should be listed relative to the root plugin directory, and
; may include "...", "*", and "?" wildcards to match directories, files, and individual characters respectively.
;
; Examples:
;    /README.txt
;    /Extras/...
;    /Binaries/ThirdParty/*.dll
==========================
the other is \Plugins\VaRestPlugin\Source\VaRestPlugin\VaRestPlugin.Build.cs
// Copyright 2014-2018 Vladimir Alyamkin. All Rights Reserved.

using System.IO;

namespace UnrealBuildTool.Rules
{
	public class VaRestPlugin : ModuleRules
	{
		public VaRestPlugin(ReadOnlyTargetRules Target) : base(Target)
		{
			PCHUsage = PCHUsageMode.UseExplicitOrSharedPCHs;

			PrivateIncludePaths.AddRange(
				new string[] {
					"VaRestPlugin/Private",
					// ... add other private include paths required here ...
				});

			PublicDependencyModuleNames.AddRange(
				new string[]
				{
					"Core",
					"CoreUObject",
					"Engine",
					"HTTP",
					"Json"
					// ... add other public dependencies that you statically link with here ...
				});
		}
	}
}

**Comment by ufna** [comment]
Is your project BP-only?

**Comment by Jackyuan999** [comment]
yes

**Comment by 1TrueDeveloper** [comment]
@ufna Hi! I have the same issue. I installed varest into the source engine (moved the source varest available on github to /engine/plugins) and when building the project (development), it builds the project fine, but when I try to launch the server .exe, it loads stuff into command line and then says: 

"Cannot find module "VaRestPlugin" so the plugin "VaRestPlugin" failed to load. Please make sure the plugin is installed correctly, otherwise....” 

Not an experienced programmer or so, but since the varestplugin only has to be in /engine/plugins, and not the root project /plugin folder, why does it say that issue?

**Comment by ufna** [comment]
@Jackyuan999 , I'll test Marketplace version tomorrow. You're using vanilla UE4.23 from the Launcher and bp-only project, right?

**Comment by ufna** [comment]
@1TrueDeveloper , it's not the way plugin should work. You have two basic options:
1. Use binary engine distribution and plugin from Marketplace. It's pre-compiled and will work as it should.
2. Custom engine.
2.1. Installed custom engine with plugins inside. It's a special way to build the engine. 
2.2. Custom engine with plugin indise the project.

In case 2.2. you should move VaRest to the <YourProject>/Plugins/ folder and rebuild the project. Only c++ based projects are supported in this case.

**Comment by 1TrueDeveloper** [comment]
@ufna So, for 2.2, I have to move the plugin to the ProjectFolder/Plugins and then add a c++ class to the project and rebuild? Also if yes, does varestplugin still have to be in engine/plugins folder?

**Comment by ufna** [comment]
> @ufna So, for 2.2, I have to move the plugin to the ProjectFolder/Plugins and then add a c++ class to the project and rebuild? Also if yes, does varestplugin still have to be in engine/plugins folder?

No, you should remove plugin from the engine in this case

**Comment by 1TrueDeveloper** [comment]
@ufna I removed it from the engine. I downloaded the Varestplugin from Github, and put it into project/plugins. It at least says it’s “installed” in plugins tab in the project. The project builds fine, no issues. Though, same issue, when trying to launch server with command -log, it says that same issue “Cannot find module...”

I added a c++ class, too, just to make sure. 

The Varest which is in project/plugins isn’t from the marketplace though. Is that the issue? Or is the marketplace version “only” for binary engine and not source?
A bit unsure of what I should do.

**Comment by Jackyuan999** [comment]
> 
> 
> @Jackyuan999 , I'll test Marketplace version tomorrow. You're using vanilla UE4.23 from the Launcher and bp-only project, right?

Version: 4.23.1-9631420+++UE4+Release-4.23

**Comment by Jackyuan999** [comment]
> 
> 
> @Jackyuan999 , I'll test Marketplace version tomorrow. You're using vanilla UE4.23 from the Launcher and bp-only project, right?

BP-Only

**Comment by Jackyuan999** [comment]
UE4 Version: 4.23.1-9631420+++UE4+Release-4.23, BP-Only project, I 've made another test, that is: delete \plugin\VaRestPlugin under my project dir,  then install VaRest from UE marketplace, 
![图片](https://user-images.githubusercontent.com/7939663/79531303-7f7b4b80-80a4-11ea-9554-ac547c5eab6a.png)

then firstly use projectLauncher to install app to my iPhone6P, but got this error: 
![图片](https://user-images.githubusercontent.com/7939663/79530856-2eb72300-80a3-11ea-8988-a3c389a16d54.png)
![图片](https://user-images.githubusercontent.com/7939663/79530906-55755980-80a3-11ea-9cae-dc6a34159f96.png)
,then I used packageProject tool to make iOS(ipa) file (Build Config:shipping) and got this error:
 
![图片](https://user-images.githubusercontent.com/7939663/79545062-a6487a80-80c2-11ea-9ede-9f9c764cd9b7.png)
but if  Build Config=Development, will build successfully.

**Comment by Jackyuan999** [comment]
Any update? Thanks a lot. Should I upgrade to UE4.24 ?  
the Plugin from Marketplace works fine in development version in UE4.23.1

**Comment by ufna** [comment]
It seemed to be smth marketplace-related issue, because plugin is distributed in pre-compiled version in this case. Please try to disable bitcode encoding and try again.

**Comment by Jackyuan999** [comment]
As you said, it works in shipping mode now, thank you very much.

**Comment by ufna** [comment]
Great you solved it! :)
