### ISSUE TITLE
Get VaRestSubsystem requires specified class ?

### ISSUE THREAD

**Issue by erpy** [ufna/VaRest#296]
I bumped into this by using the latest for UE4.24:
![image](https://user-images.githubusercontent.com/734976/79562657-b1dc7700-80ab-11ea-8274-b9dcac879e10.png)

I guess it wants a context for VaRestSubsystem... which is *the* context.... ?!
Thanks!

**Comment by erpy** [comment]
In theory, if the subsystem is tied to a specific context, shouldn't I be able to provide it through a pin connection ?
https://docs.unrealengine.com/en-US/Programming/Subsystems/index.html

**Comment by erpy** [comment]
Ok, so, it looks like an "update" issue, where "refresh all nodes" isn't sufficient. Although all the target classes are apparently the same, rebuilding the network won't complain anymore:

![image](https://user-images.githubusercontent.com/734976/79564782-95423e00-80af-11ea-9da2-7501f3991579.png)

...please have a look as this might affect transitioning to the new version.
Thanks!

**Comment by erpy** [comment]
It does affect possibly all static functions in the Subsystem:

![image](https://user-images.githubusercontent.com/734976/79565240-9c1d8080-80b0-11ea-970b-159c396cf6e5.png)

**Comment by ufna** [comment]
Hi @erpy ,

It's not a bug, it's a feature :) I've changed substystem from GI to the Engine one, so in BP's it has to be re-created.

**Comment by erpy** [comment]
> Hi @erpy ,
> 
> It's not a bug, it's a feature :) I've changed substystem from GI to the Engine one, so in BP's it has to be re-created.

Ok, what's the benefit ?
If I have to re-make the nodes, there must be a good reason. :)

**Comment by ufna** [comment]
> Ok, what's the benefit ?
> If I have to re-make the nodes, there must be a good reason. :)

Now requests can be used in UObjects and at design time :) (construction, etc)
