### ISSUE TITLE
update problem, 

### ISSUE THREAD

**Issue by vrpsytech** [ufna/VaRest#297]
when i update plugin to 4.24 from 4.22 nothing is working anymore
[blueprint](http://lexyco.net/wp-content/uploads/2020/04/Bp_GameInstance-4_18_2020-2_25_59-PM.png)
i dont khow what to do, i cant find construct va rest request ext

**Comment by vrpsytech** [comment]
I found the solution, sorry for adding issue
[solution](https://gyazo.com/14ce219eb763b66923b4782fc4b9372e)

**Comment by vrpsytech** [comment]
I found the solution, sorry for adding issue
[solution](https://gyazo.com/14ce219eb763b66923b4782fc4b9372e)

**Comment by ufna** [comment]
@vrpsytech , glad you solved, np!
