### ISSUE TITLE
failed VaRest!UVaRestLibrary::execBase64Decode()

### ISSUE THREAD

**Issue by vrpsytech** [ufna/VaRest#299]
when i try to play the game, ue4 will crash, and i get this error
UE4Editor_VaRest!UVaRestLibrary::execBase64Decode() [C:\Lexy\UE Projects\vrpsytech\Plugins\VaRest\Source\VaRest\Public\VaRestLibrary.h:20]
[complete log file](http://lexyco.net/wp-content/uploads/2020/04/UE4CC-Windows.zip)

**Comment by vrpsytech** [comment]
this happened when I use base64enocde and decode, when i dont use these 2 function, every thing works properly, other varest functions work properly

**Comment by ufna** [comment]
Hi @vrpsytech ,

It was fixed few weeks ago, please update plugin to the latest version. Which one you're using exactly?

**Comment by vrpsytech** [comment]
im on the develop branch, and im using version 1.1-r29.2

**Comment by ufna** [comment]
@vrpsytech , hm, it's strange. Could you please provide example of data you're decoding?

**Comment by vrpsytech** [comment]
when I encode, nothing happens
but when i use decode function, even if i left the source input blank and decode nothing, still my ue4 crash
i have for loop , that i encode 15 strings, but one of them was empty sometimes, 
so when it tries decode nothing it will crash, 
but i using this code for two year now, and i never had problem

**Comment by vrpsytech** [comment]
oh i have problem
please take a look at this
i encode string "Sondos", but when i decode it i get "Sondos翸"
Input Text: Sondos
Encoded: U29uZG9z
Decoded: Sondos翸
[BP](http://lexyco.net/wp-content/uploads/2020/04/VRPsyTech-Unreal-Editor-4_22_2020-10_47_32-AM.png)

**Comment by ufna** [comment]
![image](https://user-images.githubusercontent.com/271578/79970579-c948a500-849b-11ea-907d-76cf1de610d9.png)

reproduced, will be fixed asap

**Comment by ufna** [comment]
@vrpsytech , fixed at develop now

**Comment by vrpsytech** [comment]
ty for the support and amazing plugin

**Comment by ufna** [comment]
you're welcome! :)
