### ISSUE TITLE
Add support for array of different types

### ISSUE THREAD

**Issue by ufna** [ufna/VaRest#3]
I'll add blueprintable json value, and GetArray() function will return the array of this values. Each value can be casted to number/string/etc.

Get Type function should return enum to make switch simple.

Get Type Str should exist too.

Example:

``` json
{ 
   "pawns":[ 
      { 
         "key1":"value1", 
         "key2":"value2", 
         "key3":{ 
            "key4":"value4", 
            "key5":"value5" 
         } 
      }, 
      { 
         "key1":"value1", 
         "key2":"value2", 
         "key3":{ 
            "key4":"value4", 
            "key5":"value5" 
         } 
      } 
   ] 
}  
```

**Comment by davidwieler** [comment]
Would be nice is there were some examples on how to use these things.....
