### ISSUE TITLE
GET - Json not working in 4.8?

### ISSUE THREAD

**Issue by brunogbrito** [ufna/VaRest#30]
I can't get server communication using Construct Json Request with this config: 
Verb GET 
Content Type : Json 

It does work with x www form urlencoded. POST also working.

**Comment by ufna** [comment]
It works, but you need to update the plugin from develop branch. I'll make an release update in two days also.

**Comment by brunogbrito** [comment]
Nice, I will give a try.

Thank you Vladimir :)

Best Regards,

Bruno Brito

2015-06-23 8:37 GMT-03:00 Vladimir Alyamkin <notifications@github.com>:

**Comment by brunogbrito** [comment]
Hi Vladmir :)

I waited for 4.8.2 to give a new try, but I have no idea why GET still no works for me when using as Json content Type. I'm using PUT instead. POST also works fine. I putted the plugin in the game project folder, should I change to the engine folder?  In 4.7.6 works fine tho.

1 min video showing the BP.
http://youtu.be/BMJiketaQ3Y

any word u share will help ;)
Best Regards,

Bruno Brito

**Comment by minw1208** [comment]
hi bruno i'm beginner developer please help me ! 

how to install VaRest plugin 4.7.6 ver. ? i'm occur error message "  
![recompile](https://cloud.githubusercontent.com/assets/11851321/8982246/4bb9f718-36fa-11e5-84e1-38c4ce8bc61b.png)

how to solve it? please help me !
