### ISSUE TITLE
GetMethod Get Data by BearToken 

### ISSUE THREAD

**Issue by LuoShiLiang** [ufna/VaRest#301]
![Postman Setting](https://user-images.githubusercontent.com/31683509/80297299-767d2f00-87b4-11ea-8bc2-d69ed3a486c5.png)

Hello , how to Get data like the postman settings in the picture?
BTW your Wonderful plugin help me a lot ，thx my bro.

**Comment by LuoShiLiang** [comment]
Ok, i finally solve it .

Append "Bear "  and the token string value 
set header  "Header Name"="Authorization ", "Header Value=Appended String"

**Comment by ufna** [comment]
@LuoShiLiang , you're competely right! Glad you solved it! :)

**Comment by ssshammi** [comment]
Hi append bear where ? not getting it. can you show example

**Comment by eusru** [comment]
> Hi append bear where ? not getting it. can you show example

### 

[https://github.com/eusru/imageBed/issues/4#issue-1171814147](url)

**Comment by chase03** [comment]
@eusru  

> Ok, i finally solve it .
> 
> Append "Bear " and the token string value set header "Header Name"="Authorization ", "Header Value=Appended String"

Hello. Could you share your full Blueprint about Set Header, please?  Thanks.

**Comment by eusru** [comment]
> 
this is the bp,check it~
https://github.com/eusru/imageBed/issues/4#issue-1171814147
