### ISSUE TITLE
Various functions of VaRest not found in BP

### ISSUE THREAD

**Issue by mbpictures** [ufna/VaRest#307]
Hi!

I have an problem after updating my project from UE4.24 to UE4.25 and updating VaRest to version 30:
`LogBlueprint: Error: [Compiler EndlessFly_GI] Could not find a function named "LoadJsonFromFile" in 'VaRestLibrary'.
Make sure 'VaRestLibrary' has been compiled for  Load Json from File`

I can find the declaration and the implementation of your plugin, but in BP context menu, there are only a few Functions left:
![image](https://user-images.githubusercontent.com/2772553/82678951-ca135900-9c4a-11ea-8073-0b0fc8df88c1.png)

I'm on windows 10 and have several plugins installed: PlayFab (which has actual the same function names for all the 'construct ... json' functions, but that should be fine when they are in a different namespace and bp category?), SmoothSync,...

Do you know how to fix the issue? I deleted all Binaries/Intermediate folders and recompiled from source, but nothing helped...

Thank you already and best wishes! :)

EDIT:
I updated from VaRest version 27

**Comment by ufna** [comment]
Hi @mbpictures ,

Now it's part of VaRest Subsystem:

![image](https://user-images.githubusercontent.com/271578/82693207-c5aa6880-9c69-11ea-8947-6c7c267b9a10.png)

**Comment by mbpictures** [comment]
Thx! :) Maybe you can update the readme to help others, who are struggling too.
