### ISSUE TITLE
Problem with POST request to Google Script API

### ISSUE THREAD

**Issue by kubalobo** [ufna/VaRest#308]
Hi!
I have problem with receiving response from POST request to the google script webapp (https://developers.google.com/apps-script/guides/web)

![image](https://user-images.githubusercontent.com/3520560/83947166-b6a0ea00-a815-11ea-95dd-0d5865acbe72.png)

It appears that the response from google is sended with additional redirection (302 response) and VaRest is not able to handle that. Here is similar problem but connected with Unity.
http://inter-illusion.com/forum/i2-localization/963-send-failed-since-rewinding-of-the-data-stream#2611

My VaRest use:
![image](https://user-images.githubusercontent.com/3520560/83947277-52325a80-a816-11ea-9bee-cb53475972f7.png)

You can use my google script link for debugging - it should send back all information in response for both - GET and POST.
https://script.google.com/macros/s/AKfycbwYjq3pmU0sNPqiGV1Rl_hmmJy1qe3LclAlw19I/exec
It is working in tester: https://resttesttest.com/

Do you have any solution for that? 
Thanks in advance! Fantastic plugin by the way! 😄

**Comment by ufna** [comment]
Hi @kubalobo ,

Unfortunately, it's the issue of the build-in cURL itself. Can't make anything with it at plugin level, you need to patch the engine to handle 302 response :(
