### ISSUE TITLE
CallUrl Error: Is Valid Json Response = false

### ISSUE THREAD

**Issue by Jackyuan999** [ufna/VaRest#309]
UE4.23.1 , installed VaRest plugin from UE market, worked fine 1 month ago, but when I test it again today ,   Is Valid Json Response = false ,
![图片](https://user-images.githubusercontent.com/7939663/84245864-486f6680-ab38-11ea-95d0-4e9cee8503a5.png)
to check easily and clearly , I made a very simple php file:
<?php
        echo json_encode(array("result"=>"network_OK"));
 ?> 
![图片](https://user-images.githubusercontent.com/7939663/84246842-c41de300-ab39-11ea-98e8-24e8e356cba9.png)
and tested it in explorer , it worked:
![图片](https://user-images.githubusercontent.com/7939663/84246158-c469ae80-ab38-11ea-89a2-97d790cf2c21.png)
obviously the result is json data format. so what's the problem? thanks a lot .

**Comment by Jackyuan999** [comment]
What does endpoint mean? sorry  , could you give me more info?
[MyProject6.zip](https://github.com/ufna/VaRest/files/4762340/MyProject6.zip)
this is my testing project, I found VaRest Plugin was updated in  my UE4.23.1, after testing again ,still not work.
![图片](https://user-images.githubusercontent.com/7939663/84340290-f2033600-abd2-11ea-866c-cf0c6308f36f.png)

**Comment by Jackyuan999** [comment]
endpoint: https://www.eosbet.net/test1.php  
this ?

**Comment by ufna** [comment]
I've checked it, you have invalid http response:

`invalid HTTP response code received. URL: https://www.eosbet.net/test1.php, HTTP code: 0, content length: 0, actual payload size: 0`

I'm not familiar with PHP, but you should check you backend to response with 200 code.

**Comment by Jackyuan999** [comment]
It's server's problem, thank you very much.

**Comment by ufna** [comment]
You're welcome!
