### ISSUE TITLE
Cannot Execute Process GET Request with Set String Array Field for Request Content 

### ISSUE THREAD

**Issue by DhimasRNG** [ufna/VaRest#312]
Somehow I can't execute process GET request with string array in content. Not getting any response.
my API tested with Postman and works fine. I get response and everything.

I'm using marketplace version

Here's my blueprint
![1](https://user-images.githubusercontent.com/64202644/85136388-c1259f80-b269-11ea-84f9-3f5538a83f44.PNG)

![2](https://user-images.githubusercontent.com/64202644/85136401-c551bd00-b269-11ea-87c4-e9b8719984f6.PNG)

![3](https://user-images.githubusercontent.com/64202644/85136410-c8e54400-b269-11ea-99f7-f74217bef411.PNG)

Thanks in advance :)

**Comment by ufna** [comment]
Hi @DhimasRNG ,

You should set content type with SetContentType function. Currently your request is not json one :)

**Comment by DhimasRNG** [comment]
Hi @ufna 
Thanks for your quick response.

I tried, and still won't work. 
![image](https://user-images.githubusercontent.com/64202644/85194453-e234d180-b2f7-11ea-8cc4-b87638334de2.png)

I'm using cloudwatch amazon, the request is not even recorded to the GET event.

Anyway, if I make POST method API for the same url, it works with your plugin.
both Method tested in postman works.
![image](https://user-images.githubusercontent.com/64202644/85194796-920a3f00-b2f8-11ea-9f22-16cbf99bbe2f.png)

Regards :)

**Comment by ufna** [comment]
Using GET with request content is not right by HTTP/1.1 standart, check https://stackoverflow.com/a/15656884 for details.

Some modern clients supported this feature, but the engine is not.

**Comment by DhimasRNG** [comment]
Ah I see, thanks a lot :)
