### ISSUE TITLE
iOS Packaging error in BP&C++ project 

### ISSUE THREAD

**Issue by Jackyuan999** [ufna/VaRest#313]
UE4.23.1,  BP&C++ mixed project, using VaRest plugin source code, and a new C++ class in the project . Running in editor and packaging Android are all OK ,but when trying to package iOS, got an error: 
ERROR: Not expecting project /Users/86185/UE4/Builds/DESKTOP-N5JLND9/D/EpicWork/MyProject5/Intermediate/ProjectFilesIOS/MyProject5.xcodeproj to already have a target rules of with configuration name Game (MyProject5Target) while trying to add: MyProject5Target
 so Can't I compile source code using remote Mac ? Thank you very much!

**Comment by ufna** [comment]
Hi @Jackyuan999 ,

I'm definitely sure that it has nothing with VaRest itself. Remote compilation works with plugin as it should.

**Comment by Jackyuan999** [comment]
OK, I'll check again. Thanks !
