### ISSUE TITLE
4.25.2 build failure

### ISSUE THREAD

**Issue by mclark4386** [ufna/VaRest#314]
With 4.25.2 I'm having issues getting my project to package. So I did a fresh pull on the repo and tried to load the the project and can't (project wont rebuild). I have make sure that the plugin is installed in the engine, but am getting this error when I try to load or build the project:
`
ERROR: Expecting to find a type to be declared in a module rules named 'VaRest' in UE4Rules, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null. This type must derive from the 'ModuleRules' type defined by Unreal Build Tool.`

I had a working project in 4.24.6 and everything was good, and then I moved to 2.25.1 and everything was fine. I'm running on a Mac if that changes anything.

Any Ideas?

**Comment by mclark4386** [comment]
So moving the Plugin in to the project at least got the project to rebuild again. Testing the packaging now...

**Comment by mclark4386** [comment]
Packaging is working as expect now as well... any idea why this was an issue?

**Comment by ufna** [comment]
Hi @mclark4386 ,

Unfortunately it's a critical bug of 4.25.2 update. Please check https://forums.unrealengine.com/unreal-engine/announcements-and-releases/1755531-unreal-engine-4-25-released?p=1792437#post1792437 for temporary solution
