### ISSUE TITLE
UE4.25.3 GitHubOculusEngine Cannot package and plugin incompatible

### ISSUE THREAD

**Issue by Ra1n18** [ufna/VaRest#315]
cannot package project 
![Screenshot_14](https://user-images.githubusercontent.com/38788350/90039023-28465a00-dcd7-11ea-8d0f-808ce95b11d0.png)
![Screenshot_15](https://user-images.githubusercontent.com/38788350/90039198-5fb50680-dcd7-11ea-98e0-0ef6521af88f.png)

**Comment by tung22tcn** [comment]
Me too

**Comment by ufna** [comment]
I'm not familiar with OculuseEngine, please reopen with additional details if it's still actual.
