### ISSUE TITLE
Cant figure out how to post data to server

### ISSUE THREAD

**Issue by Adibiodo** [ufna/VaRest#316]
Hi,

i am having problems trying to send data to server. Getting works fine, only cant get it to post anything. 
I have a print after on request complete which prints, but the data does not change. 

Can you help me please?
![JSON_1](https://user-images.githubusercontent.com/61392896/93793988-d2e75c00-fc37-11ea-98e3-8b99cc1f0885.jpg)

**Comment by Adibiodo** [comment]
btw, its UE 4.25.3

**Comment by ufna** [comment]
Hi @Adibiodo ,

First please set LogVaRest log category to verbose and check what's in it. Is your server expects json-formatted POST data?

**Comment by Adibiodo** [comment]
Hi Ufna, 

thank you for your quick response. 
Indeed, on the UE4 side, everything works and the requests are getting through, i just didnt set the server right.

**Comment by ufna** [comment]
You're welcome :)
