### ISSUE TITLE
build error 4.26.0 preview

### ISSUE THREAD

**Issue by bmahlbrand** [ufna/VaRest#318]
Build fails for 4.26.0 preview due to the following error:

`Severity	Code	Description	Project	File	Line	Suppression State
Error	C2665	'TSharedRef<IHttpRequest,ESPMode::NotThreadSafe>::TSharedRef': none of the 3 overloads could convert all the argument types	$ue4project	C:\Users\$name\workspace\$ue4project- Copy\Plugins\VaRestPlugin\Source\VaRest\Public\VaRestRequestJSON.h	316	
`

**Comment by ufna** [comment]
Hi @bmahlbrand ,

Please use UE4.26 branch instead of develop one :)
