### ISSUE TITLE
Peer certificate cannot be authenticated with given CA certificates Issue

### ISSUE THREAD

**Issue by triadiclabs** [ufna/VaRest#319]
Hi there,

we have used Varest on a few projects and never had an issue when getting data
However, recently one of our projects cant seem to get data and returns Peer certificate cannot be authenticated with given CA certificates , when its trying to get it

Any help please?

**Comment by ufna** [comment]
Hi @triadiclabs ,

It's definitely an issue with the certificate (libcurl can't verify it for some reason), but you can always temporaty disable this check:

![image](https://user-images.githubusercontent.com/271578/97016362-4f31cf80-1555-11eb-8eb6-b07d7366d2df.png)
