### ISSUE TITLE
How to Recompile plugin (help me please)

### ISSUE THREAD

**Issue by minw1208** [ufna/VaRest#32]
hey guy, i need your help

I'm UE4 beginner developer, i was import VaRest plugin and restart my project 
But project is occur error message 

" engine version was different please recompile plugin" 

but i don't know recompile plugin and how to fix plugin version ! help me please !!

**Comment by ufna** [comment]
Do you use c++ based project, or blueprints only one?

**Comment by minw1208** [comment]
Oh that's my fault, Thanks Va ! i solved it! very very thanks you

**Comment by ufna** [comment]
@minw1208 you're welcome! ;)

**Comment by minw1208** [comment]
Thank you Va! If problems occur, i will again questions :)
