### ISSUE TITLE
Trying to generate app for HL2.

### ISSUE THREAD

**Issue by zejdma** [ufna/VaRest#320]
UATHelper: Packaging (HoloLens):   Building using Windows SDK version 10.0.18362.0 for HoloLens
UATHelper: Packaging (HoloLens):   ERROR: Missing precompiled manifest for 'VaRest'. This module was most likely not flagged for being included in a precompiled build - set 'PrecompileForTargets = PrecompileTargetsType.Any;' in VaRest.build.cs to override.
UATHelper: Packaging (HoloLens): Took 2.108022s to run UnrealBuildTool.exe, ExitCode=6
UATHelper: Packaging (HoloLens): UnrealBuildTool failed. See log for more details. (C:\Users\Spatial Hub\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_4.25\UBT-MyProject-HoloLens-Development.txt)
UATHelper: Packaging (HoloLens): AutomationTool exiting with ExitCode=6 (6)
UATHelper: Packaging (HoloLens): BUILD FAILED
PackagingResults: Error: Missing precompiled manifest for 'VaRest'. This module was most likely not flagged for being included in a precompiled build - set 'PrecompileForTargets = PrecompileTargetsType.Any;' in VaRest.build.cs to override.
PackagingResults: Error: Unknown Error

**Comment by ufna** [comment]
Hi @zejdma ,

I'm not familiar with HoloLens. Are you using VaRest as a project-level plugin or engine one?

**Comment by zejdma** [comment]
Using VaRest from marketplace on engine 4.25.3. Generation on winx64 is succesfull.

**Comment by ufna** [comment]
There is no pre-compiled version of runtime plugins for HoloLens platform on the Marketplace. Easies way to fix it is to add the VaRest as a project-level plugin, and build the project then.

**Comment by zejdma** [comment]
Thanks for answers and your time spended on my problem. 

Did you mean that.. I shouldn't use plugin via plugins in UE editor and I must copy varest folder to Plugins folder in project folder and compile it? I dont know this terms like project-level plugin or engine plugin. 

I tryed to uninstal marketplace plugin and copy actual version of varest from git hub to Plugins directory in my project folder. After it I compiled it and packaged it for Hololens and it has no more error! But on hololens after run this program is just loading. :(

Did you mean I should try this solution what i described or I got it wrong?

**Comment by ufna** [comment]
Yes, you did it right way, and now we should deal with why "but on hololens after run this program is just loading" :) App crashes or just infinite loading happens?

**Comment by zejdma** [comment]
I tried more packaging of different type of my HL project and it seems that application works good, but functions from varest like callURL don't do anything. While I call callURL function at beginPlay application just loading infinitely. If U want I can send u my project.

**Comment by ufna** [comment]
It is works as it should being packaged for example as Win64  ?

**Comment by zejdma** [comment]
On Win64 works app well with VaRest functions. On HL2 works well without VaRest functions.

**Comment by ufna** [comment]
Please reopen if its still actual

**Comment by zejdma** [comment]
I dont work on the project already, but if there was some updates in VaRest, I can test old project if VaRest functions goes well.
