### ISSUE TITLE
Is there a way to retrieve a multiline text from a database?

### ISSUE THREAD

**Issue by pbiotech** [ufna/VaRest#322]
When I send a multi-line text from a Multi-Line Editable Text widget to a database it is saved as a multi-line text in a db cell. When I try to retrieve back this multi-line text it shows only empty curly brackets {} in the result with no any text, although in a web-browser it shows the usual response like this one: {"Field Name": "Multi-line text from the database cell",}. How can I get a multi-line text from a database using VaRest? I use php and an SQLite database.

**Comment by ufna** [comment]
Hi @pbiotech ,

I definitely need an example to fetch :)

**Comment by pbiotech** [comment]
Hi @ufna ,

Here is my example:
https://drive.google.com/file/d/1IIN_IateN0rQK6coabJI1WnaRJswXYbs/view?usp=sharing
The Send flow saves the text in the db as multi-line
https://drive.google.com/file/d/1fFmb8aN_F5WFvZ4TASuHfjWdAuZJPtf-/view?usp=sharing
When I try to get this text in the Get flow it shows the empty string, I tried Encode Json to Single String and Encode Json nodes, they both show the empty curly brackets {}.
However in the web-browser the php script shows this result
https://drive.google.com/file/d/1Ud8UhmzhojvjX4EaO2mOytlXrCStuPjm/view?usp=sharing
VaRest sends to a database a text as multiline, how can I get this multiline text back? Thanks

**Comment by ufna** [comment]
@pbiotech ,

`{"smth" : "smth else",}` is invalid json. You should remove trainling comma: `{"smth" : "smth else"}`

**Comment by pbiotech** [comment]
Thanks @ufna , I tried to remove comma, but that didn't work. I also had to add comma in the php script when there are several Fields in one request, like this one:
echo "{\n";
echo "\"Field Name 1\": \"Text from db\",\n";
echo "\"Field Name 2\": \"Text from db\",\n";
echo "\"Field Name 3\": \"Text from db\",\n";
echo "}\n";
and it worked.
