### ISSUE TITLE
ue4.26 keeps telling me i need to add from marketplace yet 4.26 is not supported there yet.

### ISSUE THREAD

**Issue by ARtSSt** [ufna/VaRest#325]
hello, i am having no luck upgrading my project from 4.25 to 4.26, I keep receiving an error that Varest doe not exist and I need to download from the market place. I have replaced the plugin in the plugins folder with the branch for 4.26 from your repo(as it is not in the Marketplace yet). Am I doing something wrong, could you update the installation instructions for 4.26 with more detail?

Thank you,

**Comment by ufna** [comment]
You should place the plugin into <YourProject>/Plugins/ folder and manually recompile it. Also, you should remove link to marketplace in YourProject.uproject file if it exists here.

**Comment by ARtSSt** [comment]
/it was the pointer to Marketplace in the Uproject settings, Thank you

**Comment by ufna** [comment]
@ARtSSt you're welcome! :)

**Comment by dtb49** [comment]
I also ran into this problem when I was upgrading my project. It seems the plugin name changed perhaps but, that could have been a while back. I am running a pretty old version lol So I had to modify the module name in the Build.cs also.
