### ISSUE TITLE
Create JsonObject from a SingleString?

### ISSUE THREAD

**Issue by hekut146** [ufna/VaRest#326]
Good afternoon, can you please tell me, can i create a JsonObject from a single string, (my task is - to save data in the database simpleString (JsonObject to singleString), load and recreate JsonObject based on the received data string (singleString to JsonObject))?

**Comment by Maxmystere** [comment]
`Decode Json ` should do the trick ?

**Comment by hekut146** [comment]
I try, don't work, or am I doing something wrong?
![image](https://user-images.githubusercontent.com/4464884/101838640-0dcfa080-3b52-11eb-8dc9-d4b54dbd0003.png)
![image](https://user-images.githubusercontent.com/4464884/101838663-16c07200-3b52-11eb-974f-1bd18516bd0e.png)

**Comment by Maxmystere** [comment]
You have to initialize newJson first

**Comment by Maxmystere** [comment]
![image](https://user-images.githubusercontent.com/24446198/101838968-d0631700-3b41-11eb-8866-6cbac4b5547e.png)

**Comment by hekut146** [comment]
![image](https://user-images.githubusercontent.com/4464884/101839029-b54cd300-3b52-11eb-994b-f25ef3835442.png)
Ohh, now work, thanks
