### ISSUE TITLE
Browser to blueprint request possibly?

### ISSUE THREAD

**Issue by hekut146** [ufna/VaRest#327]
Can I create a blueprint request handler that receives data from the browser, for example: a web form for entering the time and a button to apply to get the data into the blueprint?

**Comment by Maxmystere** [comment]
If you want to run a browser into UE you can check [this](https://docs.unrealengine.com/en-US/InteractiveExperiences/UMG/UserGuide/WidgetTypeReference/WebBrowser/index.html)
Or if you want to control UE from a web browser i guess you can look [here](https://docs.unrealengine.com/en-US/ProductionPipelines/ScriptingAndAutomation/WebControl/index.html)
Anyway whatever your request is i'm not sure VaRest is what you need

**Comment by hekut146** [comment]
But don't have Remote Control Web Interface plugin in 4.26 and 4.26.1... (node.js is installed)
