### ISSUE TITLE
Add installation guide for people using the engine built from source

### ISSUE THREAD

**Issue by Zenahr** [ufna/VaRest#329]
![image](https://user-images.githubusercontent.com/47085752/103146701-70798c80-474d-11eb-9b48-a05317b3503c.png)

I only accidentally found this note here:
https://github.com/ufna/VaRest/issues/95

something like this would suffice I think:
https://answers.unrealengine.com/questions/399214/how-to-manually-build-plugins.html

Actually I don't know how to build it myself. Any pointers? I've downloaded the plugin and put it inside the engine plugins folder. Do I need to rebuild the whole engine via the solution?

**Comment by ufna** [comment]
You should place plugin into your project, not the engine. If you want to use it as an engine plugin, it's better to dig how to build plugins and the engine from RunUAT, but is it really required? :)

**Comment by Zenahr** [comment]
@ufna thanks for the pointer! Yeah because I'll be working on multiple projects and will use VaRest on most of them. Saves a bit of time. Also, updating the plugin from just one place is easier than having to do it for every project separately.
