### ISSUE TITLE
Incorrect version number in VaRest.uplugin included in VaRest_1.1-rc8_UE4.8.3_Win.7z

### ISSUE THREAD

**Issue by torus** [ufna/VaRest#33]
In the released [1.1-rc8 .7z file](https://github.com/ufna/VaRest/releases/download/1.1-rc8/VaRest_1.1-rc8_UE4.8.3_Win.7z), I found the .uplugin file contains following lines:

```
	"Version" : 7,
	"VersionName" : "1.1-rc7",
```

The source .zip file looks fine.

**Comment by ufna** [comment]
Thanks, I'll fix it in next release :+1:
