### ISSUE TITLE
Does this using method right?

### ISSUE THREAD

**Issue by Jackyuan999** [ufna/VaRest#330]
Actually I have ever used this plugin in UE4.23, but now I'm porting my project to UE4.26, so I installed it from marketplace in UE4.26. Does this plugin work fine in 4.26? And did this using methos right? please see the following pic, thanks a lot:
I'm not sure about 'Varest Subsystem' node for I didn't see it in UE4.23.
![图片](https://user-images.githubusercontent.com/7939663/103208493-bc8a2400-493b-11eb-9436-e619708faa2a.png)

**Comment by ufna** [comment]
Yes, you're doing this right :) From UE 4.24 most of static methods were wrapped to VaRestSubsystem, so API changed a bit.
