### ISSUE TITLE
Cannot use Plugin with engine built from source

### ISSUE THREAD

**Issue by Zenahr** [ufna/VaRest#331]
# Steps to reproduce

1. Create project
2. Add VaRest to plugins folder of project
3. Activate plugin
4. Close and reopen project
5. Prompt shows "Not compatible, need to rebuild...". Click yes
6. Following error message shows up:

![image](https://user-images.githubusercontent.com/47085752/103333969-260b4f00-4a70-11eb-9136-c87bc1374e11.png)

VaRest used: https://github.com/ufna/VaRest/tree/4.26 (direct download from GitHub. Not release

> I've also tried using the [latest release](https://github.com/ufna/VaRest/releases/tag/v1.1-r30), which yielded the same results.

Engine version: 4.26.0 (source build)

So how do people actually get the plugin working with an engine built from source?

**Comment by ufna** [comment]
@Zenahr ,

you should manually rebuild your project with IDE. It's the solution and will show any real errors. Please try and reopen the issues if something will go wrong.

**Comment by Zenahr** [comment]
@ufna I can't build the project since it's just a Blueprint project with starter content and nothing else. What steps do you suggest?

**Comment by ufna** [comment]
@Zenahr in this case you should add plugin to the engine (not project), and build the plugin manually. Please check https://mercuna.com/building-binary-plugins-in-unreal-engine-4/ as a direction for RunUAT commands.

**Comment by Zenahr** [comment]
@ufna thanks! I'll add a guide if I get it working correctly.
