### ISSUE TITLE
Memory leak with event tick

### ISSUE THREAD

**Issue by GoranKovac** [ufna/VaRest#332]
Hi, I have noticed there is a constant memory increase while using event tick. Initial setup is default
except CALL URL is connected to EVENT TICK since its live json and I need to update it every second.
![image](https://user-images.githubusercontent.com/19614757/104424934-4fec6780-5580-11eb-884c-53194dd78060.png)
This above without anything else connected increases memory, gets to over 8gb from initial 1gb in a hour.

I've also tried to connect everything to event tick (removing the event begin play) but there is no difference

Using latest VaRest with UE 4.24.3

**Comment by GoranKovac** [comment]
![image](https://user-images.githubusercontent.com/19614757/104455195-39a5d200-55a7-11eb-9548-87c194ce3a9f.png)
here is the blueprint, nothing matters behind CALL URL, since I've disconnected it all and the leak is still there,
Its connected to my local json web server.
After running a while 
![image](https://user-images.githubusercontent.com/19614757/104455993-5393e480-55a8-11eb-8a03-26f5daf5ca90.png)
Initial ram is 1.5gb.

If I can help anyhow please let me know, because it becomes unresponsive when it gets to max gpu ram

**Comment by GoranKovac** [comment]
Update:
![image](https://user-images.githubusercontent.com/19614757/104486809-92d42c80-55cc-11eb-9a68-78b35615acf8.png)
This works without problems and without any memory leak.
Is this a bad way? I'm reading json which is constantly updated

**Comment by ufna** [comment]
![image](https://user-images.githubusercontent.com/271578/104756086-5e977200-576c-11eb-9330-941ad3da4240.png)

I've just tested the latest version (UE 4.26), it works like a charm. Maybe it's broken for UE 4.24, but this version is too old to be supported.
