### ISSUE TITLE
JSON GET returns no body

### ISSUE THREAD

**Issue by AgentArachnid66** [ufna/VaRest#336]
I'm trying to get a JSON file held on JSONbin.io and load in the contents to a variable. I currently have the this setup in my blueprint 
![Annotation 2021-02-25 214007](https://user-images.githubusercontent.com/50571566/109225010-9e626800-77b4-11eb-9459-14e88f4daf18.png)
 
If I change the content type to something else, then it prints {} after a second or so and I can see in the output log that it got the correct response back:
```
LogVaRest: Response (200): 
JSON(
{"test":"HW"}
)JSON
```
But with a JSON type it doesn't print anything at all and in the output log I just see
```
LogVaRest: Request (json): GET https://api.jsonbin.io/b/<bin id>/latest 
JSON(
{
}
)JSON
```

Any idea what I could do to fix this?

**Comment by ufna** [comment]
I'm not familiar with jsonbin.io , but it looks like server resposes this way on request with application/json content type.

**Comment by AgentArachnid66** [comment]
Fixed it.
![Annotation 2021-02-26 100159](https://user-images.githubusercontent.com/50571566/109286434-23cc3380-781a-11eb-8e3d-e6d63e7327c6.png)
