### ISSUE TITLE
[HELP] Get simple text from response (non-json response) not working at all

### ISSUE THREAD

**Issue by Zenahr** [ufna/VaRest#340]
Is it possible to parse a response of type `text`?

I'm trying to get VaRest working with this endpoint: `https://api64.ipify.org`
![image](https://user-images.githubusercontent.com/47085752/115438218-6a804d80-a20d-11eb-81ee-7175611df0a6.png)

![image](https://user-images.githubusercontent.com/47085752/115438516-c77c0380-a20d-11eb-9e91-a16fa109d0f4.png)

I don't seem to find a way to do this.

So I've instead tried to get the value of the `ip` field from the `https://api64.ipify.org?format=json` endpoint with no luck. The delegate doesn't seem to fire at all. Why is that?

Blueprint:

![image](https://user-images.githubusercontent.com/47085752/115439074-76204400-a20e-11eb-91cf-9164d46e81ee.png)

log output:

```
LogVaRest: Request (json): GET https://api64.ipify.org?format=json 
JSON(
{
}
)JSON
```

endpoint documentation:

![image](https://user-images.githubusercontent.com/47085752/115439419-da430800-a20e-11eb-923e-d0618c81f6ec.png)

**Comment by ufna** [comment]
Hi @Zenahr ,

Server that you provided expects urlencoded content type, not a json one:

![image](https://user-images.githubusercontent.com/271578/115449005-fe104900-a222-11eb-980a-4cf99794f1d7.png)
