### ISSUE TITLE
Request completes and fails at the same time?

### ISSUE THREAD

**Issue by michael-persch** [ufna/VaRest#342]
I am using the ,,Bind Event On Request Complete" and ,,Bind Event On Request Fail" nodes. For some reason both of the events get called as if the request would complete and fail at the same time. 

For me, it seems like the post request is working, but I cannot find out if it fails because the RequestFailed event always gets thrown.

Take a look at the picture to see how I implemented it.
![image](https://user-images.githubusercontent.com/66703557/118066554-2fea7a80-b39f-11eb-96b8-299f159ddd91.png)

Thank you!

**Comment by ufna** [comment]
Hi @michael-persch ,

You're calling the request twice: 
![image](https://user-images.githubusercontent.com/271578/118180275-02550e00-b43f-11eb-8e42-918a8eef0329.png)

Both process url and apply url functions do the same thing (but in different ways)

**Comment by michael-persch** [comment]
Thank you! 
What exactly are they doing differently? So, I need just one of them? 
Is there any documentation I can look this up?

**Comment by ufna** [comment]
Yes, it's enought to use `ProcessURL` in your case. Apply URL is a latent function to send request without result bingins.

No detailed docs yet :(

**Comment by michael-persch** [comment]
Thank you very much for the info!
