### ISSUE TITLE
Can objects be passed from server to client?

### ISSUE THREAD

**Issue by Gatts011** [ufna/VaRest#344]
Server calls api, res object stored in variable then passed to client function results in error not found.
Can Json Objects be passed to client? Maybe Im not setting it correctly. If not I can just create a map and pass that.

Thanks in advance!

**Comment by ufna** [comment]
Hi @Gatts011 ,

Please provide an example of what you're trying to do.

**Comment by Gatts011** [comment]
Hi @ufna, 

I'll try post screen shots soon as I get my project running on 5.0EA, 
I was passing jsonObject from server to client with custom event input and print as string, no result. I read that arrays also have issues being passed the same way and is a bug,not sure it was resolved. 
I was able to do it by converting to single string passing to client then convert back to json.
Let me know if you are able to investigate and I'll help as much as possible
