### ISSUE TITLE
Content-length is 4 but no data with GET, JSON

### ISSUE THREAD

**Issue by Faleij** [ufna/VaRest#35]
Creating a JSON request (GET, ``JSON``) without any more than binding on complete and fail and calling ``process url`` sends a request with ``content-length`` of 4, but sends no data, eventually resulting in a timeout because the server waits for a body until it timesout and is unable to complete the request. ``application/x-www-form-urlencoded`` on the otherhand, gives a proper ``content-length`` of 0.

Complete request headers:
```
{ host: '127.0.0.1:3000',
  accept: '*/*',
  'content-type': 'application/json',
  'user-agent': 'game=GAME, engine=UE4, version=4.8.3-2634408+++depot+UE4-Releases+4.8',
  'content-length': '4',
  pragma: 'no-cache' }
```
(NodeJS with Express 4 used as server)

**Comment by brunogbrito** [comment]
Having same problem here since 4.8
https://www.youtube.com/watch?v=BMJiketaQ3Y

**Comment by ccll** [comment]
Since content body is meaningless in HTTP GET ([check this thread](http://stackoverflow.com/questions/978061/http-get-with-request-body)), all parameters should be passed in the url in this case, so I think a proper fix is to force content type to be 'x_www_form_urlencoded' when the verb is 'GET'.

**Comment by ufna** [comment]
Hey guys,

@ccll is completely right - you shouldn't use _application/json_ content-type with GET request. It will have "{  }"  body, but it's meaningless. Just use _application/x-www-form-urlencoded_ in this case.
