### ISSUE TITLE
Confirm current workaround for reading Top-Level Arrays in Blueprints

### ISSUE THREAD

**Issue by virtualarchitectures** [ufna/VaRest#350]
Hi,

I've reviewed the [HowTo: Read top-level arrays](https://www.notion.so/HowTo-Read-top-level-arrays-5c6da7c25b044fb3b7de0c9e65d512f5) doc and also reviewed issue #166 . 

![image](https://user-images.githubusercontent.com/10799911/125618771-f4247cf4-e897-4e3e-bc09-e7e0abcb9fb5.png)

I'm still unable to work out which specific nodes I need to use to match that as the nodes in Unreal 4.26.2 appear different, specifically the nodes for converting the Json response to string, constructing the JSON object and setting the value.

![image](https://user-images.githubusercontent.com/10799911/125619593-4ac9ce5e-3573-4dbd-bd78-6caaa1abe1e7.png)

Can you clarify the appropriate nodes by name to help me identify them in the action dropdown that would be appreciated.

Can you also confirm the append values. I'm using `{"data:"` and `"}"` as per issue #166 but I'm unclear if that is correct. I'm assuming I'll then be able to iterate over the Json object with a for loop.

**Comment by ufna** [comment]
Hi @virtualarchitectures ,

For top-level arrays now it's better to use Get Response Value node:

![image](https://user-images.githubusercontent.com/271578/125669494-5d41a844-e2ee-46d0-8c77-f15a0331c323.png)

**Comment by virtualarchitectures** [comment]
Ace! Thank you!
