### ISSUE TITLE
Execute process request usage

### ISSUE THREAD

**Issue by antoine-pous** [ufna/VaRest#353]
I'm currently trying to send a request (GET) to my server. I was using `Call URL` everything works well but it seem impossible to set headers using it.

Then I moved to `Execute Process Request` but for an unknown reason the request is not fired while I'm reaching my notifiaction `Executed!`.

Both events Complete and Fail are not triggered, all parameters are corrects and the server receive nothing.

I'm using UE 4.26.2

![image](https://user-images.githubusercontent.com/7486600/129482105-5d4d0708-4f15-4316-ab12-5c707d71abae.png)

**Comment by ufna** [comment]
hi @antoine-pous 

Execute Process Request is not a latent node, it works asynchronous. So, you can emit this only from OnComplete/OnFail event.

**Comment by antoine-pous** [comment]
As explained the query is never sent, then it cannor fired events

**Comment by ufna** [comment]
Hm, please provide logs

**Comment by antoine-pous** [comment]
How can I enable them ?

**Comment by ufna** [comment]
Click Window -> Developer Tools, then you will see Output Log

**Comment by antoine-pous** [comment]
This is the full debug output, when I start it goes on Login, then authenticate using CallURL, then go on my HttpQuery test which is executed but do not seem to perform any VaREST action

https://user-images.githubusercontent.com/7486600/129539602-a338772e-edd7-45f3-91d3-c91b4e1d00c4.mp4

**Comment by ufna** [comment]
It's not an output log. Output log is a window with text :)

**Comment by antoine-pous** [comment]
Oh sorry!
Here's the output, it's pretty weird, because CallURL reach this endpoint without problem. The server is never reached.

> LogHttp: Warning: 000001C791879D00: invalid HTTP response code received. URL: http://127.0.0.1/serverlist, HTTP code: 0, content length: 0, actual payload size: 0
LogHttp: Warning: 000001C791879D00: request failed, libcurl error: 7 (Couldn't connect to server)
LogHttp: Warning: 000001C791879D00: libcurl info message cache 0 (Found bundle for host 127.0.0.1: 0x1c7aec39d50 [can pipeline])
LogHttp: Warning: 000001C791879D00: libcurl info message cache 1 (Hostname in DNS cache was stale, zapped)
LogHttp: Warning: 000001C791879D00: libcurl info message cache 2 (  Trying 127.0.0.1...)
LogHttp: Warning: 000001C791879D00: libcurl info message cache 3 (TCP_NODELAY set)
LogHttp: Warning: 000001C791879D00: libcurl info message cache 4 (connect to 127.0.0.1 port 80 failed: Connection refused)
LogHttp: Warning: 000001C791879D00: libcurl info message cache 5 (Failed to connect to 127.0.0.1 port 80: Connection refused)
LogHttp: Warning: 000001C791879D00: libcurl info message cache 6 (Closing connection 19)
LogVaRest: Error: Request failed (0): http://127.0.0.1/serverlist

**Comment by ufna** [comment]
Your server refused connection, so it could be something with headers you inserted to the request.

**Comment by antoine-pous** [comment]
Currently I'm logging any query routed and the server is never reached, while it is using CallURL, this is pretty weird.

There's a way to set headers on CallURL query ? It would fix my problems too.

**Comment by ufna** [comment]
No, tech inside is the same. Please try first without any headers modification.

**Comment by antoine-pous** [comment]
Headers array is empty, then no headers are applied. Tried by unplugging the headers and still not working.

Can it be related to the fact that I'm into a function and not the main BP of the widget ?

This implementation is intended to be a wrapper for VaRest.

**Comment by ufna** [comment]
> Can it be related to the fact that I'm into a function and not the main BP of the widget ?

Yes, because all objects created inside are destroyed when function is ended. You should cache all created requests until them finished.

**Comment by antoine-pous** [comment]
Do you have any implementation example for this usage?
