### ISSUE TITLE
About the plug-in does not pass the time correctly

### ISSUE THREAD

**Issue by ghost** [ufna/VaRest#356]
Hello developer, I have some problems when using this plugin, I use the "now" node in ue to intercept the string stitched to the current time, but when I pass it, the space in it will be converted to + which causes the conversion to fail, is there any solution?

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/70359677/134857707-feed3aaa-1ef5-4da0-b702-04146c5baf74.png)
![image](https://user-images.githubusercontent.com/70359677/134857724-1b75ec22-a21f-42a6-8ae3-0efedb2c40f7.png)
The string passed during the call
![image](https://user-images.githubusercontent.com/70359677/134857763-0c4329c2-45f2-46e2-a22a-e554c8ec6e1f.png)
Parameters of the interface
![image](https://user-images.githubusercontent.com/70359677/134857834-c2f47e91-0120-4676-89b4-3380829f7815.png)
Here is the error message:
{"code":400,"success":false,"data":{},"msg":"startTime:Failed to convert property value of type 'java.lang.String' to required type 'java.util.Date' for property 'startTime'; nested exception is org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [@org.springframework.format.annotation.DateTimeFo
rmat java.util.Date] for value '2021-09-20+14:42:09'; nested exception is java.lang.IllegalArgumentException: Parse attempt failed for value [2021-09-20+14:42:09]"}
)JSON

**Comment by ufna** [comment]
It's by design. String in url will be encoded in special form. You should decode it on server, or use another way to deliver data (f.e. json instead of putting it into url). Check https://www.urlencoder.org/ for decoding examples.
