### ISSUE TITLE
Not all variables are passed to a php script handling MySQL db, while it works with a script handling SQLite db

### ISSUE THREAD

**Issue by pbiotech** [ufna/VaRest#359]
Hello,
I am trying to pass two variables from ue4 to a php script which processes MySQL database and constantly get the "Undefined index" error for one of the variables, the second var is ok. When I try to send the same variables to the almost the same script except that this script is handling an SQLite database both vars are passed normally and everything works as expected. What should I do to make sure that all variables are successfully sent to the script processing MySQL? I use ue 4.23. The variables are defined in the php script as following: $php_var = $_REQUEST["ue4_var"]. Thank you.

**Comment by ufna** [comment]
Hi @pbiotech ,

I'm not supporting backend part.
