### ISSUE TITLE
Send a http request no data with GET, JSON

### ISSUE THREAD

**Issue by miaolinvip** [ufna/VaRest#36]
Sorry,My English is very poor~~~~

I find some bug when request with Get Method by json param.

for example:  I  send a json param ={"a",12,"b",23}    ,  result server recv a string "a=12&&b=23" that not keyvalue.

I read  code , at Plugins\VaRest-develop\Source\VaRestPlugin\Private\Json\VaRestRequestJSON.cpp
this function :  FString UVaRestRequestJSON::PercentEncode(const FString& Text)
comment  this line    "OutText = OutText.Replace(TEXT("="), TEXT("%3D"));"

afterward,  server successful recv two KeyValue!

**Comment by ufna** [comment]
Can you show screenshot of your blueprint?

**Comment by miaolinvip** [comment]
![qq 20150909091623](https://cloud.githubusercontent.com/assets/12750342/9751185/35c55746-56d4-11e5-956c-238627c4a6fe.png)
![qq 20150909091933](https://cloud.githubusercontent.com/assets/12750342/9751186/35c84d8e-56d4-11e5-8b91-4945da8514fb.png)
![qq 20150909091307](https://cloud.githubusercontent.com/assets/12750342/9751184/35c42218-56d4-11e5-9c20-ad464a8271ae.png)

Use directly url "xxx.jsp? XXX = xx&xx = 22" is correct, use url with json param,  and then   "=" will be converted to "%3d"

**Comment by iijobs** [comment]
I have the same problem before, I fixed it by modify varest 's c++ code.@va,I suspected 4.8 http api cause this problem.

发自我的 iPhone

**Comment by ufna** [comment]
Fixed in develop branch now. Thanks for feedback!
