### ISSUE TITLE
UE5.1.0 -Package Project failes on VaRest_BreakJson.h

### ISSUE THREAD

**Issue by PeterMHammond** [ufna/VaRest#360]
Initialization Error required adding a contractor to the struct.  Also GENERATED_USTRUCT_BODY is to be replaced with GENERATED_BODY, however this did not effect build status.  Note this wasn't an issue with UE5.0.0 EA

USTRUCT(BlueprintType)
struct FVaRest_NamedType
{
	GENERATED_USTRUCT_BODY()

	UPROPERTY(EditAnywhere, Category = NamedType)
	FName Name;

	UPROPERTY(EditAnywhere, Category = NamedType)
	EVaRest_JsonType Type;

	UPROPERTY(EditAnywhere, Category = NamedType)
	bool bIsArray;

	FVaRest_NamedType()
	{
		Type = EVaRest_JsonType::JSON_String;
		bIsArray = false;
	}
};

In case you are looking for GENERATED_USTRUCT_BODY, in 4.11+, GENERATED_BODY() should be used instead.

**Comment by ufna** [comment]
@EveryGoodWork , thanks for report, should be fixed now :)
