### ISSUE TITLE
engine error ue4.27.1

### ISSUE THREAD

**Issue by BavGames** [ufna/VaRest#364]
hello, I am trying to use it in 4.27.1, I am getting the error that it cannot be used with this engine version, I would be glad if interested

**Comment by ufna** [comment]
@mazlum1414 , which plugin version do you use?

**Comment by mazlum1414** [comment]
> @mazlum1414 , hangi eklenti sürümünü kullanıyorsunuz?

VaRest v1.1.33
UE 4.27.1 Release

**Comment by BavGames** [comment]
> @mazlum1414 , which plugin version do you use?

VaRest v1.1.33
UE 4.27.1 Release

**Comment by ufna** [comment]
Is it build from Marketplace or manually added? Anyway, did you try to force recompile your project?

**Comment by BavGames** [comment]
> Is it build from Marketplace or manually added? Anyway, did you try to force recompile your project?

I have nothing to do with the marketplace. I downloaded the plugin from here and opened a folder called plugins to the project area and added the plugin there, then I compiled my project with visual studio What I always do is I opened the project later on.

as a result i get this error 4.27 is ok but 4.27.1 is getting error

**Comment by ufna** [comment]
[MyProject6.zip](https://github.com/ufna/VaRest/files/7632164/MyProject6.zip)

I just tried to reproduce it on my end, but it works as it should. Please check the demo project above.

**Comment by BavGames** [comment]
> [MyProject6.zip](https://github.com/ufna/VaRest/files/7632164/MyProject6.zip)
> 
> I just tried to reproduce it on my end, but it works as it should. Please check the demo project above.

May I know what engine version you created this with?

**Comment by ufna** [comment]
> May I know what engine version you created this with?

4.27.1 from launcher

**Comment by BavGames** [comment]
> > May I know what engine version you created this with?
> 
> 4.27.1 from launcher

ok thanks i will check and let you know

**Comment by BavGames** [comment]
> > Bunu hangi motor versiyonuyla yaptığınızı öğrenebilir miyim?
> 
> 4.27.1 başlatıcıdan

**Comment by BavGames** [comment]
> May I know what engine version you created this with?
> 
> 4.27.1 from launcher

hello, it didn't open in your project :
![varest](https://user-images.githubusercontent.com/83881717/144245484-d899cd1c-41e8-4c68-a7a8-3d7d2f25b694.png)
(

**Comment by ufna** [comment]
@mazlum1414 , you should do exactly what the system asks you to do. Close editor. Re-generate project files. Open solution and rebuild it with MSVS.

**Comment by BavGames** [comment]
> @mazlum1414 , you should do exactly what the system asks you to do. Close editor. Re-generate project files. Open solution and rebuild it with MSVS.

the editor is closed and i am getting this error even though i rebuild the project files

**Comment by ufna** [comment]
re-check processes or reboot the PC. something wrong locally :)

**Comment by BavGames** [comment]
> re-check processes or reboot the PC. something wrong locally :)

I'm restarting the computer :D
