### ISSUE TITLE
headers

### ISSUE THREAD

**Issue by y0p4** [ufna/VaRest#369]
Hi, how I can call URL with set headers?
I use it like that but not working
![headers](https://user-images.githubusercontent.com/52385396/149214873-e80bc896-4542-44e4-b176-f99c1a80677e.png)

**Comment by ufna** [comment]
@yousifmadan , you should set headers _before_ you call the request :) You shouldn't use CallURL in this case. Just create the request, set headers, and then call ApplyURL or ProcessURL.

I think I should add it as a param to CallURL also.

**Comment by y0p4** [comment]
thanks for your fast replay and your plugin is so cool for API calls
