### ISSUE TITLE
Sporadic crash in UVaRestJsonObject::Reset() when updating data continously

### ISSUE THREAD

**Issue by robertoardila** [ufna/VaRest#37]
Hello, first of all you plugin is excelent and help us a lot in our project, but we have a problem some times when we try to update data each 30 seconds UE4 (4.8.3) crashes with the following error:

Access violation - code c0000005 (first/second chance not available)

""

UE4Editor_VaRestPlugin_36!UVaRestJsonObject::Reset() [g:\projects\personalprojects\ideasthroughiris\sonic_testprojectviernes\sonic_testproject\plugins\varest\source\varestplugin\private\json\varestjsonobject.cpp:23]
UE4Editor_VaRestPlugin_36!UVaRestRequestJSON::ResetResponseData() [g:\projects\personalprojects\ideasthroughiris\sonic_testprojectviernes\sonic_testproject\plugins\varest\source\varestplugin\private\json\varestrequestjson.cpp:109]
UE4Editor_VaRestPlugin_36!UVaRestRequestJSON::OnProcessRequestComplete() [g:\projects\personalprojects\ideasthroughiris\sonic_testprojectviernes\sonic_testproject\plugins\varest\source\varestplugin\private\json\varestrequestjson.cpp:242]
UE4Editor_VaRestPlugin_36!TBaseUObjectMethodDelegateInstance<0,UVaRestRequestJSON,TTypeWrapper<void> __cdecl(TSharedPtr<IHttpRequest,0>,TSharedPtr<IHttpResponse,1>,bool)>::Execute() [e:\ue4\epic games\4.8\engine\source\runtime\core\public\delegates\delegateinstancesimpl_variadics.inl:681]
UE4Editor_VaRestPlugin_36!TBaseUObjectMethodDelegateInstance<0,UVaRestRequestJSON,void __cdecl(TSharedPtr<IHttpRequest,0>,TSharedPtr<IHttpResponse,1>,bool)>::ExecuteIfSafe() [e:\ue4\epic games\4.8\engine\source\runtime\core\public\delegates\delegateinstancesimpl_variadics.inl:770]
UE4Editor_HTTP!TBaseDelegate<void,TSharedPtr<IHttpRequest,0>,TSharedPtr<IHttpResponse,1>,bool>::ExecuteIfBound() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.8\engine\source\runtime\core\public\delegates\delegatesignatureimpl_variadics.inl:519]
UE4Editor_HTTP!FCurlHttpRequest::FinishedRequest() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.8\engine\source\runtime\online\http\private\curl\curlhttp.cpp:711]
UE4Editor_HTTP!FHttpManager::Tick() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.8\engine\source\runtime\online\http\private\httpmanager.cpp:30]
UE4Editor_HTTP!FCurlHttpManager::Tick() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.8\engine\source\runtime\online\http\private\curl\curlhttpmanager.cpp:259]
UE4Editor_Core!FTicker::Tick() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.8\engine\source\runtime\core\private\containers\ticker.cpp:107]
UE4Editor!FEngineLoop::Tick() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.8\engine\source\runtime\launch\private\launchengineloop.cpp:2479]
UE4Editor!GuardedMain() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.8\engine\source\runtime\launch\private\launch.cpp:142]
UE4Editor!GuardedMainWrapper() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.8\engine\source\runtime\launch\private\windows\launchwindows.cpp:126]
UE4Editor!WinMain() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.8\engine\source\runtime\launch\private\windows\launchwindows.cpp:200]

The blueprint we are using to get the data is the following (we get the response in XML):

![blueprint](https://cloud.githubusercontent.com/assets/7445201/9814311/7b5b2900-5852-11e5-83a8-228c4e9b6843.png)

We don't know what could be the cause of the error, so any help will be of great help for us,

Thanks!

**Comment by xulture** [comment]
Could this be happening because of garbage collection?  How long do these requests take to execute?

If request A is being processed, and response has not been received yet, request B could be created.  This will replace value of Request in the blueprint, effectively releasing request A for garbage collection.  If unreal cleans it up, it could cause crashes when eventually, data for request A gets returned back.

Perhaps you should keep your requests in some array to stop garbage collection..

**Comment by ufna** [comment]
Which version of VaRest you're using?
