### ISSUE TITLE
Is there a way to set the raw body independantly of the content type?

### ISSUE THREAD

**Issue by jon-galaz** [ufna/VaRest#375]
Hey, I am trying to get an enrollment request for which I have to send a csr in a POST request with content type pkcs10 and the csr in the body of the request. I can override the content type by setting the content type in the header, but I cannot set the csr in the body without the content type being JSON. Is this possible? Or is this not implemented in the plugin?

**Comment by ufna** [comment]
Did you try `EVaRestRequestContentType::binary` with `SetBinaryRequestContent`?

**Comment by jon-galaz** [comment]
I have tried now. The problem is that I don't know what it expects. Should I make every character of the string a byte and pass that as an array to `SetBinaryRequestContent` ?

**Comment by jon-galaz** [comment]
> I have tried now. The problem is that I don't know what it expects. Should I make every character of the string a byte and pass that as an array to `SetBinaryRequestContent` ?

This will work, with some overhead, but will work. Thanks for the suggestion @ufna.
