### ISSUE TITLE
error

### ISSUE THREAD

**Issue by idk-this** [ufna/VaRest#378]
![image](https://user-images.githubusercontent.com/60819755/163532914-78e57689-5a51-49b1-832c-8d7bd795336a.png)

**Comment by ufna** [comment]
Use "To float" function. Have no idea why UE can't make it automatically.

![image](https://user-images.githubusercontent.com/271578/163552383-8065820b-f875-4e1e-a788-b9443bc844ce.png)

**Comment by idk-this** [comment]
i try but
![image](https://user-images.githubusercontent.com/60819755/163554469-18404f16-731a-49a2-bf3c-6279503e662b.png)

**Comment by ufna** [comment]
@IDKTHISSS you have no any fields for "Make Json" node at your screen :)

**Comment by ufna** [comment]
which plugin version and engine do you use? Are the latest ones?

**Comment by idk-this** [comment]
I didn’t just now notice the version for 5.0, I used version 4.27 manually rebuilt. Sorry but why on marketplace no version for 5.0?

**Comment by ufna** [comment]
it's being processed by Epic, so just waiting for their review :(

**Comment by idk-this** [comment]
Ok. Sorry and gl.

**Comment by ufna** [comment]
you're welcome!
