### ISSUE TITLE
UE4.9?

### ISSUE THREAD

**Issue by onebattleman** [ufna/VaRest#38]
Hello,

Love the plugin, it has helped our project in so many ways and has saved us some valuable development time. 

Just wondering if there's a timeframe on a UE 4.9 update.

Thanks,
Eric

**Comment by xulture** [comment]
Latest development branch of the plugin works just fine under 4.9, just needs to be recompiled.

**Comment by ufna** [comment]
Hi @onebattleman ,

It's already suppoted! No changes required from UE 4.8 version :)
