### ISSUE TITLE
Is there no "serialize object" kind of function?

### ISSUE THREAD

**Issue by kardall** [ufna/VaRest#380]
I want to serialize a characters equipment/clothing or whatever else I need/want.

But nothing seems to exist to just iterate over an object, create a json structure from each entry in it. I see C++ code that someone tried to do this.

Am I missing something?

Example:

Character Creator has a "saved variables" object that contains a characters details (appearance) that I want to send to a database for character storage. So I need to basically create an object like:

```
{
    "characterName":"Person",
    "morphValues": [
        "1.0","2.0","1.1"
    ],
    "hairNames":[
        "long"
    ],
    "apparelNames": [
        "long_sleeved_shirt",
        "cargo_pants"
    ],
    "class":"human_male"
}
```
![image](https://user-images.githubusercontent.com/4186783/165183457-ffad12d1-67e8-46ff-8f23-7a5b2a673766.png)

That is the data structure. I don't care if it has extra things right now... just want it to work, and I can figure out the rest later on the back-end or clean it up manually using a custom struct in blueprint if I have to.

Every other language has it built in, but I am not familiar enough with C++ to try to code my own thing. I will if I have to, but... there should be some way to just 'Serialize Object to VaRest Json Object' that you can then use the "Encode Json to Single String" to attach to a post body in Json for the CallUrl function...

**Comment by kardall** [comment]
I found a plugin that does exactly what I wanted. It's called DBJson on the marketplace. it's free as well... Maybe you could implement it in your plugin.

**Comment by chase03** [comment]
hi! did you know how to use it, struct as varest request object input parameters?

**Comment by kardall** [comment]
I used a plug in called dbjson which has a serialize and deserialize
function.

It let's me take a struct and add it to a string field.

**Comment by chase03** [comment]
[image: image.png]i use dbjson plugin deserialize this but return nothing,
could you share more detail of your blueprint logic please?
Thanks a lot

kardall ***@***.***> 于2023年3月29日周三 23:38写道：

> I used a plug in called dbjson which has a serialize and deserialize
> function.
>
> It let's me take a struct and add it to a string field.
>

**Comment by kardall** [comment]
Here is a video for you so you can follow along :) Enjoy :D 
[https://youtu.be/r_jCv7YS5VY](https://youtu.be/r_jCv7YS5VY)
