### ISSUE TITLE
5.0.2 Make Json crashes with make array

### ISSUE THREAD

**Issue by Puzzabug** [ufna/VaRest#386]
I'm having a crash in unreal engine 5.0.2 when I use a make array node and feed it into a number array in the make json node, it will crash on compile. I'm not sure if it's an issue on your make json node, or if it's with unreal engine. 

Thanks for looking into this! 

Assertion failed: false [File:D:\build\++UE5\Sync\Engine\Source\Editor\KismetCompiler\Private\KismetCompilerMisc.cpp] [Line: 1088] Erroneous pin subcategory for PC_Real: None

[error from make array.txt](https://github.com/ufna/VaRest/files/8960120/error.from.make.array.txt)
[the make array to make json crash node snip.txt](https://github.com/ufna/VaRest/files/8960102/the.make.array.to.make.json.crash.node.snip.txt)

![image](https://user-images.githubusercontent.com/14854307/175102217-304481aa-3c38-4f85-8e9a-eb4fcb7d33c6.png)

**Comment by ufna** [comment]
@Puzzabug , thanks for report, fixed now :)

**Comment by SteinarVatne** [comment]
Will this be in an update soon? :-) I think I have a related issue (different task/nodes, but exact same error message).

**Comment by linjiangwei** [comment]
i have the same problem, use "break json" node with type "Number".

**Comment by ufna** [comment]
It's fixed in latest Marketplace update. Are you sure you're using the latest one?

**Comment by linjiangwei** [comment]
> It's fixed in latest Marketplace update. Are you sure you're using the latest one?

I'm using  "VersionName": "1.1-r32" from epic Marketplace for engine 5.0.3, is it the latest one?  and also compile from Branches 5.0, they get the same  crash.

**Comment by ufna** [comment]
@linjiangwei , could you please make a project that reproduces issue?

**Comment by linjiangwei** [comment]
@ufna  emmm.... , I don't know how to give you the project.

I've tried to create an Blank project , open LevelBlueprint and call any function has float parameter as follow.
![image](https://user-images.githubusercontent.com/28075229/206132551-927326a5-cfd9-4299-bfa8-dab8a8b814de.png)
![企业微信截图_16704025182685](https://user-images.githubusercontent.com/28075229/206131183-674b3469-15ce-4924-aa57-1f1cae4bc797.png)

then click "Compile" button, the engine will crash.
![企业微信截图_16704008008101](https://user-images.githubusercontent.com/28075229/206131216-751c0f7e-e11e-4e76-b928-2e61af7df6f8.png)

**Comment by ufna** [comment]
omg, i forgot to update the 5.0 branch. Fix on github now, will be updated at the Marketplace soon. Sorry.
