### ISSUE TITLE
Body values on POST request

### ISSUE THREAD

**Issue by Neo7252** [ufna/VaRest#389]
Hey, I'm trying to add body params to my login route, it's working on postman, but has you can see on the log, weird characters are sent like '%40' instead of 'at'. Idk if the problem is this, or my code is wrong. Thanks ;)

![image](https://user-images.githubusercontent.com/45879662/190683970-39b54711-08ab-4f75-b2bf-3a9d86e4501f.png)

![Capture d’écran 2022-09-16 181303](https://user-images.githubusercontent.com/45879662/190683838-940b8a73-f824-43b3-a882-8bb4e9e61706.png)
![2](https://user-images.githubusercontent.com/45879662/190683844-6ef20e7a-ad5c-4c08-8ae2-2304dea1bf67.png)

```
LogVaRest: UVaRestRequestJSON::ProcessRequest(372): Request (urlencoded): POST https://localhost:1666/authentication?email=test%40gmail.com&password=Test123%40&strategy=local (check bExtendedLog for additional data)
LogVaRest: Response (401): 
JSON(
{"name":"NotAuthenticated","message":"No account with this email","code":401,"className":"not-authenticated","errors":{}}
)JSON
```

**Comment by kardall** [comment]
That is the post method you have chosen, which is a x-www-url-encoded post object. Change it to JSON and it will put any fields you add as a json object in the post body.
