### ISSUE TITLE
[Make Json] node set a value of 0 for type Number if used with a variable

### ISSUE THREAD

**Issue by chrixbedardcad** [ufna/VaRest#408]
in Unreal Engine 5.1.1, If I try to use a variable (float or integer) connected to [**MakeJson**] node of a type **Number**, the request is always set to 0. If I set the value directly it works.

![2023-02-28_0-16-57](https://user-images.githubusercontent.com/75350983/221761920-d308336f-178c-4d81-85ff-d9894b71ea1e.jpg)

### Request Json Example with Variable Progress_ms connected (ERROR):
```
LogVaRest: Request (json): PUT https://api.spotify.com/v1/me/player/play 
JSON(
{
    "position_ms": 0,
    "uris": [
        "spotify:track:1eb0mORiTlz0OLkH0NPb9Z"
    ]
}
)JSON
```
### Request Json Example with direct value input:
```
LogVaRest: Request (json): PUT https://api.spotify.com/v1/me/player/play 
JSON(
{
    "position_ms": 13000,
    "uris": [
        "spotify:track:1eb0mORiTlz0OLkH0NPb9Z"
    ]
}
)JSON
```

**Comment by chrixbedardcad** [comment]
I made a new image, I try all the possible options I think of but nothing works, any ideas anyone?
![2023-02-28_9-54-09](https://user-images.githubusercontent.com/75350983/221891942-78ade4bb-74ba-4223-8d2b-48879c5544a7.jpg)

**Comment by ufna** [comment]
@chrixbedardcad fixed in development branch, Marketplace update will be here soon

**Comment by chrixbedardcad** [comment]
yeah! thanks it will save me a lot of workaround !
