### ISSUE TITLE
我需要使用post进行文件资源xx.wav文件上传，在服务器进行解析之后，得到json回传回来，但是我不知道使用哪个节点可以实现文件的上传

### ISSUE THREAD

**Issue by PengChaoJay** [ufna/VaRest#417]
我需要使用post进行文件资源xx.wav文件上传，在服务器进行解析之后，得到json回传回来，但是我不知道使用哪个节点可以实现文件的上传

**Comment by BNUZ-HuSir** [comment]
Have you solved it yet?

**Comment by PengChaoJay** [comment]
yes, i have solved it

**Comment by BNUZ-HuSir** [comment]
I only solved the problem of downloading wav, using a UE5 plugin. How did you solve it? Can you share your thoughts?

**Comment by PengChaoJay** [comment]
I figured out just like yours
