### ISSUE TITLE
v1.1 R11 does not work with UE 4.10

### ISSUE THREAD

**Issue by Faleij** [ufna/VaRest#45]
Says it might need to be recompiled and then shuts down.

**Comment by ufna** [comment]
Hi @Faleij ,

What version exactly do you use? 1.1 is common part for more than 10 versions (f.e. 1.1 *rc 10*)

Also, you have to use c++-based project.

**Comment by soulmapp** [comment]
Yes im getting the same problem, 
Im trying VaRest_1.1-r11_UE4.9.2_Win.7z with UE4.10 and its a Blueprint project.and get a warning telling me its the wrong version.
Works fine iwith  VaRest 1.1-rc9  in UE 4.9.2 blueprint project.
Can anyone help

**Comment by ufna** [comment]
Blueprint-only projects have limited support of plugins (f.e. you can't package project of this type with plugin). Just switch you project to code-based one and then it will be fixed!
