### ISSUE TITLE
Using Master Key

### ISSUE THREAD

**Issue by onebattleman** [ufna/VaRest#49]
Hello,

I've been trying to figure out how to use or invoke Master Key but I can't seem to get it to work. I'm trying to backup my data and I don't have a session token for every user. Typically in a website setup you would use/call the master key on the server to carry out such actions. How do I call/use the master key to override the default session token?

**Comment by ufna** [comment]
Hi @onebattleman ,

You should set **X-Parse-Master-Key** with you master key, and it will work.

**Comment by onebattleman** [comment]
Thanks!

**Comment by ufna** [comment]
@onebattleman You're welcome! ;)
