### ISSUE TITLE
Call from Widget

### ISSUE THREAD

**Issue by dfrankes** [ufna/VaRest#50]
Is it possible to get data from a widget? I've tryed multple things but i cannot create an custom event On Complete.

**Comment by onebattleman** [comment]
If you're referring to the retrieving data from your request all you need to do is bind the request to an event using the Bind Event to OnRequestComplete node. And then from the delegate create a custom event. See Image below. 
![2015-12-23_15h59_15](https://cloud.githubusercontent.com/assets/8759320/11984960/245c6f00-a98e-11e5-82e8-ddb22734bf39.png)

**Comment by dfrankes** [comment]
Sorry i ment from function

**Comment by xulture** [comment]
You can do it similarly from a function, however only functions with the same signature as required delegate are shown in the drop-down.  So create a function that takes VaRestRequest reference, then this function will be available in CustonFunction drop down.  Note that you still have to store 'Request' somewhere, or else it is possible that garbage collection will clean it up before response arrives. (eg assign to a variable that is owned by the same widget)

![processrequest](https://cloud.githubusercontent.com/assets/3895512/11991914/a3608f38-aa84-11e5-84f3-752fd3bddb80.png)

![assigndelegate](https://cloud.githubusercontent.com/assets/3895512/11991920/ab882f40-aa84-11e5-9437-7a87a66d76b5.png)

**Comment by ufna** [comment]
@xulture and @onebattleman , thanks! :)

**Comment by dfrankes** [comment]
Thanks!

**Comment by dfrankes** [comment]
I can do this from a GameMode blueprint right? So i dont have to recreate the functions for all levels etc?

**Comment by ufna** [comment]
@dfrankes sure! Personally I'm using GameInsance for stuff like that

**Comment by ufna** [comment]
@dfrankes you're processing url not for the request you've binded on event ;)
