### ISSUE TITLE
Update pls

### ISSUE THREAD

**Issue by DrMcSalad** [ufna/VaRest#51]
Please could you update it to 4.10.1? thanks

**Comment by ufna** [comment]
I strongly recommend you to switch your project to code-based one, because blueprint-only projects even don't support game packaging with plugins.

By the way, I'll try to update pre-compiled version next week. Thanks.

**Comment by onebattleman** [comment]
Can't you just download the source plugin and compile it yourself? It's super easy. @ufna is right you won't even be able to ship/launch your project without switching/converting to a c++ project. It's also very easy to do and you don't even have to convert your Blueprint stuff to code if you don't want too.

**Comment by DrMcSalad** [comment]
I keep getting this
E:/Epic
Games/4.10/Engine/Plugins/VaRest/Source/VaRestEditorPlugin/Classes/VaRest_BreakJson.h(27)
: Property is exposed to the editor or blueprints but has no Category
specified.

2016-01-10 5:18 GMT+01:00 onebattleman <notifications@github.com>:

**Comment by DrMcSalad** [comment]
Nevermind I got it done somehow.

2016-01-10 6:02 GMT+01:00 Martin Hrottek <martin.hrottek@gmail.com>:
