### ISSUE TITLE
Parse Server Support

### ISSUE THREAD

**Issue by onebattleman** [ufna/VaRest#53]
Don't know if you've heard, but the parse service is being shut down to new users starting today and will last for old users until January of next year.  ([See Here](http://blog.parse.com/announcements/moving-on/))

They are providing the option of setting up your own Parse Server which is pretty cool and I was wondering if you could make it so we can set it up to work with our own Parse server. 

From what I can see, all we need to do is change the Request URL from "https://api.parse.com/1/" to whatever URL we're hosting the server.

Is it is possible to make a node that we can set the default request URL that all "Process Parse Requests" will use? 

Or where can I change that manually in C++?

Thanks,
Eric

**Comment by derekvanvliet** [comment]
Yeah a node that that allows you to set this default would be nice. Or possibly a plugin settings panel.

If you just want to change it in your code, you can make that change at the top of this file:

https://github.com/ufna/VaRest/blob/develop/Source/VaRestPlugin/Private/Parse/VaRestParseManager.cpp

**Comment by ufna** [comment]
Sure, I'll add option for that.

**Comment by onebattleman** [comment]
Sweet! Thanks!

**Comment by ufna** [comment]
@onebattleman I've decided to remove Parse API support in current releases, but you can use previous plugin version without any doubt. Url can be easily changed directly in c++ code :)
