### ISSUE TITLE
Remove deprecated compiler rules

### ISSUE THREAD

**Issue by ufna** [ufna/VaRest#55]
> /Users/v.alyamkin/Documents/Unreal Projects/Awm/Plugins/VaRestPlugin/Source/VaRestPlugin/VaRestPlugin.Build.cs(11,62) : warning CS0612: `UnrealBuildTool.RulesCompiler.GetModuleFilename(string)' is obsolete

**Comment by Tauri4n** [comment]
Hey Ufna, did you have a quick fix for this?

**Comment by EwigerWanderer** [comment]
the obsolete changed into an error in 4.11

**Comment by ufna** [comment]
update from **develop** branch
