### ISSUE TITLE
Many thanks!

### ISSUE THREAD

**Issue by joegalaxy71** [ufna/VaRest#57]
Been looking for a plugin like this for ages! 
Will try this today on OSX, I've seen there are some problems on OSX, I'll report with my use case.

**Comment by KhArtNJava** [comment]
Ohhhhh, sweeeeeeeeet! :(

**Comment by joegalaxy71** [comment]
Any news on OSX binaries? That would be really nice, cause many of my students aren't so found on C++. I read that compiling on OSX need a specific SDK, can you point me at that?

**Comment by KhArtNJava** [comment]
If you give me a Mac, then I will give you the necessary solution :) ...

**Comment by joegalaxy71** [comment]
An OSX vm is fine?

Arthur wrote:

**Comment by KhArtNJava** [comment]
For VM you can do it by your self. It's not true way.
Need more motivation.

**Comment by ufna** [comment]
Thanks, guys! :)

OSX binaries won't be supported by me, because I'm not working with Mac every day. It's easy to convert any blueprint project into C++ one by two clicks (just add empty class to it from editor)

**Comment by KhArtNJava** [comment]
Whoa! Nice! :)
