### ISSUE TITLE
Empty field isn't handled correctly, crashed.

### ISSUE THREAD

**Issue by KhArtNJava** [ufna/VaRest#58]
I will be brief.

http://s6.postimg.org/kqqihc73l/screenshot_186.png

`MachineId:02270AEB414EEEE80A2709BB35F6B36B
EpicAccountId:f025becc996c43498a11ed55681e4f0c

Assertion failed: CanWriteObjectWithoutIdentifier() [File:C:\Program Files\Epic Games\4.11\Engine\Source\Runtime\Json\Public\Serialization\JsonWriter.h] [Line: 30] 

UE4Editor_Core!FDebug::AssertFailed() [d:\buildfarm\buildmachine_++ue4+release-4.11\engine\source\runtime\core\private\misc\outputdevice.cpp:430]
UE4Editor_VaRestPlugin!TJsonWriter<wchar_t,TPrettyJsonPrintPolicy<wchar_t> >::WriteObjectStart() [c:\program files\epic games\4.11\engine\source\runtime\json\public\serialization\jsonwriter.h:31]
UE4Editor_VaRestPlugin!FJsonSerializer::Serialize<wchar_t,TPrettyJsonPrintPolicy<wchar_t> >() [c:\program files\epic games\4.11\engine\source\runtime\json\public\serialization\jsonserializer.h:362]
UE4Editor_VaRestPlugin!FJsonSerializer::Serialize<wchar_t,TPrettyJsonPrintPolicy<wchar_t> >() [c:\program files\epic games\4.11\engine\source\runtime\json\public\serialization\jsonserializer.h:88]
UE4Editor_VaRestPlugin!UVaRestRequestJSON::ProcessRequest() [i:\mygame\plugins\varest\source\varestplugin\private\json\varestrequestjson.cpp:341]
UE4Editor_VaRestPlugin!UVaRestRequestJSON::ProcessURL() [i:\mygame\plugins\varest\source\varestplugin\private\json\varestrequestjson.cpp:215]
UE4Editor_VaRestPlugin!UVaRestRequestJSON::execProcessURL() [i:\mygame\plugins\varest\source\varestplugin\classes\json\varestrequestjson.h:101]
UE4Editor_CoreUObject!UFunction::Invoke() [d:\buildfarm\buildmachine_++ue4+release-4.11\engine\source\runtime\coreuobject\private\uobject\class.cpp:4482]
UE4Editor_CoreUObject!UObject::CallFunction() [d:\buildfarm\buildmachine_++ue4+release-4.11\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:562]
UE4Editor_CoreUObject!UObject::execVirtualFunction() [d:\buildfarm\buildmachine_++ue4+release-4.11\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:2022]
UE4Editor_CoreUObject!UObject::ProcessContextOpcode() [d:\buildfarm\buildmachine_++ue4+release-4.11\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:1916]
UE4Editor_CoreUObject!UObject::ProcessInternal() [d:\buildfarm\buildmachine_++ue4+release-4.11\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:781]
UE4Editor_CoreUObject!UFunction::Invoke() [d:\buildfarm\buildmachine_++ue4+release-4.11\engine\source\runtime\coreuobject\private\uobject\class.cpp:4482]
UE4Editor_CoreUObject!UObject::ProcessEvent() [d:\buildfarm\buildmachine_++ue4+release-4.11\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:1150]
UE4Editor_UMG!TMulticastScriptDelegate<FWeakObjectPtr>::ProcessMulticastDelegate<UObject>() [d:\buildfarm\buildmachine_++ue4+release-4.11\engine\source\runtime\core\public\uobject\scriptdelegates.h:459]
UE4Editor_UMG!UButton::SlateHandleClicked() [d:\buildfarm\buildmachine_++ue4+release-4.11\engine\source\runtime\umg\private\components\button.cpp:158]
UE4Editor_UMG!TMemberFunctionCaller<UButton,FReply (__cdecl UButton::*)(void) __ptr64>::operator()<>() [d:\buildfarm\buildmachine_++ue4+release-4.11\engine\source\runtime\core\public\delegates\delegateinstanceinterface_variadics.h:161]
UE4Editor_UMG!TTupleImpl<TIntegerSequence<unsigned int> >::ApplyAfter_ExplicitReturnType<FReply,TMemberFunctionCaller<UButton,FReply (__cdecl UButton::*)(void) __ptr64> >() [d:\buildfarm\buildmachine_++ue4+release-4.11\engine\source\runtime\core\public\delegates\tuple.h:128]
UE4Editor_UMG!TBaseUObjectMethodDelegateInstance<0,UButton,FReply __cdecl(void)>::Execute() [d:\buildfarm\buildmachine_++ue4+release-4.11\engine\source\runtime\core\public\delegates\delegateinstancesimpl_variadics.inl:761]
UE4Editor_Slate!TBaseDelegate<FReply>::Execute() [d:\buildfarm\buildmachine_++ue4+release-4.11\engine\source\runtime\core\public\delegates\delegatesignatureimpl_variadics.inl:521]
UE4Editor_Slate!SButton::OnMouseButtonUp() [d:\buildfarm\buildmachine_++ue4+release-4.11\engine\source\runtime\slate\private\widgets\input\sbutton.cpp:273]
UE4Editor_Slate!<lambda_9ed539f2a96fd1ccd6d2214174cc7705>::operator()() [d:\buildfarm\buildmachine_++ue4+release-4.11\engine\source\runtime\slate\private\framework\application\slateapplication.cpp:4540]
UE4Editor_Slate!FEventRouter::Route<FReply,FEventRouter::FToLeafmostPolicy,FPointerEvent,<lambda_9ed539f2a96fd1ccd6d2214174cc7705> >() [d:\buildfarm\buildmachine_++ue4+release-4.11\engine\source\runtime\slate\private\framework\application\slateapplication.cpp:214]
UE4Editor_Slate!FSlateApplication::RoutePointerUpEvent() [d:\buildfarm\buildmachine_++ue4+release-4.11\engine\source\runtime\slate\private\framework\application\slateapplication.cpp:4530]
UE4Editor_Slate!FSlateApplication::ProcessMouseButtonUpEvent() [d:\buildfarm\buildmachine_++ue4+release-4.11\engine\source\runtime\slate\private\framework\application\slateapplication.cpp:4947]
UE4Editor_Slate!FSlateApplication::OnMouseUp() [d:\buildfarm\buildmachine_++ue4+release-4.11\engine\source\runtime\slate\private\framework\application\slateapplication.cpp:4923]
UE4Editor_Core!FWindowsApplication::ProcessDeferredMessage() [d:\buildfarm\buildmachine_++ue4+release-4.11\engine\source\runtime\core\private\windows\windowsapplication.cpp:1415]
UE4Editor_Core!FWindowsApplication::DeferMessage() [d:\buildfarm\buildmachine_++ue4+release-4.11\engine\source\runtime\core\private\windows\windowsapplication.cpp:1732]
UE4Editor_Core!FWindowsApplication::ProcessMessage() [d:\buildfarm\buildmachine_++ue4+release-4.11\engine\source\runtime\core\private\windows\windowsapplication.cpp:697]
UE4Editor_Core!FWindowsApplication::AppWndProc() [d:\buildfarm\buildmachine_++ue4+release-4.11\engine\source\runtime\core\private\windows\windowsapplication.cpp:619]
user32
user32
UE4Editor_Core!FWindowsPlatformMisc::PumpMessages() [d:\buildfarm\buildmachine_++ue4+release-4.11\engine\source\runtime\core\private\windows\windowsplatformmisc.cpp:884]
UE4Editor!FEngineLoop::Tick() [d:\buildfarm\buildmachine_++ue4+release-4.11\engine\source\runtime\launch\private\launchengineloop.cpp:2610]
UE4Editor!GuardedMain() [d:\buildfarm\buildmachine_++ue4+release-4.11\engine\source\runtime\launch\private\launch.cpp:142]
UE4Editor!GuardedMainWrapper() [d:\buildfarm\buildmachine_++ue4+release-4.11\engine\source\runtime\launch\private\windows\launchwindows.cpp:126]
UE4Editor!WinMain() [d:\buildfarm\buildmachine_++ue4+release-4.11\engine\source\runtime\launch\private\windows\launchwindows.cpp:200]
UE4Editor!__scrt_common_main_seh() [f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:264]
kernel32
ntdll`

**Comment by ufna** [comment]
Unfortunately it's the bug (or feature) of Epic's JSON handler, I can't do anything with it.
