### ISSUE TITLE
Improved usage wiki

### ISSUE THREAD

**Issue by joegalaxy71** [ufna/VaRest#59]
Hi, can you please improve the usage wiki by adding high resolution images? They're too small to read.
Is there any other info source for usage? Can't find any.
Can't wait to use it in my projects!

**Comment by ufna** [comment]
You can open them in a new tab view in full resolution ;)

However, I definitely need documentation refactoring, thanks

**Comment by onebattleman** [comment]
Could you also do one for Batch requests? 

[https://parse.com/docs/rest/guide/#objects-batch](https://parse.com/docs/rest/guide/#objects-batch)

**Comment by btwolfe** [comment]
Yeah, I definitely find the usage wiki to be out of sync with the plugin. I can't reproduce any of the examples in the wiki. The diagrams show elements that don't appear to exist in the blueprint graph editor. I can't find the SET, Bind Event to OnRequestComplete, Bind Event to OnRequestFail, Process URL, etc. Hopefully I'm just missing some obvious detail, but at this point I'm stuck.

**Comment by shaunrandall** [comment]
@btwolfe 

I'm a bit late to the party but for others with the same problem.

You won't be able to get those unless:

A) You are pulling your pin off a JSON Request Variable (pure reference will not work)
![image](https://cloud.githubusercontent.com/assets/10377276/22813102/d7dfd64c-eefd-11e6-8d6d-df4afce8feaf.png)

B) You deselect context sensitive in the top right of the node search box
![image](https://cloud.githubusercontent.com/assets/10377276/22813021/5142b44c-eefd-11e6-9dd3-1d1e38f957ee.png)
