### ISSUE TITLE
Plugin missing or incompatible

### ISSUE THREAD

**Issue by michaeltieso** [ufna/VaRest#61]
I'm getting this message trying to enable the plugin:

> Missing or incompatible modules in VaRestPlugin plugin - would you like to disable it? You will no longer be able to open any assets created using it.

Unreal Engine 4.10.4

**Comment by ufna** [comment]
Latest commit from develop branch is not compatible with UE 4.10. Please use this one instead: https://github.com/ufna/VaRest/commit/f0057ab668a7e9c6063e6e15e01d7d21089059c0
