### ISSUE TITLE
 App Transport Security problem on VaRest request?

### ISSUE THREAD

**Issue by saccomat** [ufna/VaRest#63]
Anybody is experiencing this error? 
 <Error>: App Transport Security has blocked a cleartext HTTP (http://) resource load since it is insecure. Temporary exceptions can be configured via your app's Info.plist file.

I'm using ue 4.11 on Mac. Using only VaRest plugin, making a simple http get request always gives this error.

Thanks

**Comment by saccomat** [comment]
I had to put this string in the "additional plist data" inside projects settings / ios/ to let it work <key>NSAppTransportSecurity</key><dict><key>NSAllowsArbitraryLoads</key><true/></dict>\n

**Comment by ufna** [comment]
@saccomat Yes, it's the proper solution for Mac/OSX. It's not the bug, it's the OS feature :)

**Comment by Tauri4n** [comment]
Hi @saccomat, when I place anything in that field, building/packaging fails. What engine were you running when you had this problem? Have you had any success getting VaRest to work on iOS recently?

**Comment by azinonos** [comment]
@iLoveSarabear I have the same issue, did you manage to solve it?

**Comment by ufna** [comment]
@iLoveSarabear 
What's the exact build error? Do you use valid mobile provision?
