### ISSUE TITLE
Problem with spawning with C++ in VaRest Event.

### ISSUE THREAD

**Issue by KhArtNJava** [ufna/VaRest#64]
Hello.

I am trying to spawn some object with code
```
FActorSpawnParameters SpawnParams;
                 SpawnParams.SpawnCollisionHandlingOverride = ESpawnActorCollisionHandlingMethod::AlwaysSpawn;
                 AMyFurnitureActor* myFurniture = GWorld->GetWorld()->SpawnActor<AMyFurnitureActor>(MyItemBlueprint, location, rotation, SpawnParams);
```

Yeah, it's spawned... But not in game - only in UE Editor window: Initial level: 
![some]
(https://answers.unrealengine.com/storage/temp/91233-screenshot_242.png)
After code execution there are no furniture actor in game: 
![some]
(https://answers.unrealengine.com/storage/temp/91234-screenshot_243.png)
it present in UE Editor: 
![some]
(https://answers.unrealengine.com/storage/temp/91235-screenshot_244.png)
Why this code spawning actors in UE Editor, but not in game?
I have some level with GameMode override BaseLevelGameMode BP.

In the BaseLevelGameMode Player Controller is MainPlayerController.

MainPlayerController has code 
![some]
(https://answers.unrealengine.com/storage/temp/91275-screenshot_245.png)
GetGameObjectForSpawn has code
![s]
(https://answers.unrealengine.com/storage/temp/91276-3.png)
GetGameObjectForSpawn_OK has code 
![]
(https://answers.unrealengine.com/storage/temp/91277-4.png)
Full code of my function is

```
AMyFurnitureActor* ULoadFunctions::MyLoadFurnitureObjectByName(const FString FurnitureName, FVector location, FRotator rotation, UWorld* World)
 {
     UObjectLibrary * lib = UObjectLibrary::CreateLibrary(AMyFurnitureActor::StaticClass(), true, true);
     FString name = "";
     if (FurnitureName.EndsWith(TEXT("_C"))) {
         name = FurnitureName.Left(FurnitureName.Len() - 2);
     }
 
     lib->AddToRoot();
     int32 loaded = lib->LoadBlueprintAssetDataFromPath("/Game/");
 
     TArray<FAssetData> Assets;
     lib->GetAssetDataList(Assets);
   
     for (int32 i = 0; i < Assets.Num(); ++i) {
 
         FAssetData& assetData = Assets[i];
         FString assetDataObjectPath = assetData.ObjectPath.ToString();
 
         if (assetDataObjectPath.EndsWith(name)) {
             auto cls = StaticLoadObject(UObject::StaticClass(), nullptr, *assetDataObjectPath);
 
             UBlueprint * bp = Cast<UBlueprint>(cls);
             TSubclassOf<class UObject> MyItemBlueprint;
             MyItemBlueprint = (UClass*)bp->GeneratedClass;
 
             World = GWorld->GetWorld();
 
             if (World) {
 
                 FActorSpawnParameters SpawnParams;
                 SpawnParams.SpawnCollisionHandlingOverride = ESpawnActorCollisionHandlingMethod::AlwaysSpawn;
                 AMyFurnitureActor* myFurniture = World->SpawnActor<AMyFurnitureActor>(MyItemBlueprint, location, rotation, SpawnParams);
                 return myFurniture;
             }
             else {
                 return nullptr;
             }
         }
     }
 
     return nullptr;
 }
```
If game started in Standalone game mode, furniture spawned in game, not in UE Editor...
Why Event, that Binded to OnRequestComplete received UE Editor as World, but not my games world? IE, why it's spawned not in game, but in UE Editor?
And how to fix that?

**Comment by ufna** [comment]
Please log each step first. What's the result of GetAssetDataList(Assets) in editor/standalone modes? 

Also, World = GWorld->GetWorld(); in editor will be the editor world, not the game one.
