### ISSUE TITLE
Can't package HTML5 version with plugin build from Marketplace

### ISSUE THREAD

**Issue by ufna** [ufna/VaRest#66]
> I get the same unknown error when packaging for HTML 5 with the plugin enabled. Packaging for Win64 works fine with the plugin enabled and disabling the plugin allows packaging for HTML 5.
> 
> I am using the plugin, installed from the marketplace, with UE 4.11.2 provided by the launcher.

https://forums.unrealengine.com/showthread.php?13509-Plugin-Http-s-REST-blueprintable-JSON-and-Parse-REST-API-manager-at-once-(VaRest)&p=537862&viewfull=1#post537862

**Comment by PHLA12** [comment]
I was getting the same issue, I changed packaging from development to Debug and shipping and the HTML5 project packaged and ran. Doesn't return any data when it runs, shows a response code of -1 and triggers REST Failed. Works perfectly on Win64 banging my head against the wall on  HTML5. (Also tried with Github version in 4.12 - same issues), happy to supply any further info you need.

**Comment by SuperRey** [comment]
@PHLA12 check if it is related to cross-domain same-origin policies.
