### ISSUE TITLE
Can't compile plugin for UE 4.13.0

### ISSUE THREAD

**Issue by KhArtNJava** [ufna/VaRest#76]
Hello.

I tried to compile this plugin with/for 4.13 and got error

```
e:\MyGame\Plugins\VaRest\Source\VaRestEditorPlugin\Private\VaRest_BreakJson.cpp(58): error C2440: '=': cannot convert from 'UEdGraphPin *' to 'UObject *'
e:\MyGame\Plugins\VaRest\Source\VaRestEditorPlugin\Private\VaRest_BreakJson.cpp(58): note: Types pointed to are unrelated; conversion requires 
```

58 line is 
`	FieldNameTerm->Source = Pin;`

**Comment by ufna** [comment]
Thanks @KhArtNJava for report, I'll check it soon.

**Comment by unktomi** [comment]
In 4.13 it seems they changed EdGraphPin to be a struct instead of UObject derived class.  And they added a SourcePin field to BPTerminal. So I guess the fix is to assign to FieldNameTerm->SourcePin instead of FieldNameTerm->Source.

**Comment by ufna** [comment]
Thanks to @unktomi
