### ISSUE TITLE
Add ability to modify/set request headers

### ISSUE THREAD

**Issue by Dr-Jerm** [ufna/VaRest#79]
Hello! Thanks for developing this and making it available. I would like have the ability to set arbitrary headers on calls so that I can implement some security/authentication. For example a dedicated server talking to a REST api will only accept requests with a specific header that the client builds will not have.

"authentication": "DSKLFJ302adKDLSFj",
"source": "dedicated"
or something of the sort.
I could include this in the json payload as a workaround, but generally security/authentication is maintained through headers.

**Comment by Dr-Jerm** [comment]
Looking a little further into it, it does appear that Unreal's HTTP library does offer pretty easy access to setting headers:
```
Request->SetHeader(TEXT("User-Agent"), "X-UnrealEngine-Agent");
```
So it would just be a matter of integration that makes sense with your architecture.

**Comment by ufna** [comment]
Hi @Dr-Jerm ,

It's already here! :) Check SetHeader function: https://github.com/ufna/VaRest/blob/develop/Source/VaRestPlugin/Classes/VaRestRequestJSON.h#L118-L120

**Comment by Dr-Jerm** [comment]
Context Sensitive search made a fool of me yet again. Thanks!

**Comment by ufna** [comment]
@Dr-Jerm You're welcome ;)

**Comment by DunkenKBliths** [comment]
Ah... this is a good point.... 
I have actually tried using the header for security and it doesnt seem to work for me ?
(I had to start looking at another solution...but would love your plugin to work !)

I can supply you test code (javascript) if you want to see if you can get it working ?

It kept falling over for me...and saying header not present !

**Comment by Dr-Jerm** [comment]
Not sure what "security" you are trying to implement (something like OAuth?). However the first step is to make sure that the header is being set unreal side and that it is coming through to the javascript (Node.js I assume) side. You should be able to pretty simply inspect/log out the headers from javascript to make sure they are getting passed along. If they are... then the issue really lies with your implementation of said security. My naive (haven't really given it a huge amount of thought yet) plan is to add an Unreal config variable/key on dedicated servers ONLY and then add that value as a header for requests to my API which is expecting to see that key (for requests that should be coming from a dedicated server).

I'd be curious to hear what you have planned @DunkenKBliths .

**Comment by DunkenKBliths** [comment]
Ah my confusing message...probably...

The Javascript is a working version of a call to a web server  (which needs to be converted to work in blueprints) .... I have no access to the web server to see what is being sent over...

So actually not sure if the Unreal is actually sending it...
