### ISSUE TITLE
How can i send a Json string to get response instead of sending a Json object?

### ISSUE THREAD

**Issue by ZJOnline** [ufna/VaRest#81]
Because i want to encrypt the Json string .But Call URL function can just receive VARest Json Object.Is there any other method that i do't know? Thank you for helping me >.<

**Comment by ufna** [comment]
What's the format of data your server expects to get?

**Comment by ZJOnline** [comment]
just a string  has been encrypted,like this:                            
{
    "result": "1",
    "reason": "success"
}
encrypt to ------>
r9RDW0JRTlqpLXyQnD/Rpf93us7pPmNTMIKD86Yl7sVwCbdQjzaBkmT4SA8qnvOLeAfMdpdt1TCee8MJRMdQsEagYihearCE

**Comment by ufna** [comment]
In this case you can use just _ResponseObject->GetResponseString()_

**Comment by ZJOnline** [comment]
I mean, I want to send json string instead of a UVaRestJsonObject object to server.I have known how to receive a string.Thank you for replying

**Comment by ufna** [comment]
What ContentType is expected by server? You can try to use ERequestContentType::binary

**Comment by ZJOnline** [comment]
![image](https://cloud.githubusercontent.com/assets/12392483/18632834/ff4fc5a6-7eab-11e6-847e-2a7a9b902786.png)

**Comment by ZJOnline** [comment]
see,I just want this input become a FString.is that possible?

**Comment by ufna** [comment]
I've checked code and found that its impossible for now. But also I'm confused about this content type. Could you make the working example here: https://www.hurl.it/ ?

**Comment by ZJOnline** [comment]
![image](https://cloud.githubusercontent.com/assets/12392483/18654812/9b98c2c2-7f16-11e6-8fa3-315978c13fad.png)
![image](https://cloud.githubusercontent.com/assets/12392483/18654821/a682d57e-7f16-11e6-86df-f67e8805a5b2.png)
I don't know how to recompily a plugin.so,I copy your code and create my own class ,it works well.Thank you for your help  :smile:

**Comment by ufna** [comment]
Got your idea, #83 created ;)
