### ISSUE TITLE
Using plugin from C++ compilation issue

### ISSUE THREAD

**Issue by SuperRey** [ufna/VaRest#85]
Hello,

First of all, thanks @ufna for the plugin, it is a really good work ;)

I have been using the plugin for a long time, but only from Blueprints. Now I am decided to start using it from C++.

I configured my Project.Build.cs adding:

`PrivateDependencyModuleNames.AddRange(new string[] { "VaRestPlugin" });
PrivateIncludePathModuleNames.AddRange(new string[] { "VaRestPlugin" });`

Then I added the following headers to one of my .h files as I will use an UVaRestRequestJSON object (note that I am using a previous version with a outdated folder structure):

`#include "Http.h"
#include "Classes/Json/VaRestRequestJSON.h"`

I needed to add the Http.h or else I would get an "identifier "FHttpResponsePtr" is undefined" and "identifier "FHttpRequestPtr" is undefined" errors.

Then in the corresponding .cpp file I added the following headers as I will use some more objects defined in the plugin:

`#include "Classes/Json/VaRestJsonValue.h"
#include "Classes/Json/VaRestJsonObject.h"`

At this point I was getting a linker error:

`unresolved external symbol "public: class UVaRestJsonObject * __cdecl UVaRestJsonValue::AsObject(void)" (?AsObject@UVaRestJsonValue@@QEAAPEAVUVaRestJsonObject@@XZ)`

I tried to find out what was the problem until I noticed that the UVaRestJsonValue class definition was lacking the VARESTPLUGIN_API macro (unlike the UVaRestJsonObject class definition). Once I added the macro I succesfully compiled the project.

@ufna can you tell me if this is the right way or it is a "not recommended" way of doing things?

Thanks again!

**Comment by ufna** [comment]
Hi @SuperRey ,

Thanks for feedback, adding _API macro is the right thing to be done here :) I've missed it and will and it to the next release.
