### ISSUE TITLE
VaRest not in build

### ISSUE THREAD

**Issue by thomja** [ufna/VaRest#86]
Hello

So I just got VaRest for my project and I finished making what I needed in blueprint, which was a very basic GET request.

I placed it in the level blueprint so it should surely come with the game upon cooking. But nothing works after I've compiled the project. The console does not show anything specific, I've tried searching for 'varest' and 'plugin' but nothing related to varest shows up.

I've tried searching for this but haven't been able to find a working solution. Tried adding the plugins into the /Plugins/ folder of the project.

The game builds fine without any errors.

**Comment by ufna** [comment]
Is it blueprint project or C++ based one? Are you using marketplace version of plugin?

**Comment by ufna** [comment]
Please reopen issue if you have any questions.
