### ISSUE TITLE
Complete event not firing

### ISSUE THREAD

**Issue by R4VANG3R** [ufna/VaRest#87]
I'm trying to get a response event to fire in my player state. It works in my game instance class but not in my player state.

I'm working in 4.12.5 with VaRest 4.12.0

![image](https://cloud.githubusercontent.com/assets/3693009/19803804/024844d6-9d0b-11e6-870a-96897b00bbf6.png)
![image](https://cloud.githubusercontent.com/assets/3693009/19803807/095ce736-9d0b-11e6-8a73-fd8a2ca18a59.png)
![image](https://cloud.githubusercontent.com/assets/3693009/19803810/0c62c022-9d0b-11e6-9ce3-91231781f868.png)

This is the setup right now.

I tried debugging the C++ code and it seems to register the events but only handles the one in the game instance, the ones in the player state never fire.

**Comment by ufna** [comment]
Are you sure that player state isn't recreated by game mode logic?
