### ISSUE TITLE
No connection on android.

### ISSUE THREAD

**Issue by pigravity** [ufna/VaRest#89]
Cant connect on android if device is connecting thru wifi only. libcurl ends with - CURLE_COULDNT_RESOLVE_HOST (6)

**Comment by ufna** [comment]
Hi @pigravity ,

What's the URL you're trying to resolve?

**Comment by pigravity** [comment]
For example:

http://gamejolt.com/api/game/v1/data-store/?game_id=211609&key=test&signature=6e8cf880d9b7aaa74f23657fb834be50

**Comment by ufna** [comment]
Unfortunately I'm not able to reproduce it on my end. Please check that you haven't any connection limitations on your device.
