### ISSUE TITLE
Can't bind to OnRequestComplete in c++

### ISSUE THREAD

**Issue by bowringjb** [ufna/VaRest#91]
I've tried a million different ways and nothing works for me, I really don't know what I'm doing wrong but I'm getting all manner of errors, like these:
`error: no matching member function for call to '__Internal_AddDynamic'`
and
```
candidate function [with UserClass = FPlayFabRequestAction] not viable: no known conversion from 'void (FPlayFabRequestAction::*)(UVaRestJsonObject *)' to 'typename FDelegate::TMethodPtrResolver<FPlayFabRequestAction>::
FMethodPtr' (aka 'void (FPlayFabRequestAction::*)(UVaRestRequestJSON *)') for 2nd argument
```

Here is the class I'm trying to bind from, It's a latent action, I'm trying to make a wrapper around va_rest so I can do some extra operations depending on the result of a request. Here's the relevant code:

```
class FPlayFabRequestAction : public FPendingLatentAction
{
public:
	UVaRestRequestJSON* JSON;
	FString Url;
	FString Ticket;
	EPlayFabRequestResult& Exec;
    FName ExecutionFunction;
    int32 OutputLink;
    FWeakObjectPtr CallbackTarget;
    FPlayFabRequestAction(UVaRestRequestJSON* Data, FString Endpoint, FString ticket, EPlayFabRequestResult& Branches, const FLatentActionInfo& LatentInfo) :
		JSON(Data),
		Url(Endpoint),
		Ticket(ticket),
		Exec(Branches),
		ExecutionFunction(LatentInfo.ExecutionFunction),
		OutputLink(LatentInfo.Linkage),
		CallbackTarget(LatentInfo.CallbackTarget)
    {
		UE_LOG(LogTemp, Error, TEXT("Latent contructor was called!"));
		JSON->OnRequestComplete.AddDynamic(this, &FPlayFabRequestAction::OnRequestComplete);
    }
    virtual void UpdateOperation(FLatentResponse& Response) override
    {
		Exec = EPlayFabRequestResult::Success;
        Response.FinishAndTriggerIf(true, ExecutionFunction, OutputLink, CallbackTarget);
    }
	void OnRequestComplete(UVaRestJsonObject* Result) {
		UE_LOG(LogTemp, Error, TEXT("Response Complete"));
	}
};
```

I just can't get my head around what that error means. What am I doing wrong, I'm pulling my hair out trying to get this working and I'm on a deadline that's approaching fast. Please, please advise me anybody.

**Comment by Ruhrpottpatriot** [comment]
The error means, that the compiler can't find your function to bind to the delegate. Since VaRest uses dynamic multicast delegates all funtions nthat are going to be bound to the delegates need to be decorated with the **UFUNCTION()** macro.
