### ISSUE TITLE
UE 4.14 - 4.15 support ?

### ISSUE THREAD

**Issue by motorsep** [ufna/VaRest#93]
Does it work in UE 4.14 and 4.15 on for Android ?

If not, is support for those versions/platform coming soon ?

Thanks

**Comment by ufna** [comment]
Hi @motorsep ,

UE 4.14 is already supported - you can get the last version of plugin from Marketplace or source.

4.15 is not tested yet, I'll make an update once the stable version will be released.

**Comment by ufna** [comment]
UE 4.15 is supported now (in develop branch)
