### ISSUE TITLE
My JSON is Valid But Fails Decode

### ISSUE THREAD

**Issue by shaunrandall** [ufna/VaRest#94]
I get this directly from the logs.  Decode JSON always returns 0.

{"total_pages":1,"page":1,"data":[{"id":2,"ship_model_id":{"json":"some_location_here","id":1},"owner_player_id":{"last_login_datetime":null,"id":1,"gold_balance":1000,"pod_skin_location":1,"last_action_taken_datetime":null},"fleet_id":{}},{"id":3,"ship_model_id":{"json":"some_location_here","id":1},"owner_player_id":{"last_login_datetime":null,"id":3,"gold_balance":1000,"pod_skin_location":1,"last_action_taken_datetime":null},"fleet_id":{}}],"status_code":200,"message":"OK"}

Any ideas?

**Comment by shaunrandall** [comment]
If helpful:
![image](https://cloud.githubusercontent.com/assets/10377276/22771933/adfa97e0-ee4e-11e6-961b-21c700aa7ef9.png)

**Comment by shaunrandall** [comment]
And of course after 4 hours of troubleshooting and finally posting it I look like an idiot and figure it out.

You have to construct it as a json object before using it even if it is already a reference to a json object.  Did not see in docs anywhere and not very intuitive but I won't forget again.


![image](https://cloud.githubusercontent.com/assets/10377276/22772083/78eb0246-ee4f-11e6-8181-250cb24b962c.png)

**Comment by ufna** [comment]
@shaunrandall I's great that you solved it ;)
