### ISSUE TITLE
Decode Json and Get Number Field return a wrong number

### ISSUE THREAD

**Issue by yellowiscool** [ufna/VaRest#96]
Hi,

Using VaRest 1.1-r16, it seems that a wrong number is sometimes returned.

![2017-03-10 18_19_16-multitouchtests - unreal editor](https://cloud.githubusercontent.com/assets/45740/23803096/1e51fb4c-05be-11e7-833e-facf64cdb63c.png)
![2017-03-10 18_19_08-multitouchtests - unreal editor](https://cloud.githubusercontent.com/assets/45740/23803097/1e5d3d7c-05be-11e7-97aa-116c69da9838.png)

The JSON string is `{"Id":16842749}`

And 16842749 != 16842748 indeed.

**Comment by yellowiscool** [comment]
It seems to be a bug from Unreal and not VaRest.

It works with `double` though.

```cpp
FString jsonDocument(TEXT("{\"Id\":16842749}"));
TSharedPtr<FJsonObject> JsonObject = MakeShareable(new FJsonObject());
TSharedRef< TJsonReader<> > JsonReader = TJsonReaderFactory<>::Create(jsonDocument);

if (FJsonSerializer::Deserialize(JsonReader, JsonObject) && JsonObject.IsValid())
{
	float numberFloat = JsonObject->GetNumberField(FString(TEXT("Id")));
	double numberDouble = JsonObject->GetNumberField(FString(TEXT("Id")));
	
	GEngine->AddOnScreenDebugMessage(-1, 15.0f, FColor::Yellow,
		FString::Printf(TEXT("Id float: %f\nId double: %f"),
			numberFloat, numberDouble));
}
```

![2017-03-10 23_03_06-demarrer](https://cloud.githubusercontent.com/assets/45740/23813064/c8ca90d0-05e5-11e7-9274-b1196e9183fe.png)

**Comment by yellowiscool** [comment]
[I submitted a bug report.](https://answers.unrealengine.com/questions/574208/float-fjsonobjectgetnumberfield-returns-wrong-valu.html)

**Comment by yellowiscool** [comment]
Ok, so it's a `float` issue.

Unreal only implements the double, and the bug comes from VaRest that cast it to float. And floats are not very good to represent big numbers.

 * Could VaRest have a `double GetNumberField` in addition to the float version ?
 * Could VaRest implement a `int32 GetIntegerField` ?

**Comment by ufna** [comment]
Yep, it's a float issue.

Thanks for pull request! :)
