### ISSUE TITLE
Packaging for Android

### ISSUE THREAD

**Issue by jmusictouch** [ufna/VaRest#98]
Hi,
I am having problems packaging a project I am making for the Android Platform and was wondering if I am missing something. I downloaded the Plugin through the Marketplace and am working on UE 4.15. Whilst packaging for Android (ATC), the following error appeared

`UATHelper: Packaging (Android (ATC)): Running AutomationTool...
UATHelper: Packaging (Android (ATC)): Automation.ParseCommandLine: Parsing command line: -ScriptsForProject="C:/Users/Scrypter/Documents/Unreal Projects/vrCommerce/vrCommerce.uproject" BuildCookRun -nocompile -nocompileeditor -installed -nop4 -project="C:/Users/Scrypter/Documents/Unreal Projects/vrCommerce/vrCommerce.uproject" -cook -stage -archive -archived
irectory=C:/Users/Scrypter/Desktop/vrCommerce -package -clientconfig=Development -ue4exe=UE4Editor-Cmd.exe -pak -prereqs -nodebuginfo -targetplatform=Android -cookflavor=ATC -build -CrashReporter -utf8output
UATHelper: Packaging (Android (ATC)): Automation.Process: Setting up command environment.
UATHelper: Packaging (Android (ATC)): BuildCookRun.SetupParams: Setting up ProjectParams for C:\Users\Scrypter\Documents\Unreal Projects\vrCommerce\vrCommerce.uproject
UATHelper: Packaging (Android (ATC)): Project.Build: ********** BUILD COMMAND STARTED **********
UATHelper: Packaging (Android (ATC)): CommandUtils.Run: Run: C:\Program Files\Epic Games\UE_4.15\Engine\Binaries\DotNET\UnrealBuildTool.exe vrCommerce Android Development -Project="C:\Users\Scrypter\Documents\Unreal Projects\vrCommerce\vrCommerce.uproject"  "C:\Users\Scrypter\Documents\Unreal Projects\vrCommerce\vrCommerce.uproject"  -remoteini="C:\Users\Scr
ypter\Documents\Unreal Projects\vrCommerce" -noxge -generatemanifest -NoHotReload
UATHelper: Packaging (Android (ATC)): UnrealBuildTool: NDK version: 24, GccVersion: 4.9
UATHelper: Packaging (Android (ATC)): CommandUtils.Run: Run: Took 1.026259s to run UnrealBuildTool.exe, ExitCode=0
UATHelper: Packaging (Android (ATC)): CommandUtils.Run: Run: C:\Program Files\Epic Games\UE_4.15\Engine\Binaries\DotNET\UnrealBuildTool.exe vrCommerce Android Development -Project="C:\Users\Scrypter\Documents\Unreal Projects\vrCommerce\vrCommerce.uproject"  "C:\Users\Scrypter\Documents\Unreal Projects\vrCommerce\vrCommerce.uproject"  -remoteini="C:\Users\Scr
ypter\Documents\Unreal Projects\vrCommerce" -noxge -NoHotReload -ignorejunk
UATHelper: Packaging (Android (ATC)): UnrealBuildTool: Creating makefile for vrCommerce (changes to target files)
UATHelper: Packaging (Android (ATC)): UnrealBuildTool: NDK version: 24, GccVersion: 4.9
UATHelper: Packaging (Android (ATC)): UnrealBuildTool: Compiling Native code with NDK API 'android-24'
UATHelper: Packaging (Android (ATC)): UnrealBuildTool: Performing 1 actions (4 in parallel)
UATHelper: Packaging (Android (ATC)): UnrealBuildTool: [1/1] clang++.exe vrCommerce-arm64-es2.so
UATHelper: Packaging (Android (ATC)): UnrealBuildTool: clang++.exe: error: no such file or directory: 'C:/Program Files/Epic Games/UE_4.15/Engine/Plugins/Marketplace/VaRestPlugin/Binaries/Android/UE4-VaRestPlugin-arm64-es2.a'
UATHelper: Packaging (Android (ATC)): UnrealBuildTool: Total build time: 4.15 seconds (Local executor: 1.24 seconds)
UATHelper: Packaging (Android (ATC)): CommandUtils.Run: Run: Took 4.4287821s to run UnrealBuildTool.exe, ExitCode=5
UATHelper: Packaging (Android (ATC)): Program.Main: ERROR: AutomationTool terminated with exception: AutomationTool.CommandUtils+CommandFailedException: Command failed (Result:5): C:\Program Files\Epic Games\UE_4.15\Engine\Binaries\DotNET\UnrealBuildTool.exe vrCommerce Android Development -Project="C:\Users\Scrypter\Documents\Unreal Projects\vrCommerce\vrCom
merce.uproject"  "C:\Users\Scrypter\Documents\Unreal Projects\vrCommerce\vrCommerce.uproject"  -remoteini="C:\Users\Scrypter\Documents\Unreal Projects\vrCommerce" -noxge -NoHotReload -ignorejunk. See logfile for details: 'UnrealBuildTool-2017.03.17-00.33.04.txt' 
UATHelper: Packaging (Android (ATC)):    at AutomationTool.CommandUtils.RunAndLog(String App, String CommandLine, String Logfile, Int32 MaxSuccessCode, String Input, ERunOptions Options, Dictionary`2 EnvVars, SpewFilterCallbackType SpewFilterCallback)
UATHelper: Packaging (Android (ATC)):    at AutomationTool.CommandUtils.RunAndLog(CommandEnvironment Env, String App, String CommandLine, String LogName, Int32 MaxSuccessCode, String Input, ERunOptions Options, Dictionary`2 EnvVars, SpewFilterCallbackType SpewFilterCallback)
UATHelper: Packaging (Android (ATC)):    at AutomationTool.CommandUtils.RunUBT(CommandEnvironment Env, String UBTExecutable, String CommandLine, String LogName, Dictionary`2 EnvVars)
UATHelper: Packaging (Android (ATC)):    at AutomationTool.CommandUtils.RunUBT(CommandEnvironment Env, String UBTExecutable, FileReference Project, String Target, String Platform, String Config, String AdditionalArgs, String LogName, Dictionary`2 EnvVars)
UATHelper: Packaging (Android (ATC)):    at AutomationTool.UE4Build.BuildWithUBT(String TargetName, UnrealTargetPlatform TargetPlatform, String Config, FileReference UprojectPath, Boolean ForceMonolithic, Boolean ForceNonUnity, Boolean ForceDebugInfo, Boolean ForceFlushMac, Boolean DisableXGE, String InAddArgs, Boolean ForceUnity, Dictionary`2 EnvVars)
UATHelper: Packaging (Android (ATC)):    at AutomationTool.UE4Build.Build(BuildAgenda Agenda, Nullable`1 InDeleteBuildProducts, Boolean InUpdateVersionFiles, Boolean InForceNoXGE, Boolean InUseParallelExecutor, Boolean InForceNonUnity, Boolean InForceUnity, Boolean InShowProgress, Dictionary`2 PlatformEnvVars, Nullable`1 InChangelistNumberOverride, Dictionar
y`2 InTargetToManifest)
UATHelper: Packaging (Android (ATC)):    at Project.Build(BuildCommand Command, ProjectParams Params, Int32 WorkingCL, ProjectBuildTargets TargetMask)
UATHelper: Packaging (Android (ATC)):    at BuildCookRun.DoBuildCookRun(ProjectParams Params)
UATHelper: Packaging (Android (ATC)):    at BuildCookRun.ExecuteBuild()
UATHelper: Packaging (Android (ATC)):    at AutomationTool.BuildCommand.Execute()
UATHelper: Packaging (Android (ATC)):    at AutomationTool.Automation.Execute(List`1 CommandsToExecute, CaselessDictionary`1 Commands)
UATHelper: Packaging (Android (ATC)):    at AutomationTool.Automation.Process(String[] Arguments)
UATHelper: Packaging (Android (ATC)):    at AutomationTool.Program.MainProc(Object Param)
UATHelper: Packaging (Android (ATC)):    at AutomationTool.InternalUtils.RunSingleInstance(Func`2 Main, Object Param)
UATHelper: Packaging (Android (ATC)):    at AutomationTool.Program.Main()
UATHelper: Packaging (Android (ATC)): Program.Main: AutomationTool exiting with ExitCode=5 (5)
UATHelper: Packaging (Android (ATC)): BUILD FAILED
PackagingResults:Error: Error Unknown Error`

By reading this, I can only pick up that I am missing a certain file "UE4-VaRestPlugin-arm64-es2.a", but I might be wrong. I would like to use this plugin for my project as it has helped my project a lot. Any help regarding this issue would really be appreciated.

**Comment by ufna** [comment]
Hi,

arm64 is not supported by marketplace plugins. Please switch to armv7, or install VaRest manually from Github
